{"title": "Software Engineer", "company": "incoalliance", "company_type": "Outstaff", "salary": null, "technologies": ["Pandas", "API", "TensorFlow", "Git", "Airflow", "Docker", "Python", "Kubernetes", "Jenkins", "Redis", "Go", "Elasticsearch", "Spark", "Microservices", "OOP", "AI"], "location": ["Україна"]}
{"title": "SEnior Python WMS", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["API", "Wms", "Python", "Go", "Linux", "OOP", "AI"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Senior Python Developer", "company": "TechMagic", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "CI/CD", "React", "PostgreSQL", "Node.Js", "JavaScript", "Python", "Angular", "Selenium", "Go", "DevOps", "AWS", "Django", "OOP", "AI"], "location": ["Україна"]}
{"title": "Tech Lead (Python/Django/JS)", "company": "PLANEKS", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "Go", "AI", "Python"], "location": ["Україна"]}
{"title": "Junior Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": null, "technologies": ["API", "CI/CD", "Postman", "Git", "Python", "Go", "AWS", "AI"], "location": ["Україна"]}
{"title": "Senior Python Backend Developer", "company": "TechHunt", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "CI/CD", "Python", "Go", "Elasticsearch", "Django"], "location": ["Німеччина", "Нідерланди", "Польща", "Україна", "Португалія"]}
{"title": "Junior software engineer (parsing/reverse)", "company": "Artellence", "company_type": "Product", "salary": "до $2500", "technologies": ["Requests", "Security", "Redis", "AI", "asyncio", "SQL", "NoSQL", "Docker", "Go", "Parsing", "Java", "BeautifulSoup", "Python", "Selenium", "Linux", "aiohttp", "MongoDB", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Python NLP Developer", "company": "Tangible AI", "company_type": "Agency", "salary": "$600-1200", "technologies": ["CI/CD", "Git", "Python", "Go", "Django", "Nlp", "AI"], "location": ["Сполучені Штати"]}
{"title": "Middle Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["API", "CI/CD", "Postman", "Git", "Python", "Go", "AWS", "AI"], "location": ["Україна"]}
{"title": "Developer for AI ChatGPT bot", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI"], "location": ["Україна", "Польща"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": "$1200-2500", "technologies": ["Git", "Python", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Full Stack Engineer (Python/React)", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "Requests", "MySQL", "React", "JavaScript", "Python", "TypeScript", "Go", "AWS", "Django", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["API", "SQL", "HTML", "CSS", "Git", "Python", "Linux", "ML"], "location": ["Україна"]}
{"title": "Python Developer", "company": "NONAME DIGITAL", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["API", "Git", "Docker", "Python", "Linux", "Redis", "DevOps", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Python Backend Engineer", "company": "Reef Technlogies", "company_type": "Product", "salary": "$7560-11760", "technologies": ["Python", "Go", "Embers", "Django", "AI"], "location": ["Польща"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["API", "AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["RabbitMQ", "Bigdata", "CI/CD", "Spark", "Cassandra", "Redis", "Moment", "GCP", "AI", "SQL", "Go", "Elasticsearch", "Django", "Git", "Airflow", "Python", "Apache", "MongoDB", "API", "Kafka", "MySQL", "AWS"], "location": ["Румунія"]}
{"title": "Senior Backend Engineer", "company": "Launch Labs", "company_type": "Outsource", "salary": null, "technologies": ["API", "FastAPI", "React", "TypeScript", "Python", "Go", "GraphQL", "AWS", "Flask", "ML", "Celery", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "FastAPI", "Git", "Python", "Flask", "Dash", "OOP", "AI"], "location": ["Україна"]}
{"title": "Quantitative Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Git", "Python", "Go", "Linux", "OOP", "AI"], "location": ["Україна"]}
{"title": "Data and Machine Learning Engineer (Python)", "company": "Softwarium", "company_type": "Outsource", "salary": null, "technologies": ["TensorFlow", "Spark", "PyTorch", "AI", "Pandas", "SQL", "NoSQL", "React", "Docker", "Go", "Embers", "Dask", "Git", "Python", "Angular", "Scikit-learn", "ML", "OOP", "API", "Azure", "AWS", "NumPy"], "location": ["Польща", "Україна"]}
{"title": "Team Lead Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["API", "Git", "Docker", "Python", "Linux", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["JavaScript", "Python", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Junior Python Developer in Test (CSA)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["SQL", "CI/CD", "Pytest", "NoSQL", "Git", "Jenkins", "Docker", "Python", "Linux", "AWS", "asyncio", "ML", "AI"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["API", "AI", "Python"], "location": ["Україна"]}
{"title": "Senior Full-Stack Engineer Python/React", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "Azure", "SQL", "React", "PySpark", "Python", "Docker", "Spark", "Go", "TypeScript", "DevOps", "D3", "Flask", "SQLAlchemy", "Celery", "Dask", "AI"], "location": ["Україна"]}
{"title": "Data Mining Engineer needed for data centric startup", "company": "Forecasa", "company_type": "Product", "salary": null, "technologies": ["Pandas", "CI/CD", "Git", "Airflow", "Docker", "Python", "Selenium", "Kubernetes", "Spark", "PySpark", "AI"], "location": ["Сполучені Штати"]}
{"title": "Backend Engineer with AI Integration Experience", "company": "Visarsoft", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["Azure", "React", "TensorFlow", "AI", "JavaScript", "TypeScript", "Python", "Angular", "AWS", "Agile", "Nlp", "Tdd"], "location": ["Україна"]}
{"title": "Data Scientist / Senior Python developer", "company": "Simplify", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "Tensorrt", "Git", "Python", "Go", "PyTorch", "ML", "OpenCV", "Sota"], "location": ["Україна", "Німеччина", "Польща"]}
{"title": "Senior Data Engineer", "company": "Intetics", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["SQL", "API", "Etl", "Git", "Python", "Airflow", "Go", "AWS", "GCP", "ML", "AI"], "location": ["Україна"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "API", "SQL", "HTML", "CSS", "React", "PostgreSQL", "JavaScript", "Python", "Go", "Embers", "ML", "AI"], "location": ["Польща"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "MySQL", "FastAPI", "React", "Git", "Python", "Docker", "Go", "PHP", "Elasticsearch", "Flask", "Django", "AWS", "Apache", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python + Scala Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "API", "SQL", "PostgreSQL", "Python", "Go", "Embers", "Scala", "AI"], "location": ["Польща"]}
{"title": "Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": "$700-800", "technologies": ["Pandas", "API", "SQL", "HTML", "NoSQL", "Python", "Selenium", "Embers", "Flask", "ML", "BeautifulSoup", "Scraping", "AI"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["English", "JavaScript", "Mentoring", "Python", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["React", "Git", "Python", "Go", "PHP", "Django", "OOP", "AI"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "Chatmasters", "company_type": "Product", "salary": null, "technologies": ["API", "SQL", "Drf", "FastAPI", "Restapi", "Websockets", "Python", "Postgressql", "Go", "ChatGPT", "Linux", "Flask", "AWS", "ML", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Django developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["API", "FastAPI", "Python", "Go", "Django", "Celery", "AI"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "SPS Commerce", "company_type": "Product", "salary": null, "technologies": ["API", "CI/CD", "Docker", "Python", "Kubernetes", "DevOps", "Embers", "AWS", "AI"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "CI/CD", "NoSQL", "FastAPI", "Django", "PostgreSQL", "Python", "Docker", "Go", "AWS", "Flask", "GCP", "ML", "GraphQL", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "FXC Intelligence", "company_type": "Product", "salary": "$5000-7000", "technologies": ["SQL", "API", "Docker", "Python", "AI"], "location": ["Велика Британія"]}
{"title": "Fullstack Software Developer (Python+React)/ AI enthusiast", "company": "Forex Tester Software Inc", "company_type": "Product", "salary": "$700-1500", "technologies": ["Vue", "API", "Svelte", "React", "Git", "Python", "Angular", "Go", "ChatGPT", "Embers", "AI"], "location": ["Україна"]}
{"title": "Senior Python Engineer (Application Platform Track)", "company": "PandaDoc", "company_type": "Product", "salary": null, "technologies": ["Pandas", "SQL", "Kafka", "RabbitMQ", "FastAPI", "PostgreSQL", "AI", "Git", "Python", "Docker", "Kubernetes", "Go", "Rabbimq", "AWS", "Django", "asyncio"], "location": ["Польща", "Португалія", "Україна"]}
{"title": "Application Engineer", "company": "UnameIT", "company_type": "Product", "salary": null, "technologies": ["AI", "Git", "Fabric", "Python"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Product", "salary": null, "technologies": ["API", "SQL", "FastAPI", "Git", "Python", "Flask", "Dash", "OOP", "AI"], "location": ["Україна"]}
{"title": "Back-end Developer (experience with GPT API)", "company": "TechHunt", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["API", "Node.Js", "Git", "Python", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["RESTful", "API", "FastAPI", "asyncio", "React", "Git", "Python", "Angular", "Go", "Embers", "GCP", "AI"], "location": ["Польща", "Хорватія", "Словаччина"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Azure", "API", "Xml", "Json", "Python", "Go", "AWS", "ML", "AI"], "location": ["Україна"]}
{"title": "Quantitative Analyst", "company": "Weem", "company_type": "Product", "salary": "$1500-2800", "technologies": ["SQL", "Perl", "Phyton", "Python"], "location": ["Канада"]}
{"title": "Middle Python developer", "company": "Blackthorn Vision", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["Black", "AI", "Pandas", "SQL", "HTML", "React", "TypeScript", "Go", "Django", "CSS", "Git", "Python", "Angular", "Linux", "Github", "Scipy", "Flask", "ML", "API", "Azure", "Node.Js", "JavaScript", "AWS", "NumPy"], "location": ["Україна"]}
{"title": "Senior Python Developer/DevOps Engineer", "company": "Powercode", "company_type": "Outsource", "salary": "$3000-6000", "technologies": ["Azure", "CI/CD", "Git", "Kibana", "Python", "Kubernetes", "Go", "DevOps", "Elasticsearch", "Dash", "AI"], "location": ["Німеччина", "Польща", "Україна"]}
{"title": "Technical Lead", "company": "Zoot", "company_type": "Product", "salary": "$3000-4200", "technologies": ["RESTful", "API", "HTML", "JWT", "CSS", "Node.Js", "JavaScript", "Python", "Bootstrap", "jQuery", "Go", "Linux", "ML", "AI"], "location": ["Україна"]}
{"title": "backend CRM розробник", "company": "Stablexsolution", "company_type": "Product", "salary": "$1500-3000", "technologies": ["SQL", "CSS", "React", "JavaScript", "Python", "Go", "Scss", "Django"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "API", "NoSQL", "Restapi", "FastAPI", "Python", "Go", "DevOps", "Embers", "Django", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Temy", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["API", "SQL", "React", "PostgreSQL", "Python", "Go", "Django", "GraphQL"], "location": ["Україна"]}
{"title": "Senior Python developer (with DevOps experience)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "API", "NoSQL", "FastAPI", "Python", "Go", "DevOps", "Embers", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Fullstack Engineer (python+react)", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["RESTful", "API", "SQL", "HTML", "MySQL", "React", "PostgreSQL", "CSS", "Git", "TypeScript", "Python", "JavaScript", "Go", "Django", "ML", "AI"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "FastAPI", "Git", "Python", "Flask", "Dash", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "React", "PostgreSQL", "Git", "JavaScript", "Jenkins", "Python", "Kubernetes", "Go", "Airflow", "Embers", "Flask", "Apache", "AI"], "location": ["Польща"]}
{"title": "Strong Junior Python Software Engineer", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "CI/CD", "Webpack", "Redis", "Redux", "asyncio", "AI", "SQL", "React", "PostgreSQL", "Docker", "Go", "Elasticsearch", "CSS", "Git", "Python", "Kubernetes", "aiohttp", "Click", "MongoDB", "API", "Kafka", "Celery", "GraphQL"], "location": ["Україна"]}
{"title": "Senior Python Software Engineer", "company": "TEAM International", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["API", "SQL", "NoSQL", "Django", "Git", "Python", "Go", "GCP", "AI"], "location": ["Польща", "Португалія"]}
{"title": "Senior Full Stack Engineer with Python and Golang", "company": "TeamDev", "company_type": "Outstaff", "salary": null, "technologies": ["Azure", "SQL", "CI/CD", "React", "PostgreSQL", "Git", "JavaScript", "Python", "Docker", "Kubernetes", "Go", "AWS", "GCP", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Python Developer (middle)", "company": "Fordewind", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["Pandas", "SQL", "HTML", "NoSQL", "Git", "JavaScript", "Python", "Go", "DevOps", "Elasticsearch", "Flask", "AWS", "ML", "Celery", "AI"], "location": ["Україна"]}
{"title": "Software Engineer (Python) (G)", "company": "Freelance", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "Bigdata", "CI/CD", "MySQL", "PostgreSQL", "Git", "Airflow", "Python", "Spark", "Redis", "Go", "DevOps", "Moment", "AWS", "Apache", "MongoDB", "AI"], "location": ["Румунія"]}
{"title": "Python Engineer Team Lead", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "Python", "Spark", "Hadoop", "AWS", "Emr", "OOP", "AI"], "location": ["Україна"]}
{"title": "Database Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "до $2500", "technologies": ["Pandas", "SQL", "RabbitMQ", "HTML", "Webpack", "MySQL", "React", "PostgreSQL", "CSS", "Etl", "Python", "Angular", "Linux", "Redis", "Go", "Django", "ML", "Celery"], "location": ["Україна"]}
{"title": "Senior Python Developer-a на ізраїльський фінтех проєкт", "company": "Ciklum International", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["SQL", "Git", "Python", "Spark", "Kubernetes", "Data", "AI"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Pytest", "AI", "SQL", "PostgreSQL", "Docker", "Go", "Embers", "Falcon", "Git", "Python", "Kubernetes", "Linux", "Flask", "aiohttp", "SQLAlchemy", "OOP", "API", "MySQL", "Tornado"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": "$3000-5500", "technologies": ["Pandas", "SQL", "RabbitMQ", "React", "PostgreSQL", "Node.Js", "Airflow", "Docker", "Python", "Redis", "Go", "Embers", "Django", "Celery", "OOP", "AI"], "location": ["Україна", "Польща", "Вірменія"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": "$1200-2500", "technologies": ["Git", "Python", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "PLANEKS", "company_type": "Outstaff", "salary": null, "technologies": ["API", "FastAPI", "Python", "Go", "Django", "Celery", "AI"], "location": ["Україна"]}
{"title": "Django Developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["API", "FastAPI", "Python", "Go", "Django", "Celery", "AI"], "location": ["Україна"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": null, "technologies": ["API", "Reactjs", "Golang", "React", "Git", "Python", "Docker", "Kubernetes", "Go", "DevOps", "Embers", "GraphQL", "OOP", "AI"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Python Back-end Developer /Candidates from Ukraine     JobTestPrep", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["RESTful", "API", "SQL", "CI/CD", "NoSQL", "React", "PostgreSQL", "Git", "Docker", "Python", "Kubernetes", "Go", "Angular", "AWS", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "DAAS Support ENG", "company": "Temerix", "company_type": "Product", "salary": "$700-800", "technologies": ["SQL", "HTML", "Requests", "NoSQL", "CSS", "Python", "Go", "Moment", "ML", "AI"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "CodeIT", "company_type": "Outsource", "salary": "від $2000", "technologies": ["API", "SQL", "CI/CD", "PostgreSQL", "Git", "Docker", "Python", "Go", "Ansible", "DevOps", "Embers", "Linux", "Django", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": "до $2000", "technologies": ["RESTful", "API", "SQL", "NoSQL", "Git", "Python", "Go", "AWS", "AI"], "location": ["Польща"]}
{"title": "Backend Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$3500-4500", "technologies": ["RESTful", "API", "HTML", "CSS", "Git", "JavaScript", "Docker", "Python", "Kubernetes", "Go", "AWS", "Foundation", "ML", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "IvorySoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Python", "Django"], "location": ["Україна"]}
{"title": "Senior/Lead Python Developer", "company": "CHI Software", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["CI/CD", "GCP", "AI", "SQL", "NoSQL", "Docker", "Go", "DevOps", "Elasticsearch", "Django", "FastAPI", "Python", "Linux", "Flask", "aiohttp", "API", "Azure", "JavaScript", "AWS", "PHP"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Danavero", "company_type": "Outstaff", "salary": "$2000-4000", "technologies": ["API", "HTML", "CI/CD", "Node.Js", "Pyramid", "Git", "JavaScript", "Python", "Kubernetes", "Go", "Embers", "Flask", "Django", "AWS", "ML", "OOP", "AI"], "location": ["Польща"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Pytest", "AI", "SQL", "PostgreSQL", "Docker", "Go", "Embers", "Falcon", "Git", "Python", "Kubernetes", "Linux", "Flask", "aiohttp", "SQLAlchemy", "OOP", "API", "MySQL", "Tornado"], "location": ["Україна"]}
{"title": "Senior Python/Django Engineer", "company": "at Apexive", "company_type": "Agency", "salary": "від $3000", "technologies": ["RESTful", "SQL", "MySQL", "React", "Docker", "Python", "Kubernetes", "Go", "AWS", "Django", "AI"], "location": ["Чехія", "Нідерланди", "Польща", "Україна"]}
{"title": "Strong Python Developer", "company": "NGM Agency", "company_type": "Product", "salary": "від $3000", "technologies": ["API", "SQL", "HTML", "MySQL", "CSS", "PostgreSQL", "Git", "JavaScript", "Docker", "Python", "Go", "PHP", "Linux", "Puppet", "Django", "ML", "OOP", "AI"], "location": ["Україна"]}
{"title": "Backend Developer for AutoGPT", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Git", "Python"], "location": ["Україна", "Польща"]}
{"title": "Python developer (AIOHttp)", "company": "TheWhyKingz", "company_type": "Product", "salary": null, "technologies": ["SQL", "PostgreSQL", "Python", "Redis", "Go", "Shiny", "Embers", "Linux", "aiohttp", "MongoDB", "AI"], "location": ["Латвія"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Multithreading", "Databases", "Git", "Python", "Linux", "Solid", "OOP", "AI"], "location": ["Україна"]}
{"title": "Python Developer - AI Automation Solutions (LLaMA, ChatGPT Agents, Auto-GPT, LangChain)", "company": "Aimech", "company_type": "Product", "salary": "до $2500", "technologies": ["API", "FastAPI", "Llm", "Python", "Langchain", "ChatGPT", "ML", "Nlp", "AI"], "location": ["Велика Британія", "Україна"]}
{"title": "Middle Python+Node.JS Engineer", "company": "A-Team Global", "company_type": "Outsource", "salary": null, "technologies": ["HTML", "CSS", "Node.Js", "Python", "Go", "Embers", "ML", "AI"], "location": ["Болгарія", "Німеччина", "Україна"]}
{"title": "Senior Full Stack Developer (Python)", "company": "SalesNash", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "HTML", "CSS", "FastAPI", "PostgreSQL", "Js", "React", "Git", "Python", "Go", "Flask", "ML", "Webpack", "AI"], "location": ["Канада"]}
{"title": "Back End Engineer ( Python\\Java\\Go) with Data Engineering experience", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $7500", "technologies": ["API", "Kafka", "Flink", "CI/CD", "Spark", "ML", "AI"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Numerical Technologies", "company_type": "Product", "salary": "$2000-4000", "technologies": ["RESTful", "API", "Azure", "FastAPI", "Git", "Python", "Go", "AWS", "AI"], "location": ["Сполучені Штати", "Україна", "Португалія", "Польща", "Сінгапур"]}
{"title": "Intelligent Automation Full Stack  Developer - Open A.I. and No Code A.I. is a plus", "company": "Mentally", "company_type": "Product", "salary": "$2500-3700", "technologies": ["Azure", "Automation", "Saas", "Git", "Python", "Docker", "Go", "DevOps", "AWS", "ML", "AI"], "location": ["Італія"]}
{"title": "Python Developer", "company": "GEO Pay", "company_type": "Product", "salary": null, "technologies": ["SQL", "API", "Azure", "Drf", "PostgreSQL", "Python", "Redis", "Go", "AWS", "Django", "Foundation", "Celery", "AI"], "location": ["Україна"]}
{"title": "Senior Machine Learning Engineer  video", "company": "PAYRUN", "company_type": "Product", "salary": "$5000-10000", "technologies": ["Python"], "location": ["Україна"]}
{"title": "Strong Junior/Middle Python Developer", "company": "Vilmate", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "NoSQL", "FastAPI", "PostgreSQL", "Git", "Python", "Docker", "Redis", "Go", "DevOps", "AWS", "Django", "Celery", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Middle/Senior Python engineer", "company": "Disoft", "company_type": "Product", "salary": null, "technologies": ["API", "SQL", "Node.Js", "PostgreSQL", "Python", "Rest", "Go", "Django"], "location": ["Україна", "Польща", "Хорватія", "Португалія", "Чехія"]}
{"title": "Python developer", "company": "Embedd", "company_type": "Product", "salary": "$1500-3000", "technologies": ["API", "SQL", "PostgreSQL", "Git", "Python", "ML", "AI"], "location": ["Німеччина", "Велика Британія", "Україна"]}
{"title": "Senior Python Developer", "company": "Radency", "company_type": "Outstaff", "salary": null, "technologies": ["RabbitMQ", "Spark", "Redis", "GCP", "Postgres", "AI", "Pandas", "SQL", "NoSQL", "PostgreSQL", "Docker", "Elasticsearch", "Flux", "Airflow", "Git", "Python", "Flask", "Apache", "API", "GraphQL"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "CloudMade", "company_type": "Product", "salary": "$1500-3000", "technologies": ["Pandas", "SQL", "API", "aiohttp", "FastAPI", "PostgreSQL", "Scikit-learn", "Git", "Python", "Docker", "Spark", "Go", "Apache", "AWS", "Flask", "ML", "OOP", "AI"], "location": ["Польща"]}
{"title": "Python Back-end Developer (JobTestPrep)", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["RESTful", "SQL", "API", "CI/CD", "NoSQL", "React", "Git", "Python", "Docker", "Kubernetes", "Go", "Angular", "AWS", "AI"], "location": ["Україна", "Грузія", "Кіпр"]}
{"title": "Python Team Lead", "company": "SoftConstruct", "company_type": "Product", "salary": null, "technologies": ["RESTful", "API", "SQL", "Kafka", "FastAPI", "Airflow", "Python", "Spark", "Kubernetes", "Go", "Ansible", "DevOps", "Beam", "Apache", "aiohttp", "OOP", "AI"], "location": ["Україна"]}
{"title": "Full-Stack Python Developer (with Angular)", "company": "Virtuace", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "API", "Azure", "CI/CD", "FastAPI", "Git", "Docker", "Python", "Kubernetes", "Go", "Angular", "ML", "NumPy", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Sr. Python Developer", "company": "TrustPoint", "company_type": "Product", "salary": "$2000-4000", "technologies": ["RESTful", "API", "CI/CD", "Git", "Python", "Go", "DevOps", "Django", "ML", "AI"], "location": ["Сполучені Штати"]}
{"title": "Python Lead  Developer", "company": "Genius Software", "company_type": "Product", "salary": "$4500-6000", "technologies": ["AI", "Git", "Python"], "location": ["Сполучені Штати"]}
{"title": "Software Engineering Team Lead", "company": "AllSTARSIT", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "AI"], "location": ["Україна"]}
{"title": "Full Stack Developer", "company": "UKR.NET", "company_type": "Product", "salary": null, "technologies": ["Redis", "Redux", "AI", "asyncio", "SQL", "NoSQL", "React", "PostgreSQL", "TypeScript", "Go", "Elasticsearch", "Python", "aiohttp", "MongoDB", "Sqlite", "API", "MySQL", "JavaScript", "MobX"], "location": ["Україна"]}
{"title": "Python Developer", "company": "IT Svit", "company_type": "Outsource", "salary": "від $3000", "technologies": ["TensorFlow", "Rest", "AI", "SQL", "React", "PostgreSQL", "Docker", "Go", "DevOps", "Elasticsearch", "Django", "Git", "Python", "ML", "MongoDB", "Microservices", "API", "Kafka", "jQuery"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$5000", "technologies": ["API", "CI/CD", "Cognito", "Airflow", "Python", "Go", "DevOps", "Flask", "AWS", "Apache", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "Python/Django REST API Backend Developer", "company": "Smart UI", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["Backend", "AI", "Crypto", "SQL", "HTML", "NoSQL", "React", "PostgreSQL", "Docker", "Go", "DevOps", "Django", "CSS", "Git", "Python", "Angular", "Linux", "ML", "MongoDB", "API", "MySQL", "JavaScript", "jQuery", "AWS", "PHP"], "location": ["Україна"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "API", "SQL", "HTML", "CSS", "React", "PostgreSQL", "JavaScript", "Python", "Go", "Embers", "ML", "AI"], "location": ["Польща"]}
{"title": "Python developer", "company": "Olearis", "company_type": "Outsource", "salary": "$1000-2500", "technologies": ["API", "SQL", "Requests", "FastAPI", "PostgreSQL", "Python", "Go", "AWS", "SQLAlchemy", "OOP", "AI"], "location": ["Україна"]}
{"title": "ML/Python Senior", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["Azure", "SQL", "CI/CD", "Python", "ML", "AI"], "location": ["Україна"]}
{"title": "Python Team Lead", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["Python", "Go", "Linux", "OOP", "AI"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Python Developer (Django)", "company": "IT Svit", "company_type": "Outsource", "salary": "від $3000", "technologies": ["API", "Kafka", "SQL", "React", "PostgreSQL", "Django", "TensorFlow", "Git", "jQuery", "Python", "Docker", "Go", "DevOps", "Elasticsearch", "Keycloak", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Lead Python Engineer  (challenging omnichannel payment processing solution for Europe and North America)", "company": "Godel Technologies", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["API", "Azure", "SQL", "CI/CD", "MySQL", "FastAPI", "PostgreSQL", "Git", "Python", "Docker", "Go", "DevOps", "AWS", "Flask", "GCP", "AI"], "location": ["Польща", "Литва", "Болгарія"]}
{"title": "Python developer", "company": "Ciba Health", "company_type": "Product", "salary": "до $3000", "technologies": ["RESTful", "API", "SQL", "HTML", "CSS", "Django", "Pyramid", "Git", "Python", "Kubernetes", "Redis", "Go", "DevOps", "AWS", "Flask", "ML", "GraphQL", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Vidby", "company_type": "Product", "salary": "$1200-2500", "technologies": ["RabbitMQ", "API", "SQL", "PostgreSQL", "Python", "Redis", "Go", "Django", "Celery", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer (experience in ML projects using Python)", "company": "ISRAEL IT", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["English", "API", "CI/CD", "Git", "Python", "Docker", "Kubernetes", "Go", "Spark", "Embers", "AWS", "ML", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data Skills (AdTech Location Technology Leader)", "company": "Sigma Software", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "Python", "Spark", "Go", "Hadoop", "AWS", "Emr", "OOP", "AI"], "location": ["Польща", "Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Orderry", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "Pytest", "Redis", "Redux", "asyncio", "AI", "SQL", "React", "PostgreSQL", "Celery", "Docker", "Go", "Django", "Python", "Kubernetes", "Selenium", "aiohttp", "Kafka", "Webpack"], "location": ["Україна"]}
{"title": "Senior Python Engineer with JS/Typescript", "company": "Intellias", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Pandas", "Azure", "SQL", "React", "PySpark", "Python", "Docker", "Spark", "Go", "TypeScript", "DevOps", "Embers", "D3", "Flask", "SQLAlchemy", "Celery", "Dask", "AI"], "location": ["Україна"]}
{"title": "Experienced Python Developer - lifetime opportunity", "company": "CleverCrew", "company_type": "Product", "salary": "$2500-4000", "technologies": ["API", "Svelte", "FastAPI", "Git", "Jenkins", "Go", "Django", "Postgres", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "EVE.calls", "company_type": "Product", "salary": "$4000", "technologies": ["TensorFlow", "Websockets", "Python", "Grpc", "Unix"], "location": ["Україна"]}
{"title": "Middle/Senior Full-stack Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["RESTful", "API", "Azure", "CI/CD", "React", "Git", "Docker", "Jenkins", "Kubernetes", "Go", "AWS", "Django", "GCP", "AI"], "location": ["Велика Британія", "Польща", "Україна"]}
{"title": "Senior Python Developer (with DevOps)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "API", "Azure", "CI/CD", "NoSQL", "FastAPI", "Chef", "Python", "Docker", "Go", "Ansible", "DevOps", "Embers", "Puppet", "AWS", "Django", "ML", "AI"], "location": ["Україна", "Польща", "Грузія"]}
{"title": "Middle/Senior Python Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["RESTful", "API", "Postman", "CI/CD", "Swagger", "Git", "Python", "Docker", "Kubernetes", "Jenkins", "AI"], "location": ["Україна"]}
{"title": "Technical Lead Python", "company": "Meest Group", "company_type": "Product", "salary": "$1000-4000", "technologies": ["SQL", "CI/CD", "React", "PostgreSQL", "Git", "Python", "Docker", "Go", "AWS", "Django"], "location": ["Україна"]}
{"title": "Odoo Senior Developer", "company": "Mongrov", "company_type": "Product", "salary": null, "technologies": ["API", "Go", "Odoo", "ML", "AI"], "location": ["Колумбія", "Польща", "Україна"]}
{"title": "Strong Junior/Middle Data Scientist", "company": "AppReal", "company_type": "Outstaff", "salary": "$600-3500", "technologies": ["PySpark", "Python", "Spark", "Go", "Linux", "Embers", "AI"], "location": ["Україна"]}
{"title": "Infrastructure Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "NoSQL", "Golang", "Python", "Go", "Java", "AWS", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "API", "NoSQL", "FastAPI", "Python", "Go", "DevOps", "Embers", "Django", "AI"], "location": ["Україна", "Грузія", "Польща"]}
{"title": "Python developer", "company": "Uptarget", "company_type": "Product", "salary": null, "technologies": ["Kafka", "CI/CD", "Docker", "Python", "Kubernetes", "Go", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["API", "SQL", "HTML", "PostgreSQL", "Python", "Selenium", "Linux", "Flask", "AWS", "SQLAlchemy", "ML", "Celery", "BeautifulSoup", "AI"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["RESTful", "API", "SQL", "RabbitMQ", "Shopify", "FastAPI", "PostgreSQL", "Python", "Spark", "Kubernetes", "Docker", "Go", "Magento", "AWS", "Django", "Flask", "AI"], "location": ["Україна"]}
{"title": "Middle Game Mathematician (Python)", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["Go", "AI", "Python"], "location": ["Словаччина", "Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["CSS", "React", "JavaScript", "Python", "Angular", "Go", "Flask", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Pandas", "API", "SQL", "Pytest", "MySQL", "CSS", "Git", "Python", "Docker", "Go", "Embers", "AWS", "Flask", "SQLAlchemy", "AI", "Vue.Js"], "location": ["Україна"]}
{"title": "Python developer", "company": "SourceTER", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Azure", "Airflow", "Python", "AWS", "GCP", "Apache", "AI"], "location": ["Вірменія", "Азербайджан", "Грузія", "Казахстан", "Україна"]}
{"title": "Python Developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": "від $2000", "technologies": ["API", "SQL", "HTML", "MySQL", "NoSQL", "PostgreSQL", "CSS", "jQuery", "Python", "Docker", "Redis", "Go", "Linux", "Django", "ML", "OOP"], "location": ["Україна"]}
{"title": "Middle Python Developer з досвідом AI/ML", "company": "GetCode", "company_type": "Outstaff", "salary": "від $2000", "technologies": ["Python", "Spark", "AWS", "ML", "AI"], "location": ["Україна"]}
{"title": "Python developer (Web scraping expert)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["API", "SQL", "Scrapy", "Git", "Airflow", "Python", "Selenium", "AWS", "ML", "BeautifulSoup", "AI"], "location": ["Сполучені Штати"]}
{"title": "Back-end developer (Python/Web scraping)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["API", "SQL", "Scrapy", "Git", "Airflow", "Python", "Selenium", "AWS", "ML", "BeautifulSoup", "AI"], "location": ["Сполучені Штати"]}
{"title": "FullStack developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "$3000-6000", "technologies": ["SQL", "HTML", "CSS", "React", "PostgreSQL", "JavaScript", "Python", "Angular", "jQuery", "Go", "Apache", "Django", "ML", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Bcconsolidator", "company_type": "Product", "salary": "$5800-7000", "technologies": ["SQL", "PostgreSQL", "Apollo", "Python", "Angular", "Selenium", "Go", "Embers", "AWS", "SQLAlchemy", "ML", "GraphQL", "AI"], "location": ["Латвія", "Нідерланди", "Польща"]}
{"title": "Senior Python Engineer", "company": "Star Global", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "MySQL", "FastAPI", "PostgreSQL", "Git", "Python", "Docker", "Go", "Embers", "Flask", "GCP", "SQLAlchemy", "ML", "Celery", "Microservices", "AI"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "DTEK", "company_type": "Product", "salary": null, "technologies": ["SQL", "API", "NoSQL", "MySQL", "PostgreSQL", "React", "JavaScript", "Python", "Redis", "Go", "Embers", "Linux", "Java", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Blockchain Developer for Cryptocurrency Arbitrage Bot", "company": "CallC247", "company_type": "Product", "salary": "від $2000", "technologies": ["API", "Aave", "Compound", "JavaScript", "Python", "Solidity", "Uniswap", "AI"], "location": ["Україна"]}
{"title": "Back-end Python Developer", "company": "Echo", "company_type": "Outstaff", "salary": null, "technologies": ["Infomaniak", "API", "Python", "Cassandra", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Wild Wild Leads", "company_type": "Agency", "salary": "$700-800", "technologies": ["SQL", "RabbitMQ", "HTML", "Pytest", "MySQL", "CSS", "Git", "JavaScript", "Python", "Bootstrap", "Redis", "Go", "Flask", "Django", "ML", "Celery"], "location": ["Україна"]}
{"title": "Senior Python Developer for Guardicore", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Azure", "Git", "Docker", "Python", "Jenkins", "Go", "Linux", "AWS", "GCP", "Flux", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outstaff", "salary": "$6000-8000", "technologies": ["SQL", "React", "PostgreSQL", "Git", "JavaScript", "Jenkins", "Python", "Kubernetes", "Go", "Airflow", "Embers", "Flask", "Apache", "AI"], "location": ["Україна"]}
{"title": "Junior/Midle Developer (Python, JavaScript)", "company": "Checkbox", "company_type": "Product", "salary": "$700-1500", "technologies": ["RESTful", "API", "SQL", "Kafka", "Svelte", "NoSQL", "React", "PostgreSQL", "JavaScript", "Python", "Angular", "Redis", "Go", "Flask", "Django", "MongoDB", "PHP"], "location": ["Україна"]}
{"title": "Python Developer in Test (Apps)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Pytest", "Git", "Jenkins", "Python", "Selenium", "Linux", "AWS", "ML", "AI"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["SQL", "API", "HTML", "CSS", "Git", "Python", "Linux", "ML"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FoxmindEd", "company_type": "Product", "salary": "$3000-5500", "technologies": ["SQL", "HTML", "MySQL", "CSS", "PostgreSQL", "Git", "JavaScript", "Python", "Docker", "Go", "Linux", "ML", "Flask", "Django", "SQLAlchemy", "AWS", "OOP"], "location": ["Україна"]}
{"title": "Team Lead / Senior Python Engineer (Indigo Ag)", "company": "Intelliarts", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "FastAPI", "Git", "Python", "Redis", "Go", "Pydantic", "SQLAlchemy", "Celery", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "PostgreSQL", "Git", "JavaScript", "Jenkins", "Python", "Kubernetes", "Go", "Airflow", "AWS", "GCP", "Apache", "AI"], "location": ["Україна"]}
{"title": "Python developer (IoT/hardware)", "company": "Canyon Development", "company_type": "Outsource", "salary": null, "technologies": ["Embedded", "Git", "Python", "Linux", "Go", "OOP"], "location": ["Україна"]}
{"title": "Strong Middle / Senior Python Developer", "company": "TECHIIA Holding", "company_type": "Product", "salary": null, "technologies": ["API", "SQL", "CI/CD", "PostgreSQL", "Python", "Angular", "Black", "Redis", "Go", "DevOps", "Elasticsearch", "Django", "Celery", "Scrum", "AI"], "location": ["Україна"]}
{"title": "Junior Python Developer Portugal only", "company": "Adaptiq", "company_type": "Product", "salary": "до $2500", "technologies": ["Git", "Python", "Go", "AWS", "GCP", "Dash", "AI"], "location": ["Португалія"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8500", "technologies": ["TensorFlow", "Python", "Go", "PyTorch", "ML"], "location": ["Польща", "Україна"]}
{"title": "Senior Full Stack Engineer (Python, JS)", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "PostgreSQL", "JavaScript", "Python", "Docker", "Go", "Flask", "AWS", "ML", "Celery", "OOP", "AI"], "location": ["Україна"]}
{"title": "Application Architect/Tech Lead Full-stack Engineer (JS/Python)", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["SQL", "API", "NoSQL", "Git", "JavaScript", "Python", "Go", "AWS", "Django", "GCP", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Full-Stack Python Engineer", "company": "MEV", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["API", "SQL", "CI/CD", "React", "Python", "Docker", "Jenkins", "Redis", "Go", "DevOps", "AWS", "Django", "ML", "Celery", "AI"], "location": ["Україна"]}
{"title": "Odoo/Python Developer", "company": "Sentrium", "company_type": "Product", "salary": null, "technologies": ["RESTful", "API", "SQL", "PostgreSQL", "Git", "Python", "Go", "Odoo", "Linux", "Flask", "Django", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Lead Python Developer", "company": "PYGIO", "company_type": "Product", "salary": "$4000-5500", "technologies": ["SQL", "PostgreSQL", "Docker", "Python", "Kubernetes", "Go", "Django", "AI"], "location": ["Україна", "Албанія", "Вірменія", "Польща", "Чехія"]}
{"title": "DevOps Engineer (with Golang or Python)", "company": "Akvelon", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["API", "CI/CD", "Git", "Python", "Docker", "Kubernetes", "Go", "AWS", "Sdn", "ML", "AI"], "location": ["Азербайджан", "Молдова", "Польща", "Туреччина", "Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Go", "Moment", "Embers", "Click", "AI"], "location": ["Україна"]}
{"title": "Python/Django", "company": "Perlyna Devs", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Go", "AI", "Python", "Django"], "location": ["Україна"]}
{"title": "Lead Back-End Engineer", "company": "Madgicx 🇺🇦", "company_type": "Product", "salary": null, "technologies": ["Pandas", "API", "SQL", "CI/CD", "MySQL", "PostgreSQL", "Git", "Python", "Docker", "Jenkins", "Redis", "Go", "Elasticsearch", "AWS", "Django", "Flask", "Celery"], "location": ["Україна"]}
{"title": "Computer Vision Engineer", "company": "tangiblee", "company_type": "Product", "salary": "до $2000", "technologies": ["NumPy", "TensorFlow", "Python", "Go", "Scipy", "PyTorch", "OpenCV", "AI"], "location": ["Україна"]}
{"title": "Back End Developer", "company": "Nashpush", "company_type": "Product", "salary": null, "technologies": ["API", "Saas", "Python", "Docker", "Kubernetes", "Go", "Flask", "Django", "AWS", "OOP", "AI"], "location": ["Кіпр", "Україна"]}
{"title": "Middle\\Senior Backend Engineer ( Python)", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["API", "RabbitMQ", "Kafka", "Node.Js", "asyncio", "Git", "JavaScript", "Python", "Docker", "TypeScript", "Go", "Ansible", "Embers", "AWS", "Django", "Celery", "GraphQL", "AI"], "location": ["Україна"]}
{"title": "Senior / Lead Technical Support Developer", "company": "ApomSolutions", "company_type": "Outstaff", "salary": null, "technologies": ["Azure", "Docker", "Python", "Spark", "Kubernetes", "Oracle", "Java", "AWS", "GCP", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer (with ML/AI  background)", "company": "Cyberspectr Solution", "company_type": "Outstaff", "salary": null, "technologies": ["Pandas", "CI/CD", "TensorFlow", "Git", "Docker", "Python", "AWS", "Scikit-learn", "PyTorch", "NumPy", "AI"], "location": ["Україна"]}
{"title": "Python developer", "company": "NestLogic", "company_type": "Product", "salary": "$2500", "technologies": ["Jupyter Notebook", "Docker", "Python", "Kubernetes", "Go", "Linux", "ML", "AI"], "location": ["Україна"]}
{"title": "Sr Python Engineer", "company": "Zaly", "company_type": "Product", "salary": null, "technologies": ["SQL", "PostgreSQL", "Highload", "Docker", "Python", "Ansible"], "location": ["Україна", "Сполучені Штати"]}
{"title": "Python developer / strong junior", "company": "dZENcode", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["API", "SQL", "NoSQL", "TensorFlow", "Git", "JavaScript", "Python", "Go", "AWS", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "UKR.NET", "company_type": "Product", "salary": "$2000-4000", "technologies": ["API", "SQL", "MongoDB", "NoSQL", "MySQL", "PostgreSQL", "AI", "Python", "Redis", "Go", "Elasticsearch", "aiohttp", "Elasctisearch", "asyncio"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Develux", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["API", "Azure", "SQL", "CI/CD", "NoSQL", "FastAPI", "Django", "PostgreSQL", "Python", "Docker", "Go", "AWS", "Flask", "GraphQL", "AI"], "location": ["Україна"]}
{"title": "Full-stack (JS/Python) / Tech lead", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["SQL", "API", "NoSQL", "Git", "JavaScript", "Python", "Go", "AWS", "Django", "GCP", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Full Stack Developer (Python,React) Miami location", "company": "Global Teams", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "API", "SQL", "CI/CD", "MySQL", "React", "Django", "PostgreSQL", "Git", "Python", "Jenkins", "Go", "Flask", "GCP", "MongoDB", "Redux", "AI"], "location": ["Україна"]}
{"title": "Python Developer for Training Neural Networks", "company": "Digifico", "company_type": "Product", "salary": null, "technologies": ["SQL", "NoSQL", "Keras", "TensorFlow", "Python", "Go", "PyTorch"], "location": ["Україна"]}
{"title": "Python/Django Developer", "company": "ECHOES", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "SQL", "PostgreSQL", "Nginx", "Python", "Docker", "Kubernetes", "Redis", "Go", "Linux", "Elasticsearch", "AWS", "Django", "Celery", "GraphQL", "AI"], "location": ["Грузія", "Україна"]}
{"title": "Python Tech Lead", "company": "Dataforest", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Pandas", "SQL", "Kafka", "NoSQL", "Django", "Airflow", "Python", "Docker", "Kubernetes", "Redis", "Go", "Embers", "Elasticsearch", "AWS", "GCP", "Flask", "AI"], "location": ["Німеччина", "Польща", "Словаччина", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["API", "React", "Pyramid", "Git", "Docker", "Python", "Angular", "Go", "DevOps", "Flask", "Django", "AI", "Vue.Js"], "location": ["Польща"]}
{"title": "Python Developer for Automotive Project", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["API", "React", "Pyramid", "Git", "Docker", "Python", "Angular", "Go", "Ansible", "DevOps", "Flask", "Django", "AI", "Vue.Js"], "location": ["Польща"]}
{"title": "Python Software Engineer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "API", "Kafka", "NoSQL", "FastAPI", "Python", "Spark", "Redis", "Go", "AWS", "Flask", "Postgres", "OOP", "AI"], "location": ["Польща", "Словаччина", "Україна"]}
{"title": "Python Developer  (DCOS)", "company": "OSF Digital", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["RESTful", "API", "SQL", "React", "Git", "Python", "Go", "Agile", "AI"], "location": ["Польща", "Румунія", "Туреччина", "Україна"]}
{"title": "Python developer", "company": "Odore", "company_type": "Product", "salary": "$2000-4000", "technologies": ["API", "SQL", "Postman", "Pytest", "PostgreSQL", "Git", "Python", "Go", "AWS", "SQLAlchemy", "AI"], "location": ["Велика Британія"]}
{"title": "Middle Python Developer", "company": "Starnavi", "company_type": "Outstaff", "salary": null, "technologies": ["RESTful", "API", "SQL", "NoSQL", "FastAPI", "React", "Python", "Docker", "Kubernetes", "Go", "Angular", "Embers", "Linux", "Flask", "Django", "Foundation", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$4500-6000", "technologies": ["API", "CI/CD", "Airflow", "Python", "Go", "DevOps", "Flask", "AWS", "Apache", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python)  (Warsaw)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": null, "technologies": ["API", "Mlops", "React", "TensorFlow", "Node.Js", "Python", "Go", "DevOps", "AWS", "ML", "OOP", "AI"], "location": ["Польща"]}
{"title": "Python developer", "company": "Peppernode", "company_type": "Outsource", "salary": null, "technologies": ["API", "CI/CD", "FastAPI", "Django", "Git", "Python", "Docker", "Kubernetes", "Go", "AWS", "Flask", "Microservices"], "location": ["Україна"]}
{"title": "Python Backend розробник", "company": "Sk-Telemed", "company_type": "Product", "salary": "від $3000", "technologies": ["SQL", "RabbitMQ", "PostgreSQL", "Git", "Python", "Docker", "Virtualenv", "Redis", "Go", "Linux", "Pyenv", "Django", "AWS", "Celery", "AI"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Competera", "company_type": "Product", "salary": "$3000-5000", "technologies": ["SQL", "Kafka", "Luigi", "Airflow", "Python", "Spark", "Go", "Apache", "GCP", "Click", "AI"], "location": ["Кіпр", "Україна"]}
{"title": "Senior Python Developer (Data Engineering Focus)", "company": "HRForecast", "company_type": "Product", "salary": null, "technologies": ["Pandas", "API", "SQL", "Kafka", "RESTful", "FastAPI", "PostgreSQL", "Python", "Go", "Flask", "Django", "NumPy", "AI"], "location": ["Україна"]}
{"title": "Solidity/Blockchain expert (Smart Contract)", "company": "WeSoftYou", "company_type": "Outsource", "salary": null, "technologies": ["React", "Git", "Python", "Solidity", "OOP", "AI"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python) (Poland)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2000", "technologies": ["API", "Mlops", "React", "TensorFlow", "Node.Js", "Python", "DevOps", "AWS", "ML", "OOP", "AI"], "location": ["Ізраїль", "Польща"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["CSS", "React", "JavaScript", "Python", "Angular", "Go", "Flask", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "API", "SQL", "HTML", "NoSQL", "MySQL", "Django", "CSS", "Git", "Senior", "Python", "JavaScript", "Go", "Flask", "AWS", "ML"], "location": ["Україна"]}
{"title": "Experienced Odoo Developer", "company": "hts-experts.com", "company_type": "Product", "salary": null, "technologies": ["SQL", "HTML", "Troubleshooting", "Requests", "CSS", "PostgreSQL", "Git", "JavaScript", "Python", "Go", "Odoo", "Embers", "Linux", "ML", "AI"], "location": ["Швейцарія"]}
{"title": "Middle Python Developer", "company": "P2H", "company_type": "Outstaff", "salary": "до $2000", "technologies": ["RabbitMQ", "Redis", "Redux", "AI", "SQL", "HTML", "React", "PostgreSQL", "Bootstrap", "Go", "Embers", "Elasticsearch", "Vue.Js", "CSS", "Git", "Python", "Angular", "Kubernetes", "ML", "API", "MySQL", "Node.Js", "jQuery", "PHP"], "location": ["Україна"]}
{"title": "Parsing expert for a long term partnership", "company": "WebDev 247", "company_type": "Product", "salary": "до $2500", "technologies": ["API", "HTML", "CSS", "JavaScript", "Python", "ML", "AI"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Django)", "company": "Flexyti", "company_type": "Outsource", "salary": "від $3000", "technologies": ["SQL", "CI/CD", "PostgreSQL", "Docker", "Python", "Kubernetes", "Go", "AWS", "Django", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Middle Python Developer (Django Framework)", "company": "NeoFin", "company_type": "Product", "salary": "$2000", "technologies": ["Finance", "Redis", "OpenCV", "AI", "SQL", "HTML", "React", "PostgreSQL", "Go", "Elasticsearch", "Django", "Vue.Js", "RESTful", "CSS", "Git", "Python", "Flask", "ML", "API", "MySQL", "Node.Js", "JavaScript"], "location": ["Малайзія", "Польща", "Україна"]}
{"title": "strong Python over Django dev", "company": "Flexyti", "company_type": "Outsource", "salary": "до $3000", "technologies": ["SQL", "CI/CD", "PostgreSQL", "Python", "Docker", "Kubernetes", "Go", "AWS", "Django", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python developer (AWS)", "company": "TemaBit Fozzy Group", "company_type": "Product", "salary": null, "technologies": ["SQL", "API", "CI/CD", "NoSQL", "Git", "Python", "AWS", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "CI/CD", "Tornado", "Docker", "Python", "Kubernetes", "Redis", "Go", "AWS", "aiohttp", "AI"], "location": ["Словаччина", "Україна"]}
{"title": "Backend Python/Django Developer for a SaaS Product", "company": "Iteksas", "company_type": "Product", "salary": null, "technologies": ["SQL", "HTML", "Saas", "NoSQL", "CSS", "Product", "Python", "Go", "Django", "ML", "Celery"], "location": ["Литва", "Україна"]}
{"title": "Python developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["API", "SQL", "HTML", "NoSQL", "CSS", "PostgreSQL", "jQuery", "Docker", "Python", "Redis", "Go", "Linux", "Django", "ML", "OOP"], "location": ["Україна"]}
{"title": "Strong Junior Backend Python Developer", "company": "DevIT Group", "company_type": "Outsource", "salary": "$900-1500", "technologies": ["API", "Azure", "SQL", "RabbitMQ", "FastAPI", "Git", "Docker", "Python", "Langchain", "Redis", "Go", "Linux", "AWS", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": null, "technologies": ["API", "CI/CD", "Airflow", "Python", "Go", "DevOps", "Flask", "AWS", "Apache", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "AI Enthusiast / Machine Learning", "company": "King's Choice", "company_type": "Product", "salary": null, "technologies": ["ChatGPT", "AI", "Python"], "location": ["Україна"]}
{"title": "Middle Python+Java Developer IRC183577", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["RESTful", "SQL", "API", "NoSQL", "Git", "Python", "Go", "AWS", "Java", "AI"], "location": ["Україна"]}
{"title": "Python Developer", "company": "4K-Soft", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "Mondodb", "MySQL", "Git", "Docker", "Python", "Go", "MongoDB", "OOP", "AI"], "location": ["Україна"]}
{"title": "LLM developer", "company": "SerenityGPT", "company_type": "Product", "salary": "$1200-2500", "technologies": ["Go", "ChatGPT", "Nlp", "AI"], "location": ["Велика Британія"]}
{"title": "Senior Python Engineer", "company": "KnubiSoft", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["API", "CSS", "Python", "Go", "Embers", "AWS", "Django", "GraphQL", "OOP", "AI"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Go", "Moment", "Embers", "Click", "AI"], "location": ["Україна"]}
{"title": "QA Engineer (Performance testing)", "company": "SeekIT", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "API", "CI/CD", "JavaScript", "Python", "Jenkins", "Elasticsearch", "Java", "ML", "AI"], "location": ["Латвія"]}
{"title": "Python Developer", "company": "AUTODOC", "company_type": "Product", "salary": null, "technologies": ["API", "Streamlit", "Python", "Go", "DevOps", "ML", "AI"], "location": ["Молдова", "Польща", "Португалія", "Україна"]}
{"title": "Middle/Senior Python Software Developer (or switcher from another OOP language)", "company": "Jito.dev", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "CI/CD", "PostgreSQL", "Git", "Gis", "Python", "Kubernetes", "Go", "Linux", "DevOps", "AWS", "OOP", "AI"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer", "company": "teeko.", "company_type": "Product", "salary": "до $2000", "technologies": ["API", "SQL", "FastAPI", "PostgreSQL", "Python", "Go", "GraphQL"], "location": ["Україна", "Ізраїль"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["DevOps", "AI", "Python"], "location": ["Україна"]}
{"title": "Quality Assurance Architect (Networking)", "company": "PLVision", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["API", "Automation", "Pytest", "CI/CD", "Unittest", "Robot Framework", "Python", "Docker", "Architect", "Linux", "Networking", "Kubernetes", "Go", "Ansible", "Embers", "AI"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$5000-7000", "technologies": ["RESTful", "API", "HTML", "CSS", "Git", "JavaScript", "Docker", "Python", "Kubernetes", "Go", "AWS", "Foundation", "ML", "AI"], "location": ["Україна"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": null, "technologies": ["API", "React", "Git", "Docker", "Python", "Kubernetes", "Go", "DevOps", "Embers", "GraphQL", "OOP", "AI"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": "$2000-4000", "technologies": ["DevOps", "AI", "Python", "Crossplatform"], "location": ["Україна"]}
{"title": "Python/GoLang developer (Europe)", "company": "TEAM International", "company_type": "Outstaff", "salary": null, "technologies": ["API", "SQL", "NoSQL", "Django", "Python", "Kubernetes", "Go", "Foundation", "GCP", "AI"], "location": ["Польща", "Португалія"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "SQL", "Matplotlib", "Python", "Go", "Plotly", "Embers", "Dash", "NumPy", "AI"], "location": ["Польща"]}
{"title": "Senior Python Developer", "company": "Animo", "company_type": "Product", "salary": "від $5000", "technologies": ["API", "Node.Js", "Python", "Go", "AWS", "Django", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $9000", "technologies": ["API", "Azure", "CI/CD", "Python", "Docker", "Kubernetes", "Go", "Ansible", "AWS", "GCP", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "APOSTERA UA HARMAN", "company_type": "Product", "salary": null, "technologies": ["API", "Automation", "Middle", "Git", "Senior", "Python", "Docker", "Linux", "DevOps", "ML", "Automotive", "AI"], "location": ["Угорщина", "Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Bluefield Technologies", "company_type": "Product", "salary": "$5000-6000", "technologies": ["asyncio", "AI", "Pandas", "SQL", "HTML", "React", "TypeScript", "Docker", "Go", "RESTful", "CSS", "Git", "Python", "Linux", "aiohttp", "ML", "API", "Backbone", "Networking", "Ccna"], "location": ["Словаччина", "Україна"]}
{"title": "Team Lead Python", "company": "Capital Recruiters", "company_type": "Product", "salary": "$2000-4000", "technologies": ["API", "SQL", "React", "Python", "Flask", "Django"], "location": ["Україна"]}
{"title": "Software Python Developer", "company": "Capital Recruiters", "company_type": "Product", "salary": "$3000-4500", "technologies": ["API", "SQL", "React", "Python", "Flask", "Django"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Ava Technologies Inc.", "company_type": "Product", "salary": null, "technologies": ["Python", "Go", "ChatGPT", "Embers", "AWS", "Serverless", "MongoDB", "AI"], "location": ["Чехія", "Нідерланди"]}
{"title": "Python/Django Full Stack Developer", "company": "BikeBUBL", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Vue", "SQL", "Frontend", "PostgreSQL", "Js", "Python", "Go", "Django", "AI", "Vue.Js"], "location": ["Велика Британія", "Україна"]}
{"title": "Senior Algorithms Developer (Speech Recognition, Python)", "company": "SD Solutions", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["API", "TensorFlow", "Python", "Go", "Embers", "PyTorch", "ML", "AI"], "location": ["Кіпр", "Грузія", "Польща", "Україна"]}
{"title": "Corsound AI - Senior Algorithms Developer", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["API", "TensorFlow", "Python", "Go", "Embers", "PyTorch", "AI", "Algorithms"], "location": ["Україна", "Грузія"]}
{"title": "Senior Data Scientist for the oil and gas data prediction solutions", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "Azure", "SQL", "TensorFlow", "Python", "Go", "Scikit-learn", "NumPy", "AI"], "location": ["Україна"]}
{"title": "Senior Data Scientist for the oil and gas industry", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "Azure", "SQL", "TensorFlow", "Python", "Go", "Scikit-learn", "NumPy"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "InventorSoft", "company_type": "Outstaff", "salary": "$3500-5000", "technologies": ["API", "SQL", "MySQL", "FastAPI", "Python", "DevOps"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "Mobilunity", "company_type": "Outsource", "salary": null, "technologies": ["Azure", "API", "Fairplay", "Requests", "Python", "Playready", "Go", "AWS", "Dash", "AI"], "location": ["Україна"]}
{"title": "Algorithm Developer for Corsound AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["API", "TensorFlow", "Python", "Go", "Embers", "PyTorch", "AI", "Algorithms"], "location": ["Грузія", "Польща", "Україна"]}
{"title": "Senior/Lead Python Engineer with Data skills", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "Python", "Spark", "Go", "AWS", "OOP", "AI"], "location": ["Україна"]}
{"title": "Python developer (US IoT project)", "company": "Romen Personnel", "company_type": "Product", "salary": "$1000-2500", "technologies": ["SQL", "Iot", "Python", "PHP", "AWS", "OOP", "AI"], "location": ["Сполучені Штати"]}
{"title": "Senior Cloud Developer", "company": "Alcor", "company_type": "Product", "salary": "$2000-4000", "technologies": ["API", "SQL", "NoSQL", "JavaScript", "Python", "AWS", "Cloud", "AI", "Vue.Js"], "location": ["Чехія", "Польща", "Румунія", "Словаччина", "Україна"]}
{"title": "Python Developer for EdTech company", "company": "Projector", "company_type": "Product", "salary": null, "technologies": ["AI", "Python"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with ML experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Node.Js", "Ocr", "Python", "Angular", "Go", "AWS", "ML", "AI"], "location": ["Естонія", "Польща", "Україна"]}
{"title": "Senior Python  Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "Go", "ML", "OOP", "AI"], "location": ["Португалія"]}
{"title": "Middle/Senior BackEnd developer Python/Django", "company": "Meest China", "company_type": "Product", "salary": null, "technologies": ["RESTful", "API", "SQL", "JWT", "MySQL", "Wagtail", "Git", "Nginx", "Python", "Jenkins", "Redis", "Go", "AWS", "Django", "Celery", "AI"], "location": ["Україна"]}
{"title": "Strong Junior / Middle Python Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "до $2500", "technologies": ["RabbitMQ", "Redis", "AI", "Pandas", "SQL", "HTML", "React", "PostgreSQL", "Celery", "Docker", "Go", "Django", "CSS", "Git", "Python", "Angular", "Linux", "ML", "OOP", "API", "MySQL", "Webpack", "Orm"], "location": ["Україна"]}
{"title": "Python Back-End Engineer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "від $5000", "technologies": ["Azure", "CI/CD", "Python", "Kubernetes", "Redis", "AWS", "GCP", "ML", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Azure", "Git", "Docker", "Python", "Jenkins", "Go", "Linux", "AWS", "GCP", "Flux", "MongoDB", "AI"], "location": ["Україна"]}
{"title": "Senior Appian Developer", "company": "DICEUS", "company_type": "Outstaff", "salary": null, "technologies": ["SQL", "API", "Sail", "Git", "JavaScript", "Go", "Appian", "Embers", "AI"], "location": ["Йорданія", "Польща", "Україна"]}
{"title": "Python\\Django Backend Developer", "company": "Animo", "company_type": "Outsource", "salary": "до $5500", "technologies": ["SQL", "API", "Node.Js", "Remote", "Python", "Go", "AWS", "Django", "Backend", "AI"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "level99.vip", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "Requests", "AI", "SQL", "HTML", "NoSQL", "Docker", "Postman", "Git", "Nginx", "Python", "Kubernetes", "Selenium", "Apache", "SQLAlchemy", "ML", "API", "Kafka", "GraphQL"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer (Prom.ua)", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["RabbitMQ", "CI/CD", "Redis", "SQL", "React", "PostgreSQL", "Docker", "Go", "Elasticsearch", "CSS", "Git", "Python", "Kubernetes", "Click", "MongoDB", "API", "Kafka", "JavaScript", "Webpack"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Intsurfing", "company_type": "Outstaff", "salary": "$2500-4000", "technologies": ["SQL", "Azure", "API", "Python", "Linux", "AWS", "ML", "AI"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Unidatalab", "company_type": "Product", "salary": null, "technologies": ["Azure", "API", "SQL", "Kafka", "NoSQL", "FastAPI", "Django", "Git", "Python", "Docker", "Kubernetes", "Go", "ChatGPT", "AWS", "GCP", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "CI/CD", "MySQL", "PostgreSQL", "Git", "Airflow", "Python", "Spark", "Redis", "Go", "Moment", "AWS", "Apache", "MongoDB", "AI"], "location": ["Румунія"]}
{"title": "Python Developer/Data Engineer", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Pandas", "TensorFlow", "Git", "Python", "OpenCV", "AWS", "PyTorch", "ML", "NumPy", "AI"], "location": ["Україна"]}
{"title": "Middle Backend Developer", "company": "Partner-way", "company_type": "Product", "salary": null, "technologies": ["API", "Requests", "JavaScript", "Python", "TypeScript", "Go"], "location": ["Велика Британія", "Сполучені Штати", "Україна", "Німеччина", "Польща"]}
{"title": "Odoo Engineer", "company": "OpsWay", "company_type": "Outsource", "salary": null, "technologies": ["PostgreSQL", "Xml", "Owl", "JavaScript", "Python", "Odoo"], "location": ["Україна"]}
{"title": "Senior Python/DevOps Developer", "company": "Chrysalis Gate", "company_type": "Outstaff", "salary": "$5000-7000", "technologies": ["API", "Kafka", "React", "Git", "Python", "Spark", "Redis", "Moment", "DevOps", "AWS", "AI"], "location": ["Литва", "Україна", "Польща", "Словаччина", "Румунія"]}
{"title": "Python Developer", "company": "SKILLUP", "company_type": "Product", "salary": null, "technologies": ["SQL", "HTML", "CSS", "Python", "Go", "Django", "ML", "AI"], "location": ["Україна"]}
{"title": "Програміст на Django 1.9.0", "company": "GlutenOff.ua", "company_type": "Product", "salary": null, "technologies": ["SQL", "HTML", "PostgreSQL", "JavaScript", "Docker", "Python", "Nginx", "Go", "Gulp", "Django", "ML"], "location": ["Україна"]}
{"title": "Senior Software Engineer (DataDiscovery)", "company": "MEGOGO", "company_type": "Product", "salary": "$2000-4000", "technologies": ["API", "SQL", "Kafka", "MySQL", "PostgreSQL", "Python", "Docker", "Kubernetes", "Go", "Spark", "AWS", "Apache", "Click", "MongoDB", "OOP"], "location": ["Україна"]}
{"title": "Tech/Team Lead (Python)", "company": "Indigo Tech recruitment", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Pandas", "API", "SQL", "FastAPI", "PostgreSQL", "Python", "Go", "AWS", "PyTorch", "ML", "AI"], "location": ["Франція"]}
{"title": "Middle+/Senior Python developer", "company": "TechbrainJobs", "company_type": "Product", "salary": "$3000-5000", "technologies": ["SQL", "Drf", "PostgreSQL", "Django", "AI", "Git", "Nginx", "Python", "Angular", "Redis", "Go", "Elasticsearch", "aiohttp", "Celery", "Mongo"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with OCR experience", "company": "8allocate", "company_type": "Outsource", "salary": "від $5000", "technologies": ["Node.Js", "Ocr", "Python", "Angular", "Go", "AWS", "ML", "AI"], "location": ["Україна"]}
{"title": "Senior Python (Back-end) Developer", "company": "Animo", "company_type": "Outsource", "salary": "від $5000", "technologies": ["English", "API", "Node.Js", "Python", "Go", "AWS", "Django", "Apis", "AI"], "location": ["Україна"]}
{"title": "Senior Backend Engineer for Neolithics AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["Azure", "CI/CD", "Python", "Kubernetes", "Redis", "Go", "AWS", "GCP", "ML", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": null, "technologies": ["API", "Python", "DevOps", "PyTorch", "ML"], "location": ["Україна"]}
{"title": "Python Developer (Data-driven)", "company": "TechbrainJobs", "company_type": "Product", "salary": "$6000-8000", "technologies": ["API", "SQL", "CI/CD", "Git", "Docker", "Python", "Go", "Linux", "AWS", "AI"], "location": ["Ізраїль"]}
{"title": "Python/Golang Developer (Hospitality industry)", "company": "Coherent Solutions", "company_type": "Outsource", "salary": "$1500-3000", "technologies": ["SQL", "API", "NoSQL", "Golang", "Python", "Kubernetes", "Go", "Foundation", "Django", "AI"], "location": ["Польща", "Грузія", "Литва", "Болгарія", "Румунія"]}
{"title": "Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Pandas", "SQL", "RabbitMQ", "React", "PostgreSQL", "Node.Js", "Airflow", "Docker", "Python", "Redis", "Go", "Embers", "Django", "Celery", "OOP", "AI"], "location": ["Польща", "Україна"]}
{"title": "Junior Python Developer (Scraping) for AI Software Product", "company": "Simporter", "company_type": "Product", "salary": null, "technologies": ["RESTful", "API", "SQL", "RabbitMQ", "Scrapy", "NoSQL", "Airflow", "Python", "Go", "Elasticsearch", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Quickstaffing LLC", "company_type": "Outstaff", "salary": null, "technologies": ["Pandas", "SQL", "Jupyter Notebook", "Python", "Spark", "Go", "AI"], "location": ["Вірменія"]}
{"title": "Mid-Senior Python developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["API", "AI", "Python", "Go"], "location": ["Польща"]}
{"title": "Middle Python Developer", "company": "SoftVision", "company_type": "Outsource", "salary": "$1500-2800", "technologies": ["API", "SQL", "MySQL", "Django", "PostgreSQL", "Git", "Python", "Docker", "Kubernetes", "Go", "Spark", "AWS", "Flask", "Apache", "AI"], "location": ["Україна"]}
{"title": "Middle/Senior Python/Go Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["API", "Git", "JavaScript", "Python", "Go", "ML", "AI"], "location": ["Польща", "Сербія", "Португалія"]}
{"title": "Middle Developer (Python/Django) in product", "company": "Graintrack", "company_type": "Product", "salary": null, "technologies": ["RESTful", "API", "SQL", "Saas", "CI/CD", "PostgreSQL", "Python", "Docker", "Redis", "Go", "Django", "AI"], "location": ["Україна"]}
{"title": "Full Stack Software Engineer", "company": "Seatpick", "company_type": "Product", "salary": "$3000-5000", "technologies": ["API", "JavaScript", "Docker", "TypeScript", "Go", "AWS", "Django", "ML", "AI"], "location": ["Україна"]}
{"title": "Python developer", "company": "Flyaps", "company_type": "Outsource", "salary": null, "technologies": ["SQL", "CI/CD", "CSS", "Git", "JavaScript", "Python", "Go", "Linux", "Django", "AI"], "location": ["Україна"]}
{"title": "Senior Full-Stack Developer/ AI Evangelist", "company": "Softengi", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["Azure", "CI/CD", "React", "Git", "JavaScript", "Python", "Angular", "ChatGPT", "DevOps", "AWS", "ML", "AI", "Copilot"], "location": ["Чехія", "Литва", "Латвія", "Польща", "Україна"]}
{"title": "Senior Back-end Python Engineer", "company": "Particles Global", "company_type": "Product", "salary": null, "technologies": ["API", "SQL", "PostgreSQL", "AI", "Python", "Docker", "Kubernetes", "Linux", "Go", "Moment", "OOP", "Unix"], "location": ["Україна"]}
{"title": "Senior Full-Stack Engineer Python/React - UKRAINE or SPAIN", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["Pandas", "Azure", "SQL", "React", "PySpark", "Python", "Docker", "Spark", "Go", "TypeScript", "DevOps", "Embers", "D3", "Flask", "SQLAlchemy", "Celery", "Dask", "AI"], "location": ["Україна", "Іспанія"]}
{"title": "Python backend Developer", "company": "Yanpix", "company_type": "Product", "salary": null, "technologies": ["SQL", "MySQL", "PostgreSQL", "Git", "Python", "Go", "DevOps", "Flask", "Django", "MongoDB"], "location": ["Україна", "Словаччина", "Польща", "Чехія"]}
{"title": "Senior Python Full-stack Software Engineer", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["CI/CD", "JavaScript", "Jenkins", "Python", "TypeScript", "Go", "AWS", "AI"], "location": ["Україна"]}
{"title": "Data Engineer", "company": "Websmile", "company_type": "Outstaff", "salary": "від $2000", "technologies": ["Django", "Git", "Airflow", "Jenkins", "Docker", "Go", "Linux", "AWS", "Flask", "ML", "AI"], "location": ["Ізраїль", "Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$3000-6000", "technologies": ["API", "Python", "DevOps", "PyTorch", "ML", "OOP"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Super Dispatch", "company_type": "Product", "salary": "$5000-6500", "technologies": ["API", "CI/CD", "Ddd", "Python", "Kubernetes", "Go", "AWS", "Django", "GCP", "AI"], "location": ["Узбекистан"]}
{"title": "Python Full Stack Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["SQL", "HTML", "MySQL", "React", "Node.Js", "CSS", "Git", "TypeScript", "Python", "Angular", "Go", "Linux", "DevOps", "Foundation", "Click", "ML", "PHP", "AI"], "location": ["Україна"]}
