{"title": "Senior Python Backend Engineer", "company": "Reef Technlogies", "company_type": "Product", "salary": "$7560-11760", "technologies": ["Python", "Django", "AI", "Embers", "Go"], "location": ["Польща"]}
{"title": "Senior Full-Stack Engineer Python/React", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Celery", "Azure", "Docker", "PySpark", "Pandas", "AI", "Dask", "Flask", "DevOps", "React", "Go", "SQL", "SQLAlchemy", "D3", "Spark", "TypeScript"], "location": ["Україна"]}
{"title": "Senior Backend Engineer", "company": "Launch Labs", "company_type": "Outsource", "salary": "до $3000", "technologies": ["Python", "API", "Celery", "ML", "AI", "GraphQL", "Flask", "AWS", "React", "Go", "MongoDB", "FastAPI", "TypeScript"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "AI"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Django", "AI", "Go", "JavaScript"], "location": ["Україна"]}
{"title": "Backend Engineer with AI Integration Experience", "company": "Visarsoft", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["Python", "TensorFlow", "Azure", "AI", "AWS", "Agile", "Tdd", "React", "Nlp", "Angular", "JavaScript", "TypeScript"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outstaff", "salary": "$2000-4000", "technologies": ["Python", "Django", "AI", "Go", "JavaScript", "English", "Mentoring"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Intetics", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Python", "API", "ML", "Airflow", "Git", "AI", "AWS", "Go", "GCP", "SQL", "Etl"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["Python", "API", "AI"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Docker", "Git", "OOP", "Linux", "AI"], "location": ["Україна"]}
{"title": "Senior Python Backend Developer", "company": "TechHunt", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Python", "Django", "Elasticsearch", "Go", "RabbitMQ", "CI/CD"], "location": ["Німеччина", "Нідерланди", "Польща", "Україна", "Португалія"]}
{"title": "SEnior Python WMS", "company": "Mrt", "company_type": "Product", "salary": "до $8500", "technologies": ["Python", "API", "OOP", "AI", "Linux", "Go", "Wms"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Data Scientist / Senior Python developer", "company": "Simplify", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["Python", "ML", "Git", "AI", "PyTorch", "Tensorrt", "Go", "Sota", "OpenCV"], "location": ["Україна", "Німеччина", "Польща"]}
{"title": "Quantitative Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Python", "Git", "OOP", "AI", "Linux", "Go"], "location": ["Україна"]}
{"title": "Data and Machine Learning Engineer (Python)", "company": "Softwarium", "company_type": "Outsource", "salary": null, "technologies": ["TensorFlow", "AI", "NoSQL", "AWS", "Embers", "NumPy", "Spark", "Scikit-learn", "Docker", "Dask", "PyTorch", "Angular", "ML", "Azure", "Git", "React", "Python", "API", "Pandas", "OOP", "Go", "SQL"], "location": ["Польща", "Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Python", "API", "PHP", "Django", "Docker", "Git", "OOP", "AI", "Flask", "AWS", "Elasticsearch", "React", "Apache", "Go", "SQL", "MongoDB", "FastAPI", "MySQL"], "location": ["Україна"]}
{"title": "Senior/Lead Python Developer", "company": "CHI Software", "company_type": "Outsource", "salary": null, "technologies": ["PHP", "Django", "AI", "NoSQL", "AWS", "Elasticsearch", "GCP", "FastAPI", "Docker", "Linux", "Flask", "DevOps", "CI/CD", "Azure", "JavaScript", "Python", "API", "Go", "SQL", "aiohttp"], "location": ["Польща", "Україна"]}
{"title": "Python Engineer Team Lead", "company": "JOIDY", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Python", "Emr", "OOP", "AI", "AWS", "Hadoop", "SQL", "Spark"], "location": ["Україна"]}
{"title": "Senior Full Stack Engineer with Python and Golang", "company": "TeamDev", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "Azure", "Docker", "Git", "AI", "AWS", "PostgreSQL", "React", "Go", "GCP", "JavaScript", "SQL", "MongoDB", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Software Engineer", "company": "TEAM International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Django", "Git", "AI", "NoSQL", "Go", "GCP", "SQL"], "location": ["Польща", "Португалія"]}
{"title": "Python Back-end Developer /Candidates from Ukraine     JobTestPrep", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Python", "API", "Docker", "Git", "AI", "NoSQL", "AWS", "Angular", "PostgreSQL", "React", "Go", "RESTful", "SQL", "MongoDB", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["AI", "Embers", "Pytest", "Docker", "Linux", "Flask", "Tornado", "SQLAlchemy", "Kubernetes", "MySQL", "Git", "Falcon", "Python", "API", "OOP", "PostgreSQL", "Go", "SQL", "aiohttp"], "location": ["Україна"]}
{"title": "Senior Python Developer-a на ізраїльський фінтех проєкт", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Git", "AI", "Data", "SQL", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Senior Python developer (with DevOps experience)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Django", "AI", "NoSQL", "DevOps", "Embers", "Go", "SQL", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Engineer (Application Platform Track)", "company": "PandaDoc", "company_type": "Product", "salary": "$5800-7000", "technologies": ["Python", "Django", "Docker", "Git", "AI", "Pandas", "AWS", "PostgreSQL", "asyncio", "Go", "Kafka", "SQL", "RabbitMQ", "Kubernetes", "FastAPI", "Rabbimq"], "location": ["Польща", "Португалія", "Україна"]}
{"title": "Senior Fullstack Engineer (python+react)", "company": "Svitla Systems", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Python", "API", "ML", "HTML", "Django", "Git", "AI", "MySQL", "React", "PostgreSQL", "RESTful", "Go", "JavaScript", "SQL", "CSS", "TypeScript"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "FXC Intelligence", "company_type": "Product", "salary": "$5000-7000", "technologies": ["Python", "API", "Docker", "AI", "SQL"], "location": ["Велика Британія"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Django", "AI", "NoSQL", "DevOps", "Embers", "Restapi", "Go", "SQL", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python", "company": "Ciklum International", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["Python", "Airflow", "Git", "AI", "Flask", "Embers", "Jenkins", "PostgreSQL", "React", "Apache", "Go", "JavaScript", "SQL", "Kubernetes"], "location": ["Польща"]}
{"title": "Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Python", "PHP", "Git", "Django", "OOP", "AI", "React", "Go"], "location": ["Україна"]}
{"title": "ML/Python Senior", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "ML", "Azure", "AI", "SQL", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Pyramid", "ML", "HTML", "Django", "Git", "OOP", "AI", "Flask", "AWS", "Embers", "Go", "JavaScript", "Node.Js", "Kubernetes", "CI/CD"], "location": ["Польща"]}
{"title": "Python Team Lead", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["Python", "OOP", "Linux", "AI", "Go"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["AI", "Embers", "Pytest", "Docker", "Linux", "Flask", "Tornado", "SQLAlchemy", "Kubernetes", "MySQL", "Git", "Falcon", "Python", "API", "OOP", "PostgreSQL", "Go", "SQL", "aiohttp"], "location": ["Україна"]}
{"title": "Python developer", "company": "Ciba Health", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "Pyramid", "ML", "HTML", "Django", "Git", "AI", "GraphQL", "AWS", "Flask", "DevOps", "RESTful", "Go", "Redis", "SQL", "CSS", "Kubernetes"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Git", "OOP", "Linux", "AI", "Solid", "Databases", "Multithreading"], "location": ["Україна"]}
{"title": "Senior Full Stack Developer (Python)", "company": "SalesNash", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "ML", "HTML", "Git", "AI", "Flask", "PostgreSQL", "React", "Js", "Go", "SQL", "Webpack", "CSS", "FastAPI"], "location": ["Канада"]}
{"title": "Senior/Lead Python Engineer with Data Skills (AdTech Location Technology Leader)", "company": "Sigma Software", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "Emr", "OOP", "AI", "AWS", "Hadoop", "Go", "SQL", "Spark"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Numerical Technologies", "company_type": "Product", "salary": "$2500-4000", "technologies": ["Python", "API", "Azure", "Git", "AI", "AWS", "Go", "RESTful", "FastAPI"], "location": ["Сполучені Штати", "Україна", "Португалія", "Польща", "Сінгапур"]}
{"title": "Back End Engineer ( Python\\Java\\Go) with Data Engineering experience", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $7500", "technologies": ["API", "ML", "AI", "Flink", "Kafka", "Spark", "CI/CD"], "location": ["Польща", "Україна"]}
{"title": "Sr. Python Developer", "company": "TrustPoint", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Python", "API", "ML", "Git", "Django", "AI", "DevOps", "Go", "RESTful", "CI/CD"], "location": ["Сполучені Штати"]}
{"title": "Senior Python Developer", "company": "Radency", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "NoSQL", "Elasticsearch", "GCP", "RabbitMQ", "Spark", "Airflow", "Docker", "GraphQL", "Postgres", "Flask", "Git", "Apache", "Python", "API", "Flux", "Pandas", "PostgreSQL", "Redis", "SQL"], "location": ["Україна"]}
{"title": "Python Back-end Developer (JobTestPrep)", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Docker", "Git", "AI", "NoSQL", "AWS", "Angular", "React", "Go", "RESTful", "SQL", "Kubernetes", "CI/CD"], "location": ["Україна", "Грузія", "Кіпр"]}
{"title": "Python Lead  Developer", "company": "Genius Software", "company_type": "Product", "salary": null, "technologies": ["Python", "AI", "Git"], "location": ["Сполучені Штати"]}
{"title": "Python Team Lead", "company": "SoftConstruct", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "Airflow", "OOP", "AI", "DevOps", "FastAPI", "Ansible", "aiohttp", "Apache", "Go", "Beam", "Kafka", "RESTful", "SQL", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Full Stack Developer", "company": "UKR.NET", "company_type": "Product", "salary": null, "technologies": ["AI", "NoSQL", "Elasticsearch", "asyncio", "SQL", "MySQL", "Redux", "React", "JavaScript", "TypeScript", "Python", "API", "PostgreSQL", "Go", "Redis", "Sqlite", "MobX", "MongoDB", "aiohttp"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Bcconsolidator", "company_type": "Product", "salary": "$5800-7000", "technologies": ["Python", "Selenium", "ML", "AI", "GraphQL", "AWS", "Angular", "Embers", "PostgreSQL", "Go", "Apollo", "SQL", "SQLAlchemy"], "location": ["Латвія", "Нідерланди", "Польща"]}
{"title": "Team Lead / Senior Python Engineer (Indigo Ag)", "company": "Intelliarts", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Python", "API", "Celery", "Git", "AI", "Pydantic", "Go", "Redis", "SQL", "SQLAlchemy", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$5000", "technologies": ["Python", "API", "Airflow", "OOP", "AI", "Flask", "AWS", "DevOps", "Apache", "Go", "Cognito", "MongoDB", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Star Global", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Microservices", "Celery", "ML", "Docker", "Git", "AI", "Flask", "Embers", "PostgreSQL", "Go", "GCP", "SQL", "SQLAlchemy", "FastAPI", "MySQL"], "location": ["Україна"]}
{"title": "Middle/Senior Full-stack Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["API", "Azure", "Django", "Docker", "Git", "AI", "AWS", "Jenkins", "React", "Go", "GCP", "RESTful", "Kubernetes", "CI/CD"], "location": ["Велика Британія", "Польща", "Україна"]}
{"title": "Senior Python Engineer with JS/Typescript", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Celery", "Azure", "Docker", "PySpark", "Pandas", "AI", "Dask", "Flask", "DevOps", "Embers", "React", "Go", "SQL", "SQLAlchemy", "D3", "Spark", "TypeScript"], "location": ["Україна"]}
{"title": "Experienced Python Developer - lifetime opportunity", "company": "CleverCrew", "company_type": "Product", "salary": null, "technologies": ["API", "Svelte", "Git", "Django", "AI", "Postgres", "Jenkins", "Go", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Django", "AI", "NoSQL", "DevOps", "Embers", "Go", "SQL", "FastAPI"], "location": ["Україна", "Грузія", "Польща"]}
{"title": "Middle/Senior Python Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Python", "API", "Swagger", "Docker", "Git", "AI", "Jenkins", "RESTful", "Postman", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Developer (with DevOps)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Chef", "ML", "Azure", "Django", "Docker", "AI", "NoSQL", "DevOps", "AWS", "Ansible", "Embers", "Go", "Puppet", "SQL", "FastAPI", "CI/CD"], "location": ["Україна", "Польща", "Грузія"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": "від $5000", "technologies": ["Python", "API", "Django", "Docker", "AI", "FastAPI", "AWS", "Flask", "Magento", "PostgreSQL", "Go", "Shopify", "RESTful", "SQL", "RabbitMQ", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Technical Lead Python", "company": "Meest Group", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Python", "Docker", "Django", "Git", "AWS", "PostgreSQL", "React", "Go", "SQL", "CI/CD"], "location": ["Україна"]}
{"title": "Infrastructure Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Golang", "Java", "OOP", "NoSQL", "AWS", "AI", "Go", "SQL"], "location": ["Україна"]}
{"title": "Software Engineering Team Lead", "company": "AllSTARSIT", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "Go"], "location": ["Україна"]}
{"title": "Sr Python Engineer", "company": "Zaly", "company_type": "Product", "salary": "$2500-4000", "technologies": ["Python", "Highload", "Docker", "Ansible", "PostgreSQL", "SQL"], "location": ["Україна", "Сполучені Штати"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8500", "technologies": ["Python", "TensorFlow", "ML", "PyTorch", "Go"], "location": ["Польща", "Україна"]}
{"title": "Lead Python Developer", "company": "PYGIO", "company_type": "Product", "salary": "$5000-6000", "technologies": ["Python", "Docker", "Django", "AI", "PostgreSQL", "Go", "SQL", "Kubernetes"], "location": ["Україна", "Албанія", "Вірменія", "Польща", "Чехія"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "Airflow", "Git", "AI", "Flask", "Embers", "Jenkins", "PostgreSQL", "React", "Apache", "Go", "JavaScript", "SQL", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "UKR.NET", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Python", "API", "AI", "NoSQL", "Elasticsearch", "MySQL", "PostgreSQL", "asyncio", "Go", "Redis", "SQL", "MongoDB", "aiohttp", "Elasctisearch"], "location": ["Україна"]}
{"title": "Senior Python Developer for Guardicore", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Azure", "Docker", "Git", "Flux", "AI", "Linux", "AWS", "Jenkins", "Go", "GCP", "MongoDB"], "location": ["Україна"]}
{"title": "Lead Back-End Engineer", "company": "Madgicx 🇺🇦", "company_type": "Product", "salary": null, "technologies": ["Python", "Celery", "API", "CI/CD", "Django", "Docker", "Pandas", "Git", "AWS", "Flask", "Jenkins", "Elasticsearch", "PostgreSQL", "Go", "Redis", "SQL", "MySQL"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Airflow", "Git", "AI", "AWS", "Jenkins", "PostgreSQL", "Apache", "Go", "GCP", "JavaScript", "SQL", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Moment", "AI", "Embers", "Click", "Go"], "location": ["Україна"]}
{"title": "Senior Full Stack Engineer (Python, JS)", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Celery", "ML", "Docker", "OOP", "AI", "AWS", "Flask", "PostgreSQL", "Go", "JavaScript", "SQL"], "location": ["Україна"]}
{"title": "Application Architect/Tech Lead Full-stack Engineer (JS/Python)", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Python", "API", "Django", "Git", "AI", "NoSQL", "AWS", "Go", "GCP", "JavaScript", "SQL", "MongoDB"], "location": ["Україна"]}
{"title": "Full Stack Developer (Python,React) Miami location", "company": "Global Teams", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Redux", "CI/CD", "Django", "Git", "AI", "Flask", "Jenkins", "PostgreSQL", "React", "Go", "GCP", "RESTful", "SQL", "MongoDB", "MySQL"], "location": ["Україна"]}
{"title": "Back End Developer", "company": "Nashpush", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "Django", "Docker", "Saas", "OOP", "AI", "Flask", "AWS", "Go", "Kubernetes"], "location": ["Кіпр", "Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$4500-6000", "technologies": ["Python", "API", "Airflow", "OOP", "AI", "Flask", "AWS", "DevOps", "Apache", "Go", "MongoDB", "CI/CD"], "location": ["Україна"]}
{"title": "Senior / Lead Technical Support Developer", "company": "ApomSolutions", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "Azure", "Docker", "Java", "OOP", "AI", "AWS", "GCP", "Oracle", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["Python", "Docker", "AI", "AWS", "Go", "Redis", "Tornado", "RabbitMQ", "Kubernetes", "aiohttp", "CI/CD"], "location": ["Словаччина", "Україна"]}
{"title": "Senior Python Developer", "company": "Develux", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Azure", "Django", "Docker", "AI", "NoSQL", "Flask", "AWS", "GraphQL", "PostgreSQL", "Go", "SQL", "FastAPI", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["API", "Moment", "AI", "Embers", "Click", "Go"], "location": ["Україна"]}
{"title": "Senior Python developer (AWS)", "company": "TemaBit Fozzy Group", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Python", "API", "Git", "OOP", "NoSQL", "AWS", "AI", "SQL", "CI/CD"], "location": ["Україна"]}
{"title": "AI Enthusiast / Machine Learning", "company": "King's Choice", "company_type": "Product", "salary": "$2000-4000", "technologies": ["ChatGPT", "AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer (Data Engineering Focus)", "company": "HRForecast", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Python", "API", "Django", "Pandas", "AI", "FastAPI", "Flask", "PostgreSQL", "Go", "Kafka", "RESTful", "SQL", "NumPy"], "location": ["Україна"]}
{"title": "strong Python over Django dev", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Django", "Docker", "OOP", "AI", "AWS", "PostgreSQL", "Go", "SQL", "MongoDB", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "KnubiSoft", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Python", "API", "Django", "OOP", "GraphQL", "AWS", "AI", "Embers", "Go", "CSS"], "location": ["Україна"]}
{"title": "Python developer", "company": "Odore", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Python", "API", "Git", "AI", "AWS", "PostgreSQL", "Go", "SQL", "Postman", "SQLAlchemy", "Pytest"], "location": ["Велика Британія"]}
{"title": "Python Tech Lead", "company": "Dataforest", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Python", "Airflow", "Django", "Docker", "Pandas", "AI", "NoSQL", "AWS", "Flask", "Elasticsearch", "Embers", "Go", "GCP", "Kafka", "Redis", "SQL", "Kubernetes"], "location": ["Німеччина", "Польща", "Словаччина", "Україна"]}
{"title": "Python Engineer", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $9000", "technologies": ["Python", "API", "Azure", "Docker", "AI", "AWS", "Ansible", "Go", "GCP", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Full-stack (JS/Python) / Tech lead", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Python", "API", "Django", "Git", "AI", "NoSQL", "AWS", "Go", "GCP", "JavaScript", "SQL", "MongoDB"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Ava Technologies Inc.", "company_type": "Product", "salary": null, "technologies": ["Python", "ChatGPT", "AI", "AWS", "Embers", "Go", "Serverless", "MongoDB"], "location": ["Чехія", "Нідерланди"]}
{"title": "Quality Assurance Architect (Networking)", "company": "PLVision", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "Unittest", "Robot Framework", "Docker", "AI", "Linux", "Kubernetes", "Embers", "Ansible", "Automation", "Go", "Architect", "Networking", "Pytest", "CI/CD"], "location": ["Україна"]}
{"title": "Team Lead Python", "company": "Capital Recruiters", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "Django", "Flask", "React", "SQL"], "location": ["Україна"]}
{"title": "Python Back-End Engineer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$4500-6000", "technologies": ["Python", "ML", "Azure", "AI", "AWS", "GCP", "Redis", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Bluefield Technologies", "company_type": "Product", "salary": "$5000-6000", "technologies": ["HTML", "AI", "asyncio", "Backbone", "RESTful", "Docker", "Linux", "Ccna", "ML", "Git", "React", "CSS", "TypeScript", "Python", "API", "Pandas", "Go", "SQL", "Networking", "aiohttp"], "location": ["Словаччина", "Україна"]}
{"title": "Senior Cloud Developer", "company": "Alcor", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "Cloud", "AI", "NoSQL", "AWS", "Vue.Js", "JavaScript", "SQL"], "location": ["Чехія", "Польща", "Румунія", "Словаччина", "Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["Python", "AI", "DevOps", "Crossplatform"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$5000-7000", "technologies": ["Python", "API", "ML", "HTML", "Docker", "Git", "AI", "AWS", "Foundation", "RESTful", "Go", "JavaScript", "CSS", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Azure", "Docker", "Git", "Flux", "AI", "Linux", "AWS", "Jenkins", "Go", "GCP", "MongoDB"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with ML experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Python", "ML", "AI", "Angular", "AWS", "Go", "Ocr", "Node.Js"], "location": ["Естонія", "Польща", "Україна"]}
{"title": "Senior Python/DevOps Developer", "company": "Chrysalis Gate", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "Moment", "Git", "AI", "DevOps", "AWS", "React", "Kafka", "Redis", "Spark"], "location": ["Литва", "Україна", "Польща", "Словаччина", "Румунія"]}
{"title": "Senior/Lead Python Engineer with Data skills", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Python", "OOP", "AI", "AWS", "Go", "SQL", "Spark"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "InventorSoft", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "API", "DevOps", "SQL", "FastAPI", "MySQL"], "location": ["Україна"]}
{"title": "Corsound AI - Senior Algorithms Developer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$2000-4000", "technologies": ["Python", "API", "TensorFlow", "Algorithms", "AI", "PyTorch", "Embers", "Go"], "location": ["Україна", "Грузія"]}
{"title": "Senior Data Scientist for the oil and gas data prediction solutions", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Python", "TensorFlow", "Azure", "Scikit-learn", "Pandas", "AI", "Go", "SQL", "NumPy"], "location": ["Україна"]}
{"title": "Algorithm Developer for Corsound AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["Python", "API", "TensorFlow", "Algorithms", "AI", "PyTorch", "Embers", "Go"], "location": ["Грузія", "Польща", "Україна"]}
{"title": "Senior Data Scientist for the oil and gas industry", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Python", "TensorFlow", "Scikit-learn", "Azure", "Pandas", "Go", "SQL", "NumPy"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "Mobilunity", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Dash", "API", "Azure", "Requests", "Fairplay", "AI", "AWS", "Playready", "Go"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with OCR experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Python", "ML", "AI", "Angular", "AWS", "Go", "Ocr", "Node.Js"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Quickstaffing LLC", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["Python", "Pandas", "AI", "Go", "SQL", "Spark", "Jupyter Notebook"], "location": ["Вірменія"]}
{"title": "Senior Backend Engineer for Neolithics AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["Python", "ML", "Azure", "AI", "AWS", "Go", "GCP", "Redis", "Kubernetes", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Software Engineer (DataDiscovery)", "company": "MEGOGO", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Python", "API", "Docker", "OOP", "AWS", "PostgreSQL", "Apache", "Click", "Go", "Kafka", "SQL", "MongoDB", "Kubernetes", "Spark", "MySQL"], "location": ["Україна"]}
{"title": "Middle/Senior Python/Go Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Python", "API", "ML", "Git", "AI", "Go", "JavaScript"], "location": ["Польща", "Сербія", "Португалія"]}
{"title": "Senior Python (Back-end) Developer", "company": "Animo", "company_type": "Outsource", "salary": "від $5000", "technologies": ["Python", "Apis", "API", "Django", "AI", "AWS", "Go", "Node.Js", "English"], "location": ["Україна"]}
{"title": "Python Developer (Data-driven)", "company": "TechbrainJobs", "company_type": "Product", "salary": "$6000-8000", "technologies": ["Python", "API", "Git", "Docker", "AI", "Linux", "AWS", "Go", "SQL", "CI/CD"], "location": ["Ізраїль"]}
{"title": "Python Developer", "company": "Intsurfing", "company_type": "Outstaff", "salary": "$2500-4000", "technologies": ["Python", "API", "ML", "Azure", "AI", "Linux", "AWS", "SQL"], "location": ["Україна"]}
{"title": "Mid-Senior Python developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Python", "API", "AI", "Go"], "location": ["Польща"]}
{"title": "Senior Back-end Python Engineer", "company": "Particles Global", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Python", "API", "Moment", "Docker", "OOP", "Linux", "AI", "PostgreSQL", "Go", "Unix", "SQL", "Kubernetes"], "location": ["Україна"]}
{"title": "Python Full Stack Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Python", "ML", "HTML", "Git", "TypeScript", "PHP", "AI", "Angular", "DevOps", "Foundation", "Linux", "React", "Click", "Go", "SQL", "CSS", "Node.Js", "MySQL"], "location": ["Україна"]}
{"title": "Tech/Team Lead (Python)", "company": "Indigo Tech recruitment", "company_type": "Product", "salary": null, "technologies": ["Python", "API", "ML", "Pandas", "AI", "PyTorch", "AWS", "PostgreSQL", "Go", "SQL", "FastAPI"], "location": ["Франція"]}
{"title": "Senior Full-Stack Engineer Python/React - UKRAINE or SPAIN", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Celery", "Azure", "Docker", "PySpark", "Pandas", "AI", "Dask", "Flask", "DevOps", "Embers", "React", "Go", "SQL", "SQLAlchemy", "D3", "Spark", "TypeScript"], "location": ["Україна", "Іспанія"]}
{"title": "Senior Backend Engineer (Python)", "company": "Super Dispatch", "company_type": "Product", "salary": "$5000-6500", "technologies": ["Python", "API", "Ddd", "Django", "AI", "AWS", "Go", "GCP", "Kubernetes", "CI/CD"], "location": ["Узбекистан"]}
{"title": "Senior Python Full-stack Software Engineer", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "TypeScript", "AI", "AWS", "Jenkins", "Go", "JavaScript", "CI/CD"], "location": ["Україна"]}
{"title": "Senior Full-Stack Developer/ AI Evangelist", "company": "Softengi", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["Python", "ML", "ChatGPT", "Copilot", "Azure", "Git", "AI", "AWS", "DevOps", "React", "JavaScript", "Angular", "CI/CD"], "location": ["Чехія", "Литва", "Латвія", "Польща", "Україна"]}
