{"title": "Software Engineer", "company": "incoalliance", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Kubernetes", "Spark", "TensorFlow", "Go", "AI", "Git", "Airflow", "Redis", "Microservices", "Pandas", "API", "Elasticsearch", "Jenkins", "OOP", "Python", "Docker"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "SPS Commerce", "company_type": "Product", "salary": null, "technologies": ["Kubernetes", "AWS", "AI", "Embers", "CI/CD", "DevOps", "API", "Python", "Docker"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "Go", "AI", "ML", "Xml", "API", "Azure", "Python", "Json"], "location": ["Україна"]}
{"title": "Django developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Django", "Go", "AI", "FastAPI", "API", "Celery", "Python"], "location": ["Україна"]}
{"title": "Quantitative Analyst", "company": "Weem", "company_type": "Product", "salary": null, "technologies": ["Phyton", "Perl", "Python", "SQL"], "location": ["Канада"]}
{"title": "Middle+ Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "AWS", "Go", "GCP", "AI", "ML", "CI/CD", "NoSQL", "FastAPI", "PostgreSQL", "API", "Flask", "GraphQL", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Technical Lead", "company": "Zoot", "company_type": "Product", "salary": "$3000-4200", "technologies": ["JWT", "CSS", "HTML", "Linux", "Go", "AI", "ML", "RESTful", "Bootstrap", "API", "jQuery", "JavaScript", "Node.Js", "Python"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Blackthorn Vision", "company_type": "Outsource", "salary": null, "technologies": ["React", "ML", "Pandas", "JavaScript", "TypeScript", "CSS", "HTML", "Django", "Linux", "Black", "Flask", "Node.Js", "SQL", "AWS", "AI", "Github", "Scipy", "API", "Azure", "NumPy", "Go", "Angular", "Git", "Python"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Product", "salary": null, "technologies": ["AI", "FastAPI", "Git", "Dash", "API", "Flask", "OOP", "Python", "SQL"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "TechMagic", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["React", "Django", "AWS", "Go", "AI", "Angular", "CI/CD", "PostgreSQL", "Selenium", "DevOps", "API", "JavaScript", "Node.Js", "OOP", "Python", "SQL"], "location": ["Україна"]}
{"title": "Senior Python + Scala Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "RESTful", "Embers", "PostgreSQL", "API", "Scala", "Python", "SQL"], "location": ["Польща"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "React", "HTML", "Go", "AI", "ML", "RESTful", "Embers", "PostgreSQL", "API", "JavaScript", "Python", "SQL"], "location": ["Польща"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "FastAPI", "Git", "Dash", "API", "Flask", "OOP", "Python", "SQL"], "location": ["Україна"]}
{"title": "Tech Lead (Python/Django/JS)", "company": "PLANEKS", "company_type": "Outsource", "salary": null, "technologies": ["AI", "Python", "Go", "Embers"], "location": ["Україна"]}
{"title": "Full Stack Engineer (Python/React)", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["React", "Django", "AWS", "Go", "AI", "Requests", "MySQL", "API", "JavaScript", "Python", "TypeScript", "SQL"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["React", "asyncio", "Go", "AI", "GCP", "RESTful", "Embers", "Angular", "FastAPI", "Git", "API", "Python"], "location": ["Польща", "Хорватія", "Словаччина"]}
{"title": "Strong Python Developer", "company": "NGM Agency", "company_type": "Product", "salary": "від $2000", "technologies": ["CSS", "HTML", "PHP", "Django", "Go", "AI", "Linux", "ML", "Git", "Puppet", "MySQL", "PostgreSQL", "API", "JavaScript", "OOP", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Senior Python Developer/DevOps Engineer", "company": "Powercode", "company_type": "Outsource", "salary": null, "technologies": ["Kubernetes", "Go", "AI", "CI/CD", "Git", "Dash", "Python", "Elasticsearch", "Azure", "DevOps", "Kibana"], "location": ["Німеччина", "Польща", "Україна"]}
{"title": "Middle Python+Node.JS Engineer", "company": "A-Team Global", "company_type": "Outsource", "salary": "$2500", "technologies": ["CSS", "HTML", "AI", "Go", "ML", "Embers", "Node.Js", "Python"], "location": ["Болгарія", "Німеччина", "Україна"]}
{"title": "Middle+ Python Developer", "company": "CodeIT", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Go", "AI", "Linux", "Embers", "CI/CD", "Git", "Ansible", "DevOps", "API", "Python", "PostgreSQL", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Senior Python/Django Engineer", "company": "at Apexive", "company_type": "Agency", "salary": "від $3000", "technologies": ["Kubernetes", "React", "Django", "AWS", "Go", "AI", "RESTful", "MySQL", "Python", "Docker", "SQL"], "location": ["Чехія", "Нідерланди", "Польща", "Україна"]}
{"title": "Backend Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$3500-4500", "technologies": ["Kubernetes", "CSS", "HTML", "AWS", "Go", "AI", "ML", "RESTful", "Foundation", "Git", "API", "JavaScript", "Python", "Docker"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "IvorySoft", "company_type": "Outsource", "salary": null, "technologies": ["AI", "Python", "Django", "Go"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "PLANEKS", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "Go", "AI", "FastAPI", "API", "Celery", "Python"], "location": ["Україна"]}
{"title": "Software Engineer (Python) (G)", "company": "Freelance", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Spark", "Bigdata", "AWS", "Go", "AI", "Apache", "MongoDB", "CI/CD", "Git", "Airflow", "MySQL", "PostgreSQL", "DevOps", "Moment", "Redis", "Python", "SQL"], "location": ["Румунія"]}
{"title": "Middle Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["RabbitMQ", "React", "Django", "Go", "AI", "Embers", "Node.Js", "Airflow", "PostgreSQL", "Pandas", "Celery", "Redis", "OOP", "Python", "Docker", "SQL"], "location": ["Україна", "Польща", "Вірменія"]}
{"title": "Back-end Developer (experience with GPT API)", "company": "TechHunt", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["AI", "Git", "API", "Node.Js", "Python"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Temy", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["React", "Django", "Go", "API", "Python", "GraphQL", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "FastAPI", "Git", "Dash", "API", "Flask", "OOP", "Python", "SQL"], "location": ["Україна"]}
{"title": "Django Developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Django", "Go", "AI", "FastAPI", "API", "Celery", "Python"], "location": ["Україна"]}
{"title": "Full-Stack Python Developer (with Angular)", "company": "Virtuace", "company_type": "Outsource", "salary": null, "technologies": ["Kubernetes", "Go", "AI", "ML", "Angular", "MongoDB", "CI/CD", "NumPy", "Git", "FastAPI", "Pandas", "API", "Azure", "Python", "Docker"], "location": ["Україна"]}
{"title": "Lead Python Engineer  (challenging omnichannel payment processing solution for Europe and North America)", "company": "Godel Technologies", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["AWS", "Go", "GCP", "AI", "Azure", "CI/CD", "Git", "FastAPI", "MySQL", "PostgreSQL", "DevOps", "API", "Flask", "Python", "Docker", "SQL"], "location": ["Польща", "Литва", "Болгарія"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "React", "HTML", "Go", "AI", "ML", "RESTful", "Embers", "PostgreSQL", "API", "JavaScript", "Python", "SQL"], "location": ["Польща"]}
{"title": "Senior Python Developer (experience in ML projects using Python)", "company": "ISRAEL IT", "company_type": "Outstaff", "salary": "$3000-4500", "technologies": ["Kubernetes", "Spark", "AWS", "Go", "AI", "ML", "Embers", "CI/CD", "Git", "English", "API", "OOP", "Python", "Docker"], "location": ["Україна"]}
{"title": "Middle/Senior Python engineer", "company": "Disoft", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "API", "Python", "Node.Js", "PostgreSQL", "Rest", "SQL"], "location": ["Україна", "Польща", "Хорватія", "Португалія", "Чехія"]}
{"title": "Intelligent Automation Full Stack  Developer - Open A.I. and No Code A.I. is a plus", "company": "Mentally", "company_type": "Product", "salary": "$2500-3700", "technologies": ["AWS", "Go", "AI", "ML", "Saas", "Git", "DevOps", "Azure", "Python", "Docker", "Automation"], "location": ["Італія"]}
{"title": "Blockchain Developer for Cryptocurrency Arbitrage Bot", "company": "CallC247", "company_type": "Product", "salary": "від $2000", "technologies": ["Aave", "Compound", "AI", "Uniswap", "Solidity", "API", "JavaScript", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "GEO Pay", "company_type": "Product", "salary": null, "technologies": ["Drf", "Django", "AWS", "Go", "AI", "Foundation", "Azure", "API", "Python", "Celery", "Redis", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Middle Game Mathematician (Python)", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["AI", "Python", "Go"], "location": ["Словаччина", "Україна"]}
{"title": "Senior Python Developer", "company": "EVE.calls", "company_type": "Product", "salary": "$4000", "technologies": ["TensorFlow", "Unix", "Grpc", "Python", "Websockets"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Orderry", "company_type": "Product", "salary": "$3000-4500", "technologies": ["React", "Redux", "Docker", "RabbitMQ", "Django", "Kafka", "aiohttp", "Webpack", "SQL", "AI", "Redis", "PostgreSQL", "Kubernetes", "asyncio", "Go", "Selenium", "Pytest", "Celery", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "IT Svit", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["React", "ML", "DevOps", "Docker", "Django", "MongoDB", "Kafka", "Elasticsearch", "Rest", "SQL", "TensorFlow", "AI", "API", "PostgreSQL", "Go", "Git", "Microservices", "jQuery", "Python"], "location": ["Україна"]}
{"title": "Python Developer (Django)", "company": "IT Svit", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["React", "Django", "SQL", "Go", "AI", "TensorFlow", "Kafka", "MongoDB", "Git", "jQuery", "DevOps", "API", "Python", "Elasticsearch", "PostgreSQL", "Docker", "Keycloak"], "location": ["Україна"]}
{"title": "Python developer", "company": "Uptarget", "company_type": "Product", "salary": null, "technologies": ["Kubernetes", "Go", "AI", "Kafka", "CI/CD", "Python", "Docker"], "location": ["Україна"]}
{"title": "Odoo Senior Developer", "company": "Mongrov", "company_type": "Product", "salary": null, "technologies": ["Go", "AI", "ML", "Odoo", "API"], "location": ["Колумбія", "Польща", "Україна"]}
{"title": "FullStack developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "від $3000", "technologies": ["CSS", "React", "HTML", "Django", "Go", "AI", "ML", "Apache", "Angular", "MongoDB", "Python", "jQuery", "JavaScript", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Python developer", "company": "SourceTER", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "AI", "GCP", "Apache", "Airflow", "API", "Azure", "Python"], "location": ["Вірменія", "Азербайджан", "Грузія", "Казахстан", "Україна"]}
{"title": "Python developer (Web scraping expert)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "AI", "BeautifulSoup", "ML", "Git", "Airflow", "Selenium", "API", "Scrapy", "Python", "SQL"], "location": ["Сполучені Штати"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["CSS", "React", "Django", "Go", "AI", "Angular", "JavaScript", "Flask", "Python"], "location": ["Україна"]}
{"title": "Full-Stack Python Engineer", "company": "MEV", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["React", "Django", "AWS", "Go", "AI", "ML", "CI/CD", "Redis", "DevOps", "API", "Celery", "Jenkins", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["CSS", "SQLAlchemy", "AWS", "Go", "AI", "Embers", "Vue.Js", "Git", "MySQL", "Pandas", "API", "Pytest", "Flask", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "HTML", "Django", "Go", "Linux", "ML", "NoSQL", "MySQL", "PostgreSQL", "API", "jQuery", "Redis", "OOP", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Strong Middle / Senior Python Developer", "company": "TECHIIA Holding", "company_type": "Product", "salary": null, "technologies": ["Celery", "Django", "Go", "AI", "Angular", "CI/CD", "Black", "Scrum", "DevOps", "API", "Python", "Elasticsearch", "Redis", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Back-end developer (Python/Web scraping)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "AI", "BeautifulSoup", "ML", "Git", "Airflow", "Selenium", "API", "Scrapy", "Python", "SQL"], "location": ["Сполучені Штати"]}
{"title": "Senior Python Developer (with ML/AI  background)", "company": "Cyberspectr Solution", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["TensorFlow", "AWS", "AI", "PyTorch", "CI/CD", "NumPy", "Git", "Scikit-learn", "Pandas", "Python", "Docker"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "DTEK", "company_type": "Product", "salary": null, "technologies": ["React", "Linux", "Go", "AI", "Embers", "MongoDB", "NoSQL", "Java", "MySQL", "PostgreSQL", "API", "JavaScript", "Redis", "Python", "SQL"], "location": ["Україна"]}
{"title": "Python developer", "company": "NestLogic", "company_type": "Product", "salary": "$2500", "technologies": ["Kubernetes", "Linux", "AI", "Go", "ML", "Jupyter Notebook", "Python", "Docker"], "location": ["Україна"]}
{"title": "Odoo/Python Developer", "company": "Sentrium", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "AI", "Linux", "RESTful", "MongoDB", "Git", "Odoo", "API", "Python", "Flask", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["CSS", "HTML", "Linux", "ML", "Git", "API", "Python", "SQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FoxmindEd", "company_type": "Product", "salary": "$3000-5000", "technologies": ["CSS", "HTML", "Django", "SQLAlchemy", "AWS", "Go", "ML", "Linux", "Git", "MySQL", "PostgreSQL", "JavaScript", "Flask", "OOP", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Python developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "HTML", "Django", "Go", "Linux", "ML", "NoSQL", "PostgreSQL", "API", "jQuery", "Redis", "OOP", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Competera", "company_type": "Product", "salary": null, "technologies": ["Spark", "Click", "Go", "AI", "GCP", "Apache", "Kafka", "Airflow", "Luigi", "Python", "SQL"], "location": ["Кіпр", "Україна"]}
{"title": "Middle/Senior Python Software Developer (or switcher from another OOP language)", "company": "Jito.dev", "company_type": "Outsource", "salary": "від $2000", "technologies": ["Kubernetes", "Linux", "AWS", "Go", "AI", "CI/CD", "Git", "DevOps", "Python", "Gis", "OOP", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Middle\\Senior Backend Engineer ( Python)", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["RabbitMQ", "Django", "AWS", "Go", "AI", "asyncio", "Embers", "Kafka", "Git", "Ansible", "API", "Celery", "JavaScript", "Node.Js", "GraphQL", "Python", "TypeScript", "Docker"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Django)", "company": "Flexyti", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Kubernetes", "Django", "AWS", "Go", "AI", "MongoDB", "CI/CD", "PostgreSQL", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Backend Python/Django Developer for a SaaS Product", "company": "Iteksas", "company_type": "Product", "salary": "$3000-6000", "technologies": ["CSS", "HTML", "Django", "Go", "ML", "NoSQL", "Saas", "Product", "Celery", "Python", "SQL"], "location": ["Литва", "Україна"]}
{"title": "Senior Python Developer", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "HTML", "Django", "AWS", "Senior", "Go", "ML", "RESTful", "NoSQL", "Git", "MySQL", "API", "JavaScript", "Flask", "Python", "SQL"], "location": ["Україна"]}
{"title": "Solidity/Blockchain expert (Smart Contract)", "company": "WeSoftYou", "company_type": "Outsource", "salary": null, "technologies": ["React", "AI", "Git", "Solidity", "OOP", "Python"], "location": ["Україна"]}
{"title": "Python Backend розробник", "company": "Sk-Telemed", "company_type": "Product", "salary": "від $3000", "technologies": ["RabbitMQ", "Virtualenv", "Django", "AWS", "Go", "AI", "Linux", "Git", "PostgreSQL", "Pyenv", "Celery", "Redis", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["React", "Django", "Go", "AI", "Vue.Js", "Angular", "Git", "DevOps", "API", "Flask", "Python", "Docker", "Pyramid"], "location": ["Польща"]}
{"title": "Python Developer for Automotive Project", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["React", "Django", "Go", "AI", "Vue.Js", "Angular", "Git", "Ansible", "DevOps", "API", "Flask", "Python", "Docker", "Pyramid"], "location": ["Польща"]}
{"title": "Software and MLOps Engineer (Python)  (Warsaw)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": null, "technologies": ["React", "TensorFlow", "AWS", "Go", "AI", "ML", "DevOps", "API", "Node.Js", "OOP", "Python", "Mlops"], "location": ["Польща"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["CSS", "React", "Django", "Go", "AI", "Angular", "JavaScript", "Flask", "Python"], "location": ["Україна"]}
{"title": "DevOps Engineer (with Golang or Python)", "company": "Akvelon", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Kubernetes", "AWS", "Go", "AI", "ML", "CI/CD", "Git", "API", "Python", "Sdn", "Docker"], "location": ["Азербайджан", "Молдова", "Польща", "Туреччина", "Україна"]}
{"title": "Python Developer/Data Engineer", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["TensorFlow", "AI", "AWS", "ML", "PyTorch", "Git", "OpenCV", "Pandas", "Python", "NumPy"], "location": ["Україна"]}
{"title": "Python Developer for EdTech company", "company": "Projector", "company_type": "Product", "salary": null, "technologies": ["Python", "AI"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer (Prom.ua)", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["React", "JavaScript", "Docker", "RabbitMQ", "CSS", "Click", "MongoDB", "Kafka", "Webpack", "Elasticsearch", "SQL", "CI/CD", "API", "Redis", "PostgreSQL", "Kubernetes", "Go", "Git", "Python"], "location": ["Україна"]}
{"title": "Python/Django Full Stack Developer", "company": "BikeBUBL", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Frontend", "Django", "Go", "AI", "Vue.Js", "Js", "PostgreSQL", "Python", "Vue", "SQL"], "location": ["Велика Британія", "Україна"]}
{"title": "Python\\Django Backend Developer", "company": "Animo", "company_type": "Outsource", "salary": "до $5500", "technologies": ["Django", "AWS", "Go", "AI", "Remote", "API", "Node.Js", "Backend", "Python", "SQL"], "location": ["Україна"]}
{"title": "Middle Backend Developer", "company": "Partner-way", "company_type": "Product", "salary": null, "technologies": ["Go", "Requests", "API", "JavaScript", "Python", "TypeScript"], "location": ["Велика Британія", "Сполучені Штати", "Україна", "Німеччина", "Польща"]}
{"title": "Middle/Senior BackEnd developer Python/Django", "company": "Meest China", "company_type": "Product", "salary": null, "technologies": ["JWT", "Nginx", "Django", "AWS", "Go", "AI", "RESTful", "Git", "MySQL", "Redis", "Wagtail", "API", "Celery", "Jenkins", "Python", "SQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "SKILLUP", "company_type": "Product", "salary": null, "technologies": ["CSS", "HTML", "Django", "AI", "Go", "ML", "Python", "SQL"], "location": ["Україна"]}
{"title": "Python/GoLang developer (Europe)", "company": "TEAM International", "company_type": "Outstaff", "salary": null, "technologies": ["Kubernetes", "Django", "Go", "AI", "GCP", "Foundation", "NoSQL", "API", "Python", "SQL"], "location": ["Польща", "Португалія"]}
{"title": "Senior Python  Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["AI", "Go", "ML", "Git", "OOP", "Python"], "location": ["Португалія"]}
{"title": "Software Python Developer", "company": "Capital Recruiters", "company_type": "Product", "salary": "$3000-4500", "technologies": ["React", "Django", "API", "Flask", "Python", "SQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": "$3000-4500", "technologies": ["Python", "DevOps", "AI"], "location": ["Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": "$3000-6000", "technologies": ["Matplotlib", "Go", "AI", "Embers", "Pandas", "Dash", "Plotly", "Python", "NumPy", "SQL"], "location": ["Польща"]}
{"title": "Python Engineer", "company": "APOSTERA UA HARMAN", "company_type": "Product", "salary": "від $3000", "technologies": ["Linux", "AI", "ML", "Middle", "Git", "DevOps", "API", "Python", "Automotive", "Senior", "Docker", "Automation"], "location": ["Угорщина", "Польща", "Україна"]}
{"title": "Senior Algorithms Developer (Speech Recognition, Python)", "company": "SD Solutions", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["TensorFlow", "Go", "AI", "ML", "Embers", "PyTorch", "API", "Python"], "location": ["Кіпр", "Грузія", "Польща", "Україна"]}
{"title": "Middle Python Developer", "company": "SoftVision", "company_type": "Outsource", "salary": null, "technologies": ["Kubernetes", "Spark", "Django", "AWS", "Go", "AI", "Apache", "Git", "MySQL", "PostgreSQL", "API", "Flask", "Python", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["RabbitMQ", "React", "Django", "Go", "AI", "Embers", "Node.Js", "Airflow", "PostgreSQL", "Pandas", "Celery", "Redis", "OOP", "Python", "Docker", "SQL"], "location": ["Польща", "Україна"]}
{"title": "Python backend Developer", "company": "Yanpix", "company_type": "Product", "salary": "$3000-5500", "technologies": ["Django", "Go", "MongoDB", "Git", "MySQL", "PostgreSQL", "DevOps", "Flask", "Python", "SQL"], "location": ["Україна", "Словаччина", "Польща", "Чехія"]}
{"title": "Senior Python Engineer", "company": "Unidatalab", "company_type": "Product", "salary": "від $2000", "technologies": ["Kubernetes", "Django", "AWS", "Go", "GCP", "AI", "Kafka", "FastAPI", "Git", "NoSQL", "API", "Azure", "Python", "ChatGPT", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Middle+/Senior Python developer", "company": "TechbrainJobs", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Nginx", "Drf", "Mongo", "Django", "Go", "AI", "Angular", "aiohttp", "Git", "Elasticsearch", "Python", "Celery", "Redis", "PostgreSQL", "SQL"], "location": ["Україна"]}
{"title": "Senior Appian Developer", "company": "DICEUS", "company_type": "Outstaff", "salary": null, "technologies": ["Appian", "Sail", "Go", "AI", "Embers", "Git", "API", "JavaScript", "SQL"], "location": ["Йорданія", "Польща", "Україна"]}
{"title": "Middle Developer (Python/Django) in product", "company": "Graintrack", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "AI", "RESTful", "CI/CD", "Saas", "API", "Python", "Redis", "PostgreSQL", "Docker", "SQL"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$3000-5000", "technologies": ["ML", "PyTorch", "DevOps", "API", "Python"], "location": ["Україна"]}
{"title": "Full Stack Software Engineer", "company": "Seatpick", "company_type": "Product", "salary": null, "technologies": ["Django", "AWS", "Go", "AI", "ML", "API", "JavaScript", "TypeScript", "Docker"], "location": ["Україна"]}
{"title": "Data Engineer", "company": "Websmile", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "AWS", "Go", "AI", "ML", "Linux", "Git", "Airflow", "Flask", "Jenkins", "Docker"], "location": ["Ізраїль", "Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$3000-5000", "technologies": ["ML", "PyTorch", "DevOps", "API", "OOP", "Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "Flyaps", "company_type": "Outsource", "salary": null, "technologies": ["CSS", "Django", "Go", "AI", "Linux", "CI/CD", "Git", "JavaScript", "Python", "SQL"], "location": ["Україна"]}
