{"title": "Software Engineer", "company": "incoalliance", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Spark", "Go", "Jenkins", "Microservices", "Kubernetes", "AI", "Docker", "OOP", "Airflow", "Elasticsearch", "Pandas", "Git", "API", "TensorFlow", "Redis", "Python"], "location": ["Україна"]}
{"title": "Senior Python Backend Developer", "company": "TechHunt", "company_type": "Product", "salary": "від $5000", "technologies": ["Go", "CI/CD", "Elasticsearch", "Django", "Python", "RabbitMQ"], "location": ["Німеччина", "Нідерланди", "Польща", "Україна", "Португалія"]}
{"title": "SEnior Python WMS", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["Go", "Wms", "AI", "OOP", "API", "Python", "Linux"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Senior Python Developer", "company": "TechMagic", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Django", "DevOps", "Go", "Selenium", "React", "AI", "OOP", "JavaScript", "PostgreSQL", "SQL", "CI/CD", "Node.Js", "AWS", "Angular", "API", "Python"], "location": ["Україна"]}
{"title": "Tech Lead (Python/Django/JS)", "company": "PLANEKS", "company_type": "Outsource", "salary": "$1500-2800", "technologies": ["AI", "Go", "Embers", "Python"], "location": ["Україна"]}
{"title": "Junior Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Postman", "CI/CD", "Git", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Junior software engineer (parsing/reverse)", "company": "Artellence", "company_type": "Product", "salary": "до $2500", "technologies": ["Go", "Docker", "JavaScript", "aiohttp", "Parsing", "MongoDB", "Security", "Redis", "NoSQL", "Java", "Requests", "AI", "SQL", "asyncio", "API", "Linux", "Selenium", "BeautifulSoup", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Postman", "CI/CD", "Git", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Python NLP Developer", "company": "Tangible AI", "company_type": "Agency", "salary": "до $2500", "technologies": ["Nlp", "Go", "AI", "CI/CD", "Git", "Django", "Python"], "location": ["Сполучені Штати"]}
{"title": "Developer for AI ChatGPT bot", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "GPT"], "location": ["Україна", "Польща"]}
{"title": "Full Stack Engineer (Python/React)", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Go", "Requests", "React", "AI", "JavaScript", "TypeScript", "SQL", "MySQL", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Backend Engineer", "company": "Reef Technlogies", "company_type": "Product", "salary": "$7560-11760", "technologies": ["Go", "AI", "Embers", "Django", "Python"], "location": ["Польща"]}
{"title": "Middle Python Developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["CSS", "ML", "HTML", "SQL", "Git", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Developer", "company": "NONAME DIGITAL", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["Django", "DevOps", "Go", "AI", "Docker", "Git", "API", "Redis", "Python", "Linux"], "location": ["Україна"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": "$1500-3000", "technologies": ["Go", "AI", "Git", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer", "company": "Launch Labs", "company_type": "Outsource", "salary": null, "technologies": ["Go", "React", "GraphQL", "ML", "AI", "TypeScript", "Flask", "MongoDB", "AWS", "Celery", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "OOP", "Flask", "SQL", "Git", "Dash", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Airflow", "GCP", "Git", "MySQL", "CI/CD", "Moment", "Spark", "Cassandra", "MongoDB", "Redis", "Apache", "Kafka", "AI", "SQL", "Bigdata", "AWS", "API", "RabbitMQ", "Elasticsearch", "Django", "Python"], "location": ["Румунія"]}
{"title": "Data and Machine Learning Engineer (Python)", "company": "Softwarium", "company_type": "Outsource", "salary": null, "technologies": ["Go", "ML", "Docker", "Dask", "Git", "Spark", "NoSQL", "React", "AI", "PyTorch", "SQL", "NumPy", "Pandas", "Azure", "Embers", "AWS", "API", "TensorFlow", "OOP", "Scikit-learn", "Angular", "Python"], "location": ["Польща", "Україна"]}
{"title": "Junior Python Developer in Test (CSA)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Jenkins", "ML", "AI", "Docker", "SQL", "Git", "Pytest", "AWS", "asyncio", "CI/CD", "NoSQL", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Go", "AI", "JavaScript", "Django", "Python"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["AI", "OOP", "Docker", "Git", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Full-Stack Engineer Python/React", "company": "Intellias", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["DevOps", "Spark", "Go", "React", "SQLAlchemy", "AI", "Docker", "TypeScript", "Flask", "SQL", "Pandas", "Dask", "Azure", "Celery", "PySpark", "Python", "D3"], "location": ["Україна"]}
{"title": "Data Mining Engineer needed for data centric startup", "company": "Forecasa", "company_type": "Product", "salary": null, "technologies": ["Spark", "Selenium", "Kubernetes", "AI", "Docker", "Airflow", "Pandas", "Git", "PySpark", "CI/CD", "Python"], "location": ["Сполучені Штати"]}
{"title": "Middle/Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Data Scientist / Senior Python developer", "company": "Simplify", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Tensorrt", "OpenCV", "ML", "AI", "PyTorch", "Git", "Sota", "Python"], "location": ["Україна", "Німеччина", "Польща"]}
{"title": "Backend Engineer with AI Integration Experience", "company": "Visarsoft", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["Nlp", "React", "Tdd", "AI", "JavaScript", "TypeScript", "Angular", "Azure", "AWS", "Agile", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Intetics", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Etl", "Go", "ML", "AI", "Airflow", "GCP", "SQL", "Git", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Quantitative Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Go", "AI", "OOP", "Git", "Python", "Linux"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": "до $3000", "technologies": ["Django", "Apache", "Go", "React", "AI", "OOP", "Docker", "PHP", "Flask", "SQL", "Elasticsearch", "Git", "MySQL", "AWS", "MongoDB", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "AnyforSoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "React", "AI", "OOP", "PHP", "Git", "Django", "Python"], "location": ["Україна"]}
{"title": "Fullstack Software Developer (Python+React)/ AI enthusiast", "company": "Forex Tester Software Inc", "company_type": "Product", "salary": "$700-1500", "technologies": ["Svelte", "API", "Go", "React", "AI", "Git", "Embers", "Angular", "Vue", "GPT", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outstaff", "salary": "$2000-4000", "technologies": ["Go", "AI", "JavaScript", "Django", "English", "Mentoring", "Python"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "SPS Commerce", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Kubernetes", "AI", "Docker", "CI/CD", "Embers", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Django developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["API", "Go", "AI", "Celery", "Django", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "Chatmasters", "company_type": "Product", "salary": "$1200-2500", "technologies": ["Drf", "Go", "ML", "Websockets", "AI", "Restapi", "Flask", "FastAPI", "SQL", "MongoDB", "AWS", "API", "GPT", "Postgressql", "Python", "Linux"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "Go", "GraphQL", "ML", "AI", "Docker", "GCP", "Flask", "SQL", "PostgreSQL", "CI/CD", "AWS", "API", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Application Engineer", "company": "UnameIT", "company_type": "Product", "salary": null, "technologies": ["AI", "Git", "Python", "Fabric"], "location": ["Україна"]}
{"title": "Senior Python Engineer (Application Platform Track)", "company": "PandaDoc", "company_type": "Product", "salary": null, "technologies": ["Kafka", "Go", "Rabbimq", "Kubernetes", "AI", "Docker", "PostgreSQL", "SQL", "Pandas", "asyncio", "Git", "AWS", "Django", "FastAPI", "Python", "RabbitMQ"], "location": ["Польща", "Португалія", "Україна"]}
{"title": "Senior Python Developer", "company": "FXC Intelligence", "company_type": "Product", "salary": "$5000-7000", "technologies": ["AI", "Docker", "SQL", "API", "Python"], "location": ["Велика Британія"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Go", "React", "CSS", "ML", "AI", "HTML", "RESTful", "JavaScript", "PostgreSQL", "SQL", "Embers", "API", "Python"], "location": ["Польща"]}
{"title": "Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["Selenium", "ML", "AI", "HTML", "Flask", "SQL", "Scraping", "Pandas", "Embers", "BeautifulSoup", "API", "NoSQL", "Python"], "location": ["Польща", "Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Product", "salary": null, "technologies": ["AI", "OOP", "Flask", "SQL", "Git", "Dash", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Python + Scala Developer", "company": "DataArt", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Go", "Scala", "AI", "RESTful", "PostgreSQL", "SQL", "Embers", "API", "Python"], "location": ["Польща"]}
{"title": "Python Engineer", "company": "Temy", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Django", "Go", "React", "GraphQL", "PostgreSQL", "SQL", "API", "Python"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "OOP", "Flask", "SQL", "Git", "Dash", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Quantitative Analyst", "company": "Weem", "company_type": "Product", "salary": "від $2000", "technologies": ["Perl", "SQL", "Python", "Phyton"], "location": ["Канада"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["API", "DevOps", "Go", "AI", "Restapi", "SQL", "Embers", "Django", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Json", "Xml", "AI", "ML", "Azure", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python developer (with DevOps experience)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "API", "Go", "AI", "SQL", "Embers", "Django", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Strong Junior Python Software Engineer", "company": "EVO", "company_type": "Product", "salary": "$1500-3000", "technologies": ["Go", "CSS", "Docker", "Git", "CI/CD", "aiohttp", "Kubernetes", "GraphQL", "PostgreSQL", "Webpack", "MongoDB", "Celery", "Redis", "Kafka", "React", "AI", "SQL", "asyncio", "API", "Redux", "RabbitMQ", "Click", "Elasticsearch", "Python"], "location": ["Україна"]}
{"title": "Senior Fullstack Engineer (python+react)", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Go", "React", "CSS", "ML", "AI", "HTML", "RESTful", "TypeScript", "JavaScript", "PostgreSQL", "SQL", "Git", "MySQL", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Apache", "Go", "Jenkins", "React", "Kubernetes", "AI", "JavaScript", "Airflow", "Flask", "SQL", "PostgreSQL", "Git", "Embers", "Python"], "location": ["Польща"]}
{"title": "Back-end Developer (experience with GPT API)", "company": "TechHunt", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["AI", "Node.Js", "Git", "API", "GPT", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Go", "React", "AI", "RESTful", "GCP", "Git", "asyncio", "Embers", "Angular", "API", "FastAPI", "Python"], "location": ["Польща", "Хорватія", "Словаччина"]}
{"title": "Middle Python developer", "company": "Blackthorn Vision", "company_type": "Outsource", "salary": null, "technologies": ["Go", "CSS", "ML", "JavaScript", "Git", "Github", "Black", "TypeScript", "Flask", "Node.Js", "Scipy", "React", "AI", "HTML", "SQL", "NumPy", "Pandas", "Azure", "AWS", "API", "Linux", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "backend CRM розробник", "company": "Stablexsolution", "company_type": "Product", "salary": "$1500-3000", "technologies": ["Go", "React", "CSS", "JavaScript", "SQL", "Scss", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer/DevOps Engineer", "company": "Powercode", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Go", "Kubernetes", "AI", "Elasticsearch", "Azure", "Git", "Dash", "CI/CD", "Kibana", "Python"], "location": ["Німеччина", "Польща", "Україна"]}
{"title": "Technical Lead", "company": "Zoot", "company_type": "Product", "salary": "$3000-4500", "technologies": ["Go", "JWT", "CSS", "ML", "AI", "HTML", "RESTful", "jQuery", "JavaScript", "Node.Js", "Bootstrap", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Engineer Team Lead", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "AI", "OOP", "Hadoop", "SQL", "Emr", "AWS", "Python"], "location": ["Україна"]}
{"title": "Senior Python Software Engineer", "company": "TEAM International", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Go", "AI", "GCP", "SQL", "Git", "API", "NoSQL", "Python"], "location": ["Польща", "Португалія"]}
{"title": "Software Engineer (Python) (G)", "company": "Freelance", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Spark", "Go", "Apache", "Moment", "AI", "Airflow", "PostgreSQL", "SQL", "Bigdata", "Git", "MySQL", "AWS", "MongoDB", "CI/CD", "Redis", "Python"], "location": ["Румунія"]}
{"title": "Senior Full Stack Engineer with Python and Golang", "company": "TeamDev", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "React", "Kubernetes", "AI", "Docker", "JavaScript", "GCP", "PostgreSQL", "SQL", "Azure", "Git", "AWS", "MongoDB", "CI/CD", "Python"], "location": ["Україна"]}
{"title": "Python Developer (middle)", "company": "Fordewind", "company_type": "Outsource", "salary": "$1500-3000", "technologies": ["DevOps", "Go", "ML", "AI", "HTML", "JavaScript", "Flask", "SQL", "Elasticsearch", "Pandas", "Git", "AWS", "Celery", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer-a на ізраїльський фінтех проєкт", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Spark", "Kubernetes", "AI", "SQL", "Git", "Python", "Data"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": "$5000-6500", "technologies": ["Go", "Docker", "Git", "MySQL", "Pytest", "aiohttp", "Tornado", "Kubernetes", "SQLAlchemy", "Flask", "PostgreSQL", "Falcon", "AI", "SQL", "Embers", "API", "Linux", "OOP", "Python"], "location": ["Україна"]}
{"title": "Database Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "$1000-2500", "technologies": ["Etl", "Go", "React", "CSS", "ML", "HTML", "PostgreSQL", "SQL", "Webpack", "Angular", "Pandas", "MySQL", "Celery", "Django", "Redis", "Python", "RabbitMQ", "Linux"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "PLANEKS", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["Django", "Go", "AI", "Celery", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["Go", "React", "AI", "Docker", "OOP", "Airflow", "PostgreSQL", "SQL", "Node.Js", "Pandas", "Embers", "Celery", "Django", "Redis", "Python", "RabbitMQ"], "location": ["Україна", "Польща", "Вірменія"]}
{"title": "Python Back-end Developer /Candidates from Ukraine     JobTestPrep", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Go", "React", "Kubernetes", "AI", "Docker", "RESTful", "PostgreSQL", "SQL", "CI/CD", "Git", "MongoDB", "AWS", "Angular", "API", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": "$1500-3000", "technologies": ["Go", "AI", "Git", "Django", "Python"], "location": ["Україна"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Go", "React", "Reactjs", "Kubernetes", "AI", "OOP", "Golang", "Docker", "GraphQL", "Git", "Embers", "API", "Python"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Django Developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["API", "Go", "AI", "Celery", "Django", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "DAAS Support ENG", "company": "Temerix", "company_type": "Product", "salary": "$700-800", "technologies": ["Moment", "Go", "Requests", "CSS", "ML", "AI", "HTML", "SQL", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Senior/Lead Python Developer", "company": "CHI Software", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Go", "Docker", "JavaScript", "GCP", "CI/CD", "aiohttp", "Flask", "NoSQL", "AI", "SQL", "Azure", "AWS", "API", "FastAPI", "Linux", "PHP", "Elasticsearch", "Django", "Python"], "location": ["Польща", "Україна"]}
{"title": "Strong Python Developer", "company": "NGM Agency", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "CSS", "ML", "AI", "Docker", "OOP", "Puppet", "JavaScript", "HTML", "PostgreSQL", "SQL", "PHP", "Git", "MySQL", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Go", "Kubernetes", "ML", "AI", "OOP", "HTML", "JavaScript", "Flask", "CI/CD", "Node.Js", "Git", "Pyramid", "AWS", "Embers", "Django", "Python"], "location": ["Польща"]}
{"title": "Python developer (AIOHttp)", "company": "TheWhyKingz", "company_type": "Product", "salary": null, "technologies": ["Go", "Shiny", "aiohttp", "AI", "PostgreSQL", "SQL", "MongoDB", "Embers", "Redis", "Python", "Linux"], "location": ["Латвія"]}
{"title": "Senior Python/Django Engineer", "company": "at Apexive", "company_type": "Agency", "salary": "від $3000", "technologies": ["Go", "React", "Kubernetes", "AI", "Docker", "RESTful", "SQL", "MySQL", "AWS", "Django", "Python"], "location": ["Чехія", "Нідерланди", "Польща", "Україна"]}
{"title": "Python Developer - AI Automation Solutions (LLaMA, ChatGPT Agents, Auto-GPT, LangChain)", "company": "Aimech", "company_type": "Product", "salary": "$600-3500", "technologies": ["API", "Nlp", "ML", "AI", "Langchain", "Llm", "Chatgpt", "GPT", "FastAPI", "Python"], "location": ["Велика Британія", "Україна"]}
{"title": "Middle Python+Node.JS Engineer", "company": "A-Team Global", "company_type": "Outsource", "salary": null, "technologies": ["Go", "CSS", "ML", "AI", "HTML", "Node.Js", "Embers", "Python"], "location": ["Болгарія", "Німеччина", "Україна"]}
{"title": "Backend Developer for AutoGPT", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Git", "GPT", "Python"], "location": ["Україна", "Польща"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Solid", "Multithreading", "OOP", "AI", "Git", "Databases", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Full Stack Developer (Python)", "company": "SalesNash", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Go", "Js", "CSS", "React", "ML", "HTML", "AI", "PostgreSQL", "Flask", "SQL", "Webpack", "Git", "API", "FastAPI", "Python"], "location": ["Канада"]}
{"title": "Backend Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$3500-4500", "technologies": ["Foundation", "Go", "CSS", "Kubernetes", "ML", "AI", "Docker", "RESTful", "HTML", "JavaScript", "Git", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "IvorySoft", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["AI", "Django", "Go", "Python"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "CodeIT", "company_type": "Outsource", "salary": null, "technologies": ["Django", "DevOps", "Go", "AI", "Docker", "Linux", "PostgreSQL", "SQL", "CI/CD", "Git", "Embers", "API", "Python", "Ansible"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Docker", "Git", "MySQL", "Pytest", "aiohttp", "Tornado", "Kubernetes", "SQLAlchemy", "Flask", "PostgreSQL", "Falcon", "AI", "SQL", "Embers", "API", "Linux", "OOP", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "RESTful", "SQL", "Git", "AWS", "API", "NoSQL", "Python"], "location": ["Польща"]}
{"title": "Python Team Lead", "company": "SoftConstruct", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Spark", "Go", "Kafka", "Apache", "Kubernetes", "AI", "OOP", "RESTful", "Airflow", "SQL", "Beam", "API", "aiohttp", "FastAPI", "Python", "Ansible"], "location": ["Україна"]}
{"title": "Python Back-end Developer (JobTestPrep)", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "React", "Kubernetes", "AI", "Docker", "RESTful", "CI/CD", "SQL", "Git", "AWS", "Angular", "API", "NoSQL", "Python"], "location": ["Україна", "Грузія", "Кіпр"]}
{"title": "Back End Engineer ( Python\\Java\\Go) with Data Engineering experience", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $7500", "technologies": ["Spark", "Kafka", "ML", "AI", "CI/CD", "API", "Flink"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Numerical Technologies", "company_type": "Product", "salary": "до $3000", "technologies": ["Go", "AI", "RESTful", "Azure", "Git", "AWS", "API", "FastAPI", "Python"], "location": ["Сполучені Штати", "Україна", "Португалія", "Польща", "Сінгапур"]}
{"title": "Python Lead  Developer", "company": "Genius Software", "company_type": "Product", "salary": null, "technologies": ["AI", "Git", "Python"], "location": ["Сполучені Штати"]}
{"title": "Strong Junior/Middle Python Developer", "company": "Vilmate", "company_type": "Outstaff", "salary": "$2500", "technologies": ["API", "DevOps", "Go", "AI", "Docker", "PostgreSQL", "SQL", "Git", "MongoDB", "AWS", "Celery", "Django", "Redis", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "GEO Pay", "company_type": "Product", "salary": "$3000-5500", "technologies": ["API", "Drf", "Go", "Foundation", "AI", "PostgreSQL", "SQL", "Azure", "AWS", "Celery", "Django", "Redis", "Python"], "location": ["Україна"]}
{"title": "Senior Machine Learning Engineer  video", "company": "PAYRUN", "company_type": "Product", "salary": "$5000-10000", "technologies": ["Python"], "location": ["Україна"]}
{"title": "Sr. Python Developer", "company": "TrustPoint", "company_type": "Product", "salary": null, "technologies": ["Django", "DevOps", "Go", "ML", "AI", "RESTful", "CI/CD", "Git", "API", "Python"], "location": ["Сполучені Штати"]}
{"title": "Intelligent Automation Full Stack  Developer - Open A.I. and No Code A.I. is a plus", "company": "Mentally", "company_type": "Product", "salary": "$2500-3700", "technologies": ["DevOps", "Go", "Automation", "Saas", "ML", "AI", "Docker", "Azure", "Git", "AWS", "Python"], "location": ["Італія"]}
{"title": "Python developer", "company": "Embedd", "company_type": "Product", "salary": null, "technologies": ["ML", "AI", "PostgreSQL", "SQL", "Git", "API", "Python"], "location": ["Німеччина", "Велика Британія", "Україна"]}
{"title": "Middle/Senior Python engineer", "company": "Disoft", "company_type": "Product", "salary": null, "technologies": ["API", "Go", "PostgreSQL", "SQL", "Node.Js", "Rest", "Django", "Python"], "location": ["Україна", "Польща", "Хорватія", "Португалія", "Чехія"]}
{"title": "Python Engineer", "company": "CloudMade", "company_type": "Product", "salary": "$1200-2500", "technologies": ["Apache", "Go", "Spark", "ML", "AI", "Docker", "OOP", "Flask", "SQL", "PostgreSQL", "Scikit-learn", "Pandas", "Git", "AWS", "API", "aiohttp", "FastAPI", "Python"], "location": ["Польща"]}
{"title": "Full-Stack Python Developer (with Angular)", "company": "Virtuace", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Kubernetes", "ML", "AI", "Docker", "CI/CD", "NumPy", "Pandas", "Azure", "Git", "MongoDB", "Angular", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Radency", "company_type": "Outstaff", "salary": null, "technologies": ["Postgres", "Docker", "Airflow", "GCP", "Git", "Spark", "GraphQL", "Flask", "PostgreSQL", "NoSQL", "Redis", "Apache", "Flux", "AI", "SQL", "Pandas", "API", "RabbitMQ", "Elasticsearch", "Python"], "location": ["Україна"]}
{"title": "Software Engineering Team Lead", "company": "AllSTARSIT", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["AI", "Go"], "location": ["Україна"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Go", "React", "CSS", "ML", "AI", "HTML", "RESTful", "JavaScript", "PostgreSQL", "SQL", "Embers", "API", "Python"], "location": ["Польща"]}
{"title": "Full Stack Developer", "company": "UKR.NET", "company_type": "Product", "salary": null, "technologies": ["Go", "JavaScript", "MySQL", "Sqlite", "aiohttp", "TypeScript", "PostgreSQL", "MongoDB", "NoSQL", "Redis", "React", "AI", "SQL", "asyncio", "API", "Redux", "Elasticsearch", "MobX", "Python"], "location": ["Україна"]}
{"title": "Python Developer (Django)", "company": "IT Svit", "company_type": "Outsource", "salary": null, "technologies": ["API", "DevOps", "Kafka", "Go", "React", "AI", "Docker", "PostgreSQL", "SQL", "Keycloak", "Elasticsearch", "Git", "MongoDB", "jQuery", "Django", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "IT Svit", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Go", "ML", "Docker", "Git", "jQuery", "Microservices", "PostgreSQL", "MongoDB", "Kafka", "React", "AI", "SQL", "API", "TensorFlow", "Elasticsearch", "Rest", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$5000", "technologies": ["DevOps", "Apache", "Go", "AI", "OOP", "Airflow", "Flask", "CI/CD", "MongoDB", "AWS", "Cognito", "API", "Python"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data Skills (AdTech Location Technology Leader)", "company": "Sigma Software", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "Go", "AI", "OOP", "Hadoop", "SQL", "Emr", "AWS", "Python"], "location": ["Польща", "Україна"]}
{"title": "Python/Django REST API Backend Developer", "company": "Smart UI", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["DevOps", "Go", "CSS", "ML", "Docker", "JavaScript", "Crypto", "Git", "MySQL", "jQuery", "PostgreSQL", "Backend", "MongoDB", "NoSQL", "React", "AI", "HTML", "SQL", "AWS", "API", "Linux", "PHP", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "ML/Python Senior", "company": "Danavero", "company_type": "Outstaff", "salary": "до $3000", "technologies": ["ML", "AI", "SQL", "Azure", "CI/CD", "Python"], "location": ["Україна"]}
{"title": "Python Team Lead", "company": "Mrt", "company_type": "Product", "salary": "$6000-8000", "technologies": ["Go", "AI", "OOP", "Python", "Linux"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Python developer", "company": "Ciba Health", "company_type": "Product", "salary": "до $3000", "technologies": ["API", "DevOps", "Go", "CSS", "Kubernetes", "ML", "AI", "GraphQL", "RESTful", "HTML", "Flask", "SQL", "Git", "Pyramid", "AWS", "Django", "Redis", "Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "Olearis", "company_type": "Outsource", "salary": "$1000-2500", "technologies": ["Go", "Requests", "SQLAlchemy", "AI", "OOP", "PostgreSQL", "SQL", "AWS", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Lead Python Engineer  (challenging omnichannel payment processing solution for Europe and North America)", "company": "Godel Technologies", "company_type": "Outsource", "salary": "до $5500", "technologies": ["DevOps", "Go", "AI", "Docker", "GCP", "Flask", "SQL", "PostgreSQL", "CI/CD", "Azure", "Git", "AWS", "MySQL", "API", "FastAPI", "Python"], "location": ["Польща", "Литва", "Болгарія"]}
{"title": "Middle Python Developer", "company": "Vidby", "company_type": "Product", "salary": "$1500-3000", "technologies": ["API", "Go", "AI", "PostgreSQL", "SQL", "Celery", "Django", "Redis", "Python", "RabbitMQ"], "location": ["Україна"]}
{"title": "Senior Python Developer (experience in ML projects using Python)", "company": "ISRAEL IT", "company_type": "Outstaff", "salary": "$3000-4500", "technologies": ["Spark", "Go", "Kubernetes", "ML", "AI", "OOP", "Docker", "CI/CD", "Git", "Embers", "AWS", "API", "English", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Orderry", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Go", "Docker", "Pytest", "aiohttp", "Kubernetes", "PostgreSQL", "Webpack", "Celery", "Redis", "Kafka", "React", "AI", "SQL", "asyncio", "Redux", "RabbitMQ", "Selenium", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer with JS/Typescript", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Spark", "Go", "React", "SQLAlchemy", "AI", "Docker", "TypeScript", "Flask", "SQL", "Pandas", "Dask", "Azure", "Embers", "Celery", "PySpark", "Python", "D3"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$2000-4000", "technologies": ["Django", "DevOps", "Go", "AI", "SQL", "Embers", "API", "NoSQL", "FastAPI", "Python"], "location": ["Україна", "Грузія", "Польща"]}
{"title": "Senior Python Developer", "company": "EVE.calls", "company_type": "Product", "salary": "$4000", "technologies": ["Grpc", "GPT", "Websockets", "Unix", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Middle/Senior Full-stack Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Django", "Go", "Jenkins", "React", "Kubernetes", "AI", "Docker", "RESTful", "GCP", "CI/CD", "Azure", "Git", "AWS", "API"], "location": ["Велика Британія", "Польща", "Україна"]}
{"title": "Experienced Python Developer - lifetime opportunity", "company": "CleverCrew", "company_type": "Product", "salary": null, "technologies": ["API", "Svelte", "Go", "Jenkins", "AI", "Postgres", "Git", "Django", "FastAPI"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Jenkins", "Kubernetes", "AI", "Docker", "Postman", "RESTful", "CI/CD", "Swagger", "Git", "API", "Python"], "location": ["Україна"]}
{"title": "Odoo Senior Developer", "company": "Mongrov", "company_type": "Product", "salary": null, "technologies": ["Go", "ML", "AI", "Odoo", "API"], "location": ["Колумбія", "Польща", "Україна"]}
{"title": "Senior Python Developer (with DevOps)", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$3500-5000", "technologies": ["DevOps", "API", "Go", "Chef", "ML", "AI", "Docker", "Puppet", "CI/CD", "SQL", "Azure", "Embers", "AWS", "Django", "NoSQL", "FastAPI", "Python", "Ansible"], "location": ["Україна", "Польща", "Грузія"]}
{"title": "Strong Junior/Middle Data Scientist", "company": "AppReal", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "Go", "AI", "Embers", "PySpark", "Python", "Linux"], "location": ["Україна"]}
{"title": "Technical Lead Python", "company": "Meest Group", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Go", "React", "Docker", "PostgreSQL", "SQL", "CI/CD", "Git", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Infrastructure Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Java", "Go", "AI", "OOP", "Golang", "SQL", "AWS", "API", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["Selenium", "SQLAlchemy", "AI", "ML", "HTML", "Flask", "SQL", "PostgreSQL", "BeautifulSoup", "AWS", "Celery", "API", "Python", "Linux"], "location": ["Польща", "Україна"]}
{"title": "Python developer", "company": "Uptarget", "company_type": "Product", "salary": null, "technologies": ["Go", "Kafka", "Kubernetes", "AI", "Docker", "CI/CD", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["API", "Spark", "Go", "Kubernetes", "AI", "Docker", "RESTful", "Flask", "SQL", "PostgreSQL", "Magento", "Shopify", "AWS", "Django", "FastAPI", "Python", "RabbitMQ"], "location": ["Україна"]}
{"title": "Back-end developer (Python/Web scraping)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["Selenium", "ML", "AI", "Airflow", "SQL", "Git", "BeautifulSoup", "AWS", "API", "Python", "Scrapy"], "location": ["Сполучені Штати"]}
{"title": "Back-end Python Developer", "company": "Echo", "company_type": "Outstaff", "salary": null, "technologies": ["Cassandra", "AI", "Infomaniak", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Star Global", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Microservices", "SQLAlchemy", "AI", "Docker", "ML", "GCP", "Flask", "SQL", "PostgreSQL", "Git", "MySQL", "Embers", "Celery", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Bcconsolidator", "company_type": "Product", "salary": "$5800-7000", "technologies": ["Go", "Selenium", "GraphQL", "SQLAlchemy", "AI", "ML", "Apollo", "PostgreSQL", "SQL", "Embers", "AWS", "Angular", "Python"], "location": ["Латвія", "Нідерланди", "Польща"]}
{"title": "Middle Python Developer", "company": "Wild Wild Leads", "company_type": "Agency", "salary": "$700-800", "technologies": ["Go", "CSS", "ML", "HTML", "JavaScript", "Bootstrap", "Flask", "SQL", "Git", "MySQL", "Pytest", "Celery", "Django", "Redis", "Python", "RabbitMQ"], "location": ["Україна"]}
{"title": "Python developer (Web scraping expert)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["Selenium", "ML", "AI", "Airflow", "SQL", "Git", "BeautifulSoup", "AWS", "API", "Python", "Scrapy"], "location": ["Сполучені Штати"]}
{"title": "Software Engineer (Python)", "company": "DTEK", "company_type": "Product", "salary": null, "technologies": ["Java", "Go", "React", "AI", "JavaScript", "PostgreSQL", "SQL", "MongoDB", "MySQL", "Redis", "Embers", "API", "NoSQL", "Python", "Linux"], "location": ["Україна"]}
{"title": "Blockchain Developer for Cryptocurrency Arbitrage Bot", "company": "CallC247", "company_type": "Product", "salary": "від $2000", "technologies": ["Uniswap", "Aave", "AI", "JavaScript", "Compound", "API", "Solidity", "Python"], "location": ["Україна"]}
{"title": "FullStack developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "від $2000", "technologies": ["Apache", "Go", "React", "CSS", "ML", "AI", "HTML", "jQuery", "JavaScript", "PostgreSQL", "SQL", "MongoDB", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "SourceTER", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["Apache", "AI", "Airflow", "GCP", "Azure", "AWS", "API", "Python"], "location": ["Вірменія", "Азербайджан", "Грузія", "Казахстан", "Україна"]}
{"title": "Middle Game Mathematician (Python)", "company": "Idenon", "company_type": "Product", "salary": "від $3000", "technologies": ["AI", "Go", "Python"], "location": ["Словаччина", "Україна"]}
{"title": "Middle Python Developer з досвідом AI/ML", "company": "GetCode", "company_type": "Outstaff", "salary": "від $2000", "technologies": ["Spark", "ML", "AI", "AWS", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Go", "CSS", "ML", "HTML", "OOP", "Docker", "PostgreSQL", "SQL", "Redis", "MySQL", "jQuery", "API", "NoSQL", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Go", "CSS", "SQLAlchemy", "AI", "Docker", "Vue.Js", "Flask", "SQL", "Pandas", "Git", "MySQL", "AWS", "Pytest", "API", "Embers", "Python"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Go", "React", "CSS", "AI", "JavaScript", "Flask", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer for Guardicore", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Jenkins", "Flux", "AI", "Docker", "GCP", "Azure", "Git", "AWS", "MongoDB", "Python", "Linux"], "location": ["Україна"]}
{"title": "Team Lead / Senior Python Engineer (Indigo Ag)", "company": "Intelliarts", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Go", "SQLAlchemy", "AI", "Pydantic", "SQL", "Git", "Celery", "API", "Redis", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Apache", "Go", "Jenkins", "React", "Kubernetes", "AI", "JavaScript", "Airflow", "Flask", "SQL", "PostgreSQL", "Git", "Embers", "Python"], "location": ["Україна"]}
{"title": "Junior/Midle Developer (Python, JavaScript)", "company": "Checkbox", "company_type": "Product", "salary": "$700-1500", "technologies": ["Django", "Svelte", "Go", "Kafka", "React", "RESTful", "PHP", "JavaScript", "Flask", "SQL", "PostgreSQL", "MongoDB", "Redis", "Angular", "API", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Python developer (IoT/hardware)", "company": "Canyon Development", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["Go", "OOP", "Embedded", "Git", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FoxmindEd", "company_type": "Product", "salary": "$3000-4200", "technologies": ["Go", "CSS", "SQLAlchemy", "ML", "OOP", "Docker", "HTML", "JavaScript", "Flask", "SQL", "PostgreSQL", "Git", "MySQL", "AWS", "Django", "Python", "Linux"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["CSS", "ML", "HTML", "SQL", "Git", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Developer in Test (Apps)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Jenkins", "Selenium", "ML", "AI", "Pytest", "Git", "AWS", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum", "company": "Ciklum International", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Apache", "Go", "Jenkins", "Kubernetes", "AI", "JavaScript", "GCP", "PostgreSQL", "SQL", "Airflow", "Git", "AWS", "Python"], "location": ["Україна"]}
{"title": "Senior Full Stack Engineer (Python, JS)", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Go", "ML", "AI", "OOP", "Docker", "JavaScript", "Flask", "SQL", "PostgreSQL", "AWS", "Celery", "Python"], "location": ["Україна"]}
{"title": "Full-Stack Python Engineer", "company": "MEV", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["Django", "DevOps", "Go", "Jenkins", "React", "ML", "AI", "Docker", "CI/CD", "SQL", "AWS", "Celery", "API", "Redis", "Python"], "location": ["Україна"]}
{"title": "Application Architect/Tech Lead Full-stack Engineer (JS/Python)", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["API", "Go", "AI", "JavaScript", "GCP", "SQL", "MongoDB", "Git", "AWS", "Django", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8500", "technologies": ["Go", "ML", "PyTorch", "TensorFlow", "Python"], "location": ["Польща", "Україна"]}
{"title": "Strong Middle / Senior Python Developer", "company": "TECHIIA Holding", "company_type": "Product", "salary": null, "technologies": ["API", "DevOps", "Go", "Black", "Scrum", "AI", "PostgreSQL", "SQL", "CI/CD", "Angular", "Elasticsearch", "Celery", "Django", "Redis", "Python"], "location": ["Україна"]}
{"title": "Junior Python Developer Portugal only", "company": "Adaptiq", "company_type": "Product", "salary": "до $2500", "technologies": ["Go", "AI", "GCP", "Git", "AWS", "Dash", "Python"], "location": ["Португалія"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Moment", "Go", "AI", "Click", "Embers", "API"], "location": ["Україна"]}
{"title": "Odoo/Python Developer", "company": "Sentrium", "company_type": "Product", "salary": "$2500-3700", "technologies": ["API", "Go", "AI", "RESTful", "PostgreSQL", "Flask", "SQL", "Odoo", "MongoDB", "Git", "Django", "Python", "Linux"], "location": ["Україна"]}
{"title": "Computer Vision Engineer", "company": "tangiblee", "company_type": "Product", "salary": "до $2000", "technologies": ["Go", "Scipy", "OpenCV", "AI", "PyTorch", "NumPy", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "DevOps Engineer (with Golang or Python)", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["API", "Go", "Kubernetes", "ML", "AI", "Docker", "Git", "AWS", "CI/CD", "Sdn", "Python"], "location": ["Азербайджан", "Молдова", "Польща", "Туреччина", "Україна"]}
{"title": "Back End Developer", "company": "Nashpush", "company_type": "Product", "salary": "$2500-4000", "technologies": ["API", "Go", "Saas", "Kubernetes", "AI", "OOP", "Docker", "Flask", "AWS", "Django", "Python"], "location": ["Кіпр", "Україна"]}
{"title": "Python/Django", "company": "Perlyna Devs", "company_type": "Agency", "salary": "$600-3500", "technologies": ["AI", "Django", "Go", "Python"], "location": ["Україна"]}
{"title": "Middle\\Senior Backend Engineer ( Python)", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["Django", "Go", "Kafka", "GraphQL", "AI", "Docker", "JavaScript", "TypeScript", "Node.Js", "Git", "asyncio", "AWS", "Celery", "API", "Embers", "Python", "RabbitMQ", "Ansible"], "location": ["Україна"]}
{"title": "Python developer / strong junior", "company": "dZENcode", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["Django", "Go", "AI", "JavaScript", "SQL", "Git", "AWS", "API", "TensorFlow", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Senior / Lead Technical Support Developer", "company": "ApomSolutions", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "Java", "Kubernetes", "AI", "Docker", "OOP", "GCP", "Oracle", "Azure", "AWS", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer (with ML/AI  background)", "company": "Cyberspectr Solution", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["AI", "Docker", "PyTorch", "NumPy", "Scikit-learn", "Pandas", "Git", "AWS", "CI/CD", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "UKR.NET", "company_type": "Product", "salary": "$1000-4000", "technologies": ["NoSQL", "Go", "aiohttp", "AI", "PostgreSQL", "SQL", "Elasticsearch", "Elasctisearch", "asyncio", "MySQL", "MongoDB", "API", "Redis", "Python"], "location": ["Україна"]}
{"title": "Lead Python Developer", "company": "PYGIO", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Go", "Kubernetes", "AI", "Docker", "PostgreSQL", "SQL", "Django", "Python"], "location": ["Україна", "Албанія", "Вірменія", "Польща", "Чехія"]}
{"title": "Lead Back-End Engineer", "company": "Madgicx 🇺🇦", "company_type": "Product", "salary": null, "technologies": ["API", "Go", "Jenkins", "Docker", "PostgreSQL", "Flask", "SQL", "CI/CD", "Elasticsearch", "Pandas", "Git", "MySQL", "AWS", "Celery", "Django", "Redis", "Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "NestLogic", "company_type": "Product", "salary": null, "technologies": ["Go", "Kubernetes", "ML", "AI", "Docker", "Jupyter Notebook", "Python", "Linux"], "location": ["Україна"]}
{"title": "Sr Python Engineer", "company": "Zaly", "company_type": "Product", "salary": null, "technologies": ["Docker", "PostgreSQL", "SQL", "Highload", "Python", "Ansible"], "location": ["Україна", "Сполучені Штати"]}
{"title": "Full-stack (JS/Python) / Tech lead", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["API", "Go", "AI", "JavaScript", "GCP", "SQL", "MongoDB", "Git", "AWS", "Django", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python)  (Warsaw)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Go", "Mlops", "React", "ML", "AI", "OOP", "Node.Js", "AWS", "API", "TensorFlow", "Python"], "location": ["Польща"]}
{"title": "Full Stack Developer (Python,React) Miami location", "company": "Global Teams", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Django", "Go", "Jenkins", "React", "AI", "RESTful", "GCP", "Flask", "SQL", "PostgreSQL", "CI/CD", "Git", "MySQL", "MongoDB", "API", "Redux", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Develux", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Go", "GraphQL", "AI", "Docker", "Flask", "SQL", "PostgreSQL", "CI/CD", "Azure", "AWS", "API", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Python Developer for Training Neural Networks", "company": "Digifico", "company_type": "Product", "salary": null, "technologies": ["Go", "PyTorch", "SQL", "TensorFlow", "NoSQL", "Python", "Keras"], "location": ["Україна"]}
{"title": "Python Developer  (DCOS)", "company": "OSF Digital", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["Go", "React", "AI", "RESTful", "SQL", "Git", "Agile", "API", "Python"], "location": ["Польща", "Румунія", "Туреччина", "Україна"]}
{"title": "Python Tech Lead", "company": "Dataforest", "company_type": "Outsource", "salary": "$1000-4000", "technologies": ["Go", "Kafka", "Kubernetes", "AI", "Docker", "Airflow", "GCP", "Flask", "SQL", "Elasticsearch", "Pandas", "Redis", "Embers", "AWS", "Django", "NoSQL", "Python"], "location": ["Німеччина", "Польща", "Словаччина", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": "$3000-5500", "technologies": ["Django", "DevOps", "Go", "React", "AI", "Docker", "Vue.Js", "Flask", "Git", "Pyramid", "Angular", "API", "Python"], "location": ["Польща"]}
{"title": "Python Developer for Automotive Project", "company": "Luxoft", "company_type": "Outsource", "salary": "від $2000", "technologies": ["Django", "DevOps", "Go", "React", "AI", "Docker", "Vue.Js", "Flask", "Git", "Pyramid", "Angular", "API", "Python", "Ansible"], "location": ["Польща"]}
{"title": "Python/Django Developer", "company": "ECHOES", "company_type": "Product", "salary": "$800-2000", "technologies": ["Go", "Kubernetes", "GraphQL", "AI", "Docker", "PostgreSQL", "SQL", "Elasticsearch", "Nginx", "AWS", "Celery", "Django", "Redis", "Python", "RabbitMQ", "Linux"], "location": ["Грузія", "Україна"]}
{"title": "Python developer", "company": "Odore", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Go", "SQLAlchemy", "AI", "Postman", "PostgreSQL", "SQL", "Pytest", "Git", "AWS", "API", "Python"], "location": ["Велика Британія"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$4500-6000", "technologies": ["DevOps", "Apache", "Go", "AI", "OOP", "Airflow", "Flask", "CI/CD", "MongoDB", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Python Software Engineer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["NoSQL", "Go", "Kafka", "Spark", "AI", "Postgres", "OOP", "Flask", "SQL", "AWS", "API", "Redis", "FastAPI", "Python"], "location": ["Польща", "Словаччина", "Україна"]}
{"title": "Middle Python Developer", "company": "Starnavi", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "Foundation", "Go", "React", "Kubernetes", "AI", "Docker", "RESTful", "Flask", "SQL", "Embers", "Angular", "API", "NoSQL", "FastAPI", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python developer", "company": "Peppernode", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["API", "Go", "Microservices", "Kubernetes", "Docker", "Flask", "CI/CD", "Git", "AWS", "Django", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "strong Python over Django dev", "company": "Flexyti", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["Go", "Kubernetes", "AI", "OOP", "Docker", "PostgreSQL", "SQL", "CI/CD", "MongoDB", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Django)", "company": "Flexyti", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Go", "Kubernetes", "AI", "Docker", "PostgreSQL", "SQL", "CI/CD", "MongoDB", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["API", "Go", "Senior", "CSS", "ML", "HTML", "RESTful", "JavaScript", "Flask", "SQL", "Git", "MySQL", "AWS", "Django", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Parsing expert for a long term partnership", "company": "WebDev 247", "company_type": "Product", "salary": "до $2500", "technologies": ["CSS", "ML", "AI", "HTML", "JavaScript", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python developer (AWS)", "company": "TemaBit Fozzy Group", "company_type": "Product", "salary": null, "technologies": ["AI", "OOP", "CI/CD", "SQL", "Git", "AWS", "API", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Competera", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Spark", "Go", "Kafka", "Apache", "AI", "Airflow", "GCP", "SQL", "Click", "Luigi", "Python"], "location": ["Кіпр", "Україна"]}
{"title": "Middle Python Developer (Django Framework)", "company": "NeoFin", "company_type": "Product", "salary": "$2000", "technologies": ["Go", "CSS", "ML", "JavaScript", "Git", "MySQL", "RESTful", "Flask", "PostgreSQL", "Node.Js", "Finance", "Redis", "OpenCV", "React", "AI", "HTML", "Vue.Js", "SQL", "API", "Elasticsearch", "Django", "Python"], "location": ["Малайзія", "Польща", "Україна"]}
{"title": "Senior Python Developer (Data Engineering Focus)", "company": "HRForecast", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "Kafka", "AI", "RESTful", "Flask", "SQL", "PostgreSQL", "NumPy", "Pandas", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Solidity/Blockchain expert (Smart Contract)", "company": "WeSoftYou", "company_type": "Outsource", "salary": null, "technologies": ["React", "AI", "OOP", "Git", "Solidity", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "P2H", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "CSS", "ML", "Git", "MySQL", "jQuery", "Kubernetes", "PostgreSQL", "Node.Js", "Redis", "React", "AI", "HTML", "Vue.Js", "SQL", "Embers", "Bootstrap", "API", "Redux", "RabbitMQ", "PHP", "Elasticsearch", "Angular", "Python"], "location": ["Україна"]}
{"title": "Experienced Odoo Developer", "company": "hts-experts.com", "company_type": "Product", "salary": "$600-3500", "technologies": ["Go", "Requests", "CSS", "ML", "AI", "HTML", "JavaScript", "PostgreSQL", "SQL", "Odoo", "Git", "Embers", "Python", "Troubleshooting", "Linux"], "location": ["Швейцарія"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Go", "React", "CSS", "AI", "JavaScript", "Flask", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python) (Poland)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2000", "technologies": ["DevOps", "Mlops", "React", "ML", "AI", "OOP", "Node.Js", "AWS", "API", "TensorFlow", "Python"], "location": ["Ізраїль", "Польща"]}
{"title": "Python Backend розробник", "company": "Sk-Telemed", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Django", "Go", "AI", "Docker", "PostgreSQL", "SQL", "Virtualenv", "Git", "AWS", "Celery", "Pyenv", "Redis", "Python", "RabbitMQ", "Linux"], "location": ["Україна"]}
{"title": "Python developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Go", "CSS", "ML", "HTML", "Docker", "OOP", "PostgreSQL", "SQL", "Redis", "jQuery", "API", "NoSQL", "Python", "Linux"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Idenon", "company_type": "Product", "salary": "$1000-4000", "technologies": ["Go", "aiohttp", "Tornado", "Kubernetes", "AI", "Docker", "AWS", "CI/CD", "Redis", "Python", "RabbitMQ"], "location": ["Словаччина", "Україна"]}
{"title": "Python Developer", "company": "AUTODOC", "company_type": "Product", "salary": "$1200-2500", "technologies": ["DevOps", "Go", "ML", "AI", "Streamlit", "API", "Python"], "location": ["Молдова", "Польща", "Португалія", "Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "Apache", "Go", "AI", "OOP", "Airflow", "Flask", "CI/CD", "MongoDB", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Backend Python/Django Developer for a SaaS Product", "company": "Iteksas", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Go", "CSS", "Saas", "ML", "HTML", "Product", "SQL", "Celery", "Django", "NoSQL", "Python"], "location": ["Литва", "Україна"]}
{"title": "AI Enthusiast / Machine Learning", "company": "King's Choice", "company_type": "Product", "salary": "$1000-4000", "technologies": ["AI", "Chatgpt", "GPT", "Python"], "location": ["Україна"]}
{"title": "Middle Python+Java Developer IRC183577", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["Java", "Go", "AI", "RESTful", "SQL", "Git", "AWS", "API", "NoSQL", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "4K-Soft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Docker", "OOP", "SQL", "Mondodb", "Git", "MySQL", "MongoDB", "Python"], "location": ["Україна"]}
{"title": "LLM developer", "company": "SerenityGPT", "company_type": "Product", "salary": null, "technologies": ["AI", "Nlp", "Go", "GPT"], "location": ["Велика Британія"]}
{"title": "Middle/Senior Python Software Developer (or switcher from another OOP language)", "company": "Jito.dev", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Go", "Kubernetes", "Gis", "OOP", "AI", "PostgreSQL", "SQL", "Git", "AWS", "CI/CD", "Python", "Linux"], "location": ["Україна"]}
{"title": "Strong Junior Backend Python Developer", "company": "DevIT Group", "company_type": "Outsource", "salary": "$900-1500", "technologies": ["API", "Go", "AI", "Docker", "SQL", "Langchain", "Azure", "Git", "AWS", "Django", "Redis", "FastAPI", "Python", "RabbitMQ", "Linux"], "location": ["Україна"]}
{"title": "QA Engineer (Performance testing)", "company": "SeekIT", "company_type": "Outsource", "salary": null, "technologies": ["Java", "Jenkins", "ML", "AI", "JavaScript", "CI/CD", "SQL", "Elasticsearch", "API", "Python"], "location": ["Латвія"]}
{"title": "Senior Python Engineer", "company": "KnubiSoft", "company_type": "Outsource", "salary": "$2000-4000", "technologies": ["API", "Go", "CSS", "GraphQL", "AI", "OOP", "Embers", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Moment", "Go", "AI", "Click", "Embers", "API"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer", "company": "teeko.", "company_type": "Product", "salary": "до $2000", "technologies": ["Go", "GraphQL", "PostgreSQL", "SQL", "API", "FastAPI", "Python"], "location": ["Україна", "Ізраїль"]}
{"title": "Python Developer", "company": "Ava Technologies Inc.", "company_type": "Product", "salary": null, "technologies": ["Go", "AI", "MongoDB", "Embers", "AWS", "GPT", "Serverless", "Python"], "location": ["Чехія", "Нідерланди"]}
{"title": "Python Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$5000-7000", "technologies": ["Foundation", "Go", "CSS", "Kubernetes", "ML", "AI", "Docker", "RESTful", "HTML", "JavaScript", "Git", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Quality Assurance Architect (Networking)", "company": "PLVision", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Automation", "Networking", "Kubernetes", "AI", "Docker", "CI/CD", "Unittest", "Ansible", "Architect", "Pytest", "Robot Framework", "Embers", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Team Lead Python", "company": "Capital Recruiters", "company_type": "Product", "salary": null, "technologies": ["API", "React", "Flask", "SQL", "Django", "Python"], "location": ["Україна"]}
{"title": "Software Python Developer", "company": "Capital Recruiters", "company_type": "Product", "salary": null, "technologies": ["API", "React", "Flask", "SQL", "Django", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": "$3000-4200", "technologies": ["DevOps", "AI", "Python"], "location": ["Україна"]}
{"title": "Python/Django Full Stack Developer", "company": "BikeBUBL", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Go", "Js", "AI", "Vue.Js", "PostgreSQL", "SQL", "Python", "Vue", "Django", "Frontend"], "location": ["Велика Британія", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Matplotlib", "Plotly", "SQL", "NumPy", "Pandas", "Embers", "Dash", "Python"], "location": ["Польща"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Crossplatform", "AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Animo", "company_type": "Product", "salary": "від $5000", "technologies": ["Django", "Go", "AI", "Node.Js", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Bluefield Technologies", "company_type": "Product", "salary": "$5000-6000", "technologies": ["Go", "CSS", "ML", "Docker", "Git", "aiohttp", "Ccna", "Networking", "RESTful", "TypeScript", "Backbone", "React", "AI", "HTML", "SQL", "Pandas", "asyncio", "API", "Linux", "Python"], "location": ["Словаччина", "Україна"]}
{"title": "Python Engineer", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $9000", "technologies": ["Go", "Kubernetes", "AI", "Docker", "GCP", "CI/CD", "Azure", "AWS", "API", "Python", "Ansible"], "location": ["Україна"]}
{"title": "Python/GoLang developer (Europe)", "company": "TEAM International", "company_type": "Outstaff", "salary": null, "technologies": ["Django", "Foundation", "Go", "Kubernetes", "AI", "GCP", "SQL", "API", "NoSQL", "Python"], "location": ["Польща", "Португалія"]}
{"title": "Python Engineer", "company": "APOSTERA UA HARMAN", "company_type": "Product", "salary": "від $3000", "technologies": ["DevOps", "Automotive", "Automation", "Senior", "ML", "AI", "Docker", "Middle", "Git", "API", "Python", "Linux"], "location": ["Угорщина", "Польща", "Україна"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["DevOps", "Go", "React", "Kubernetes", "GraphQL", "AI", "OOP", "Docker", "Git", "Embers", "API", "Python"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Corsound AI - Senior Algorithms Developer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["Go", "Algorithms", "AI", "PyTorch", "Embers", "API", "TensorFlow", "Python"], "location": ["Україна", "Грузія"]}
{"title": "Senior/Lead Python Engineer with Data skills", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Spark", "Go", "AI", "OOP", "SQL", "AWS", "Python"], "location": ["Україна"]}
{"title": "Senior Algorithms Developer (Speech Recognition, Python)", "company": "SD Solutions", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Go", "ML", "AI", "PyTorch", "Embers", "API", "TensorFlow", "Python"], "location": ["Кіпр", "Грузія", "Польща", "Україна"]}
{"title": "Senior Data Scientist for the oil and gas industry", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Go", "NumPy", "SQL", "Scikit-learn", "Pandas", "Azure", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Senior Data Scientist for the oil and gas data prediction solutions", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "NumPy", "SQL", "Scikit-learn", "Pandas", "Azure", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "Mobilunity", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Requests", "AI", "Fairplay", "Azure", "AWS", "Dash", "API", "Playready", "Python"], "location": ["Україна"]}
{"title": "Algorithm Developer for Corsound AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$1000-4000", "technologies": ["Go", "Algorithms", "AI", "PyTorch", "Embers", "API", "TensorFlow", "Python"], "location": ["Грузія", "Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "InventorSoft", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "SQL", "MySQL", "API", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Python developer (US IoT project)", "company": "Romen Personnel", "company_type": "Product", "salary": "$1000-2500", "technologies": ["AI", "OOP", "PHP", "SQL", "AWS", "Iot", "Python"], "location": ["Сполучені Штати"]}
{"title": "Senior Full-stack Developer with ML experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Ocr", "ML", "AI", "Node.Js", "AWS", "Angular", "Python"], "location": ["Естонія", "Польща", "Україна"]}
{"title": "Middle/Senior BackEnd developer Python/Django", "company": "Meest China", "company_type": "Product", "salary": null, "technologies": ["Django", "Go", "Jenkins", "JWT", "AI", "RESTful", "Wagtail", "SQL", "Git", "MySQL", "AWS", "Celery", "API", "Nginx", "Redis", "Python"], "location": ["Україна"]}
{"title": "Senior Cloud Developer", "company": "Alcor", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Cloud", "AI", "Vue.Js", "JavaScript", "SQL", "AWS", "API", "NoSQL", "Python"], "location": ["Чехія", "Польща", "Румунія", "Словаччина", "Україна"]}
{"title": "Python Developer for EdTech company", "company": "Projector", "company_type": "Product", "salary": null, "technologies": ["AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python  Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["Go", "ML", "AI", "OOP", "Git", "Python"], "location": ["Португалія"]}
{"title": "Strong Junior / Middle Python Developer", "company": "DATAWIZ", "company_type": "Product", "salary": null, "technologies": ["Orm", "Go", "CSS", "ML", "Docker", "Git", "MySQL", "PostgreSQL", "Webpack", "Celery", "Redis", "React", "AI", "HTML", "SQL", "Pandas", "API", "RabbitMQ", "Linux", "OOP", "Angular", "Django", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Intsurfing", "company_type": "Outstaff", "salary": "$2500-4000", "technologies": ["ML", "AI", "SQL", "Azure", "AWS", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "level99.vip", "company_type": "Product", "salary": null, "technologies": ["ML", "Docker", "Postman", "Git", "Nginx", "Kubernetes", "SQLAlchemy", "GraphQL", "NoSQL", "Apache", "Kafka", "Requests", "AI", "HTML", "SQL", "API", "RabbitMQ", "Selenium", "Python"], "location": ["Україна"]}
{"title": "Python\\Django Backend Developer", "company": "Animo", "company_type": "Outsource", "salary": "до $5500", "technologies": ["API", "Go", "AI", "SQL", "Node.Js", "Backend", "Remote", "AWS", "Django", "Python"], "location": ["Україна"]}
{"title": "Python Back-End Engineer", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["Kubernetes", "ML", "AI", "GCP", "Azure", "AWS", "CI/CD", "Redis", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Unidatalab", "company_type": "Product", "salary": "$2500-3700", "technologies": ["API", "Go", "Kafka", "Kubernetes", "AI", "Docker", "GCP", "SQL", "Azure", "Git", "AWS", "Django", "GPT", "NoSQL", "FastAPI", "Python"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer (Prom.ua)", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["Go", "CSS", "Docker", "JavaScript", "Git", "CI/CD", "Kubernetes", "PostgreSQL", "Webpack", "MongoDB", "Redis", "Kafka", "React", "SQL", "API", "RabbitMQ", "Click", "Elasticsearch", "Python"], "location": ["Україна"]}
{"title": "Senior Appian Developer", "company": "DICEUS", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Go", "Appian", "AI", "JavaScript", "SQL", "Sail", "Git", "Embers", "API"], "location": ["Йорданія", "Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Jenkins", "Flux", "AI", "Docker", "GCP", "Azure", "Git", "AWS", "MongoDB", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["Moment", "Spark", "Go", "Apache", "AI", "Airflow", "PostgreSQL", "SQL", "Git", "MySQL", "AWS", "MongoDB", "CI/CD", "Redis", "Python"], "location": ["Румунія"]}
{"title": "Senior Python/DevOps Developer", "company": "Chrysalis Gate", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "Spark", "Kafka", "Moment", "React", "AI", "Git", "AWS", "API", "Redis", "Python"], "location": ["Литва", "Україна", "Польща", "Словаччина", "Румунія"]}
{"title": "Python Developer/Data Engineer", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["OpenCV", "ML", "AI", "PyTorch", "NumPy", "Pandas", "Git", "AWS", "TensorFlow", "Python"], "location": ["Україна"]}
{"title": "Odoo Engineer", "company": "OpsWay", "company_type": "Outsource", "salary": null, "technologies": ["Xml", "JavaScript", "PostgreSQL", "Odoo", "Owl", "Python"], "location": ["Україна"]}
{"title": "Middle Backend Developer", "company": "Partner-way", "company_type": "Product", "salary": null, "technologies": ["Requests", "Go", "JavaScript", "TypeScript", "API", "Python"], "location": ["Велика Британія", "Сполучені Штати", "Україна", "Німеччина", "Польща"]}
{"title": "Python Developer", "company": "SKILLUP", "company_type": "Product", "salary": null, "technologies": ["Go", "CSS", "ML", "AI", "HTML", "SQL", "Django", "Python"], "location": ["Україна"]}
{"title": "Програміст на Django 1.9.0", "company": "GlutenOff.ua", "company_type": "Product", "salary": null, "technologies": ["Go", "ML", "HTML", "Docker", "JavaScript", "PostgreSQL", "SQL", "Nginx", "Django", "Python", "Gulp"], "location": ["Україна"]}
{"title": "Senior Software Engineer (DataDiscovery)", "company": "MEGOGO", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Spark", "Go", "Kafka", "Apache", "Kubernetes", "OOP", "Docker", "PostgreSQL", "SQL", "Click", "MongoDB", "MySQL", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python (Back-end) Developer", "company": "Animo", "company_type": "Outsource", "salary": "від $5000", "technologies": ["API", "Go", "AI", "Apis", "Node.Js", "AWS", "Django", "English", "Python"], "location": ["Україна"]}
{"title": "Python Developer (Data-driven)", "company": "TechbrainJobs", "company_type": "Product", "salary": "$6000-8000", "technologies": ["Go", "AI", "Docker", "CI/CD", "SQL", "Git", "AWS", "API", "Python", "Linux"], "location": ["Ізраїль"]}
{"title": "Senior Full-stack Developer with OCR experience", "company": "8allocate", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Go", "Ocr", "ML", "AI", "Node.Js", "AWS", "Angular", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer for Neolithics AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["Go", "Kubernetes", "ML", "AI", "GCP", "Azure", "AWS", "CI/CD", "Redis", "Python"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$4000-5500", "technologies": ["DevOps", "ML", "PyTorch", "API", "Python"], "location": ["Україна"]}
{"title": "Tech/Team Lead (Python)", "company": "Indigo Tech recruitment", "company_type": "Product", "salary": null, "technologies": ["Go", "ML", "AI", "PyTorch", "PostgreSQL", "SQL", "Pandas", "AWS", "API", "FastAPI", "Python"], "location": ["Франція"]}
{"title": "Middle+/Senior Python developer", "company": "TechbrainJobs", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Drf", "Go", "AI", "PostgreSQL", "SQL", "Angular", "Elasticsearch", "Redis", "Git", "Nginx", "Celery", "Django", "aiohttp", "Python", "Mongo"], "location": ["Україна"]}
{"title": "Python/Golang Developer (Hospitality industry)", "company": "Coherent Solutions", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["API", "Foundation", "Go", "Kubernetes", "AI", "Golang", "SQL", "Django", "NoSQL", "Python"], "location": ["Польща", "Грузія", "Литва", "Болгарія", "Румунія"]}
{"title": "Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Go", "React", "AI", "Docker", "OOP", "Airflow", "PostgreSQL", "SQL", "Node.Js", "Pandas", "Embers", "Celery", "Django", "Redis", "Python", "RabbitMQ"], "location": ["Польща", "Україна"]}
{"title": "Junior Python Developer (Scraping) for AI Software Product", "company": "Simporter", "company_type": "Product", "salary": "$600-1200", "technologies": ["Go", "AI", "RESTful", "Airflow", "SQL", "Elasticsearch", "API", "NoSQL", "Python", "RabbitMQ", "Scrapy"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Quickstaffing LLC", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "Go", "Jupyter Notebook", "AI", "SQL", "Pandas", "Python"], "location": ["Вірменія"]}
{"title": "Middle Python Developer", "company": "SoftVision", "company_type": "Outsource", "salary": null, "technologies": ["Django", "Spark", "Go", "Apache", "Kubernetes", "AI", "Docker", "Flask", "SQL", "PostgreSQL", "Git", "MySQL", "AWS", "API", "Python"], "location": ["Україна"]}
{"title": "Mid-Senior Python developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "$2500-4000", "technologies": ["AI", "API", "Go", "Python"], "location": ["Польща"]}
{"title": "Middle/Senior Python/Go Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": "до $3000", "technologies": ["Go", "ML", "AI", "JavaScript", "Git", "API", "Python"], "location": ["Польща", "Сербія", "Португалія"]}
{"title": "Senior Back-end Python Engineer", "company": "Particles Global", "company_type": "Product", "salary": "$2000-4000", "technologies": ["Moment", "Go", "Kubernetes", "AI", "OOP", "Docker", "PostgreSQL", "SQL", "Unix", "API", "Python", "Linux"], "location": ["Україна"]}
{"title": "Data Engineer", "company": "Websmile", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Jenkins", "ML", "AI", "Docker", "Airflow", "Flask", "Git", "AWS", "Django", "Linux"], "location": ["Ізраїль", "Україна"]}
{"title": "Python backend Developer", "company": "Yanpix", "company_type": "Product", "salary": "$3000-4200", "technologies": ["DevOps", "Go", "Flask", "SQL", "PostgreSQL", "Git", "MySQL", "MongoDB", "Django", "Python"], "location": ["Україна", "Словаччина", "Польща", "Чехія"]}
{"title": "Full Stack Software Engineer", "company": "Seatpick", "company_type": "Product", "salary": "від $2000", "technologies": ["Django", "Go", "ML", "AI", "Docker", "JavaScript", "TypeScript", "AWS", "API"], "location": ["Україна"]}
{"title": "Senior Full-Stack Developer/ AI Evangelist", "company": "Softengi", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["DevOps", "React", "ML", "AI", "Copilot", "JavaScript", "Chatgpt", "Azure", "Git", "AWS", "Angular", "CI/CD", "GPT", "Python"], "location": ["Чехія", "Литва", "Латвія", "Польща", "Україна"]}
{"title": "Senior Full-Stack Engineer Python/React - UKRAINE or SPAIN", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Spark", "Go", "React", "SQLAlchemy", "AI", "Docker", "TypeScript", "Flask", "SQL", "Pandas", "Dask", "Azure", "Embers", "Celery", "PySpark", "Python", "D3"], "location": ["Україна", "Іспанія"]}
{"title": "Senior Python Full-stack Software Engineer", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Jenkins", "AI", "JavaScript", "TypeScript", "AWS", "CI/CD", "Python"], "location": ["Україна"]}
{"title": "Middle Developer (Python/Django) in product", "company": "Graintrack", "company_type": "Product", "salary": null, "technologies": ["API", "Go", "Saas", "AI", "Docker", "RESTful", "PostgreSQL", "SQL", "CI/CD", "Django", "Redis", "Python"], "location": ["Україна"]}
{"title": "Python Full Stack Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Foundation", "Go", "React", "CSS", "ML", "AI", "HTML", "PHP", "TypeScript", "SQL", "Click", "Node.Js", "Git", "MySQL", "Angular", "Python", "Linux"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": null, "technologies": ["DevOps", "ML", "OOP", "PyTorch", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Super Dispatch", "company_type": "Product", "salary": "$5000-6500", "technologies": ["Ddd", "API", "Go", "Kubernetes", "AI", "GCP", "CI/CD", "AWS", "Django", "Python"], "location": ["Узбекистан"]}
{"title": "Python developer", "company": "Flyaps", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Go", "CSS", "AI", "JavaScript", "CI/CD", "SQL", "Git", "Django", "Python", "Linux"], "location": ["Україна"]}
