{"title": "Python Developer", "company": "Kozak Group", "company_type": "Outstaff", "salary": "до $2800", "technologies": ["SQL", "API", "Python", "Es", "Redis", "AWS", "JavaScript", "AI", "MySQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "ANDROMEDA Systems", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Go", "DevOps", "Git", "Pandas", "Python", "Django", "AWS", "AI"], "location": ["Україна"]}
{"title": "Python/Django Engineer", "company": "Intobi", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Python", "Django", "AI", "Docker"], "location": ["Україна"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Git", "Python", "Django", "AI"], "location": ["Україна"]}
{"title": "Software Engineer (Python) (G)", "company": "Freelance", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Bigdata", "Spark", "Git", "DevOps", "MongoDB", "SQL", "CI/CD", "Python", "Redis", "AWS", "PostgreSQL", "AI", "Airflow", "Moment", "MySQL", "Apache"], "location": ["Румунія"]}
{"title": "Python Developer", "company": "EvaCodes", "company_type": "Outstaff", "salary": "$2500-3700", "technologies": ["Go", "AI", "Python"], "location": ["Україна"]}
{"title": "Principal/Associate Director Software Engineer", "company": "Skillreveal", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Java", "Agile", "SQL", "Python", "API", "Kubernetes", "Embers", "AWS", "SQLAlchemy", "AI", "React"], "location": ["Польща"]}
{"title": "Senior Python Backend Developer", "company": "Forte Group", "company_type": "Outsource", "salary": null, "technologies": ["GraphQL", "Git", "Pandas", "PHP", "Node.Js", "Elasticsearch", "Python", "API", "OOP", "AWS", "JavaScript", "AI", "React"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "FreySoft", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "Flask", "MongoDB", "API", "Python", "OOP", "AI", "RESTful"], "location": ["Україна", "Польща"]}
{"title": "Senior Python with Cloud Certificate", "company": "Skillreveal", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["Go", "Spark", "Azure", "Kafka", "API", "Python", "Redis", "AWS", "AI", "React", "Terraform"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FreySoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "MongoDB", "API", "Python", "OOP", "AI", "RESTful"], "location": ["Польща", "Україна"]}
{"title": "Middle Python Engineer", "company": "GoIT", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Git", "DevOps", "Azure", "Kubernetes", "Python", "Django", "AWS", "AI"], "location": ["Польща"]}
{"title": "Python Developer (AdTech location technology leader)", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Spark", "SQL", "Python", "OOP", "AWS", "AI", "Hadoop"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Kubernetes", "API", "Python", "AWS", "AI", "Docker"], "location": ["Польща", "Україна"]}
{"title": "Python developer", "company": "Lineup", "company_type": "Outsource", "salary": "до $2800", "technologies": ["SQL", "API", "Python", "Redis", "AWS", "MySQL"], "location": ["Україна"]}
{"title": "Str.Middle/Senior Python Architect 2037/03", "company": "Argument", "company_type": "Outstaff", "salary": "до $5000", "technologies": ["Go", "SQL", "Python", "AI", "PostgreSQL", "Pyramid", "Postgres"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Web Developer for an energy efficiency project", "company": "Latrock", "company_type": "Product", "salary": "$2700-3500", "technologies": ["Go", "Flask", "ML", "HTML", "CSS", "SQL", "API", "Python", "Django", "AI"], "location": ["Німеччина"]}
{"title": "Middle+ Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Flask", "GraphQL", "NoSQL", "ML", "SQL", "CI/CD", "API", "Python", "Django", "AWS", "GCP", "PostgreSQL", "AI", "Docker", "FastAPI"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Flask", "Git", "SQL", "API", "Python", "OOP", "AI", "Dash", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python + Scala Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Go", "RESTful", "SQL", "API", "Python", "Embers", "AI", "PostgreSQL", "Scala"], "location": ["Польща"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Go", "ML", "HTML", "CSS", "SQL", "API", "Python", "Embers", "AI", "React", "PostgreSQL", "JavaScript", "RESTful"], "location": ["Польща"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Product", "salary": null, "technologies": ["Flask", "Git", "SQL", "API", "Python", "OOP", "AI", "Dash", "FastAPI"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Flask", "Git", "SQL", "API", "Python", "OOP", "AI", "Dash", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "TechMagic", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Go", "Angular", "DevOps", "SQL", "CI/CD", "Node.Js", "API", "Python", "OOP", "Selenium", "Django", "AWS", "PostgreSQL", "JavaScript", "AI", "React"], "location": ["Україна"]}
{"title": "Tech Lead (Python/Django/JS)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "AI", "Python", "Embers"], "location": ["Україна"]}
{"title": "Software Engineer", "company": "incoalliance", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Spark", "Git", "Pandas", "Elasticsearch", "Kubernetes", "Python", "OOP", "Microservices", "API", "Redis", "AI", "Jenkins", "Airflow", "TensorFlow", "Docker"], "location": ["Україна"]}
{"title": "Full Stack Engineer (Python/React)", "company": "Fluvius", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Requests", "SQL", "API", "Python", "Django", "AWS", "React", "JavaScript", "AI", "TypeScript", "MySQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Vimmi Communications", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Go", "Flask", "Linux", "NoSQL", "MongoDB", "Tornado", "SQL", "Vim", "API", "Python", "OOP", "Kubernetes", "FastAPI", "Django", "AI", "aiohttp", "RESTful"], "location": ["Україна"]}
{"title": "Robotics Advanced Automation Engineer", "company": "SoftServe", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Codesys", "API", "Ros", "Python", "AWS", "AI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Intobi", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Python"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "PLANEKS", "company_type": "Outstaff", "salary": "$2500-3700", "technologies": ["Go", "API", "Python", "Django", "AI", "Celery", "FastAPI"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "SPS Commerce", "company_type": "Product", "salary": null, "technologies": ["DevOps", "CI/CD", "Kubernetes", "API", "Python", "Embers", "AWS", "AI", "Docker"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "CodeIT", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Go", "Linux", "Git", "DevOps", "Ansible", "SQL", "CI/CD", "Python", "API", "Embers", "Django", "AI", "PostgreSQL", "Docker"], "location": ["Україна"]}
{"title": "Python (Django) Developer", "company": "IvorySoft", "company_type": "Outsource", "salary": null, "technologies": ["Django", "AI", "Go", "Python"], "location": ["Україна"]}
{"title": "Backend Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$3500-4500", "technologies": ["Go", "Foundation", "Git", "ML", "CSS", "HTML", "Kubernetes", "API", "Python", "AWS", "JavaScript", "AI", "Docker", "RESTful"], "location": ["Україна"]}
{"title": "Django developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "API", "Python", "Django", "AI", "Celery", "FastAPI"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Pandas", "SQL", "Node.Js", "Python", "OOP", "Redis", "Embers", "Django", "AI", "PostgreSQL", "Airflow", "React", "Celery", "Docker", "RabbitMQ"], "location": ["Україна", "Польща", "Вірменія"]}
{"title": "Django Developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "API", "Python", "Django", "AI", "Celery", "FastAPI"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Temy", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Go", "GraphQL", "SQL", "API", "Python", "Django", "PostgreSQL", "React"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Flask", "Git", "SQL", "API", "Python", "OOP", "AI", "Dash", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": "$3000-6000", "technologies": ["Go", "Angular", "Git", "API", "Python", "FastAPI", "asyncio", "Embers", "AI", "GCP", "React", "RESTful"], "location": ["Польща", "Хорватія", "Словаччина"]}
{"title": "Back-end Developer (experience with GPT API)", "company": "TechHunt", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Git", "Node.Js", "API", "Python", "AI"], "location": ["Україна"]}
{"title": "Quantitative Analyst", "company": "Weem", "company_type": "Product", "salary": "$2500-3700", "technologies": ["Perl", "SQL", "Python", "Phyton"], "location": ["Канада"]}
{"title": "Senior Python Developer/DevOps Engineer", "company": "Powercode", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Go", "Kibana", "DevOps", "Git", "CI/CD", "Azure", "Elasticsearch", "Kubernetes", "Python", "AI", "Dash"], "location": ["Німеччина", "Польща", "Україна"]}
{"title": "Middle Python developer", "company": "Blackthorn Vision", "company_type": "Outsource", "salary": "до $5000", "technologies": ["Angular", "Git", "Azure", "Django", "React", "Go", "SQL", "Node.Js", "Python", "AWS", "JavaScript", "TypeScript", "Linux", "ML", "HTML", "Pandas", "CSS", "API", "AI", "NumPy", "Github", "Flask", "Scipy", "Black"], "location": ["Україна"]}
{"title": "Middle Python+Node.JS Engineer", "company": "A-Team Global", "company_type": "Outsource", "salary": null, "technologies": ["Go", "ML", "HTML", "CSS", "Node.Js", "Python", "Embers", "AI"], "location": ["Болгарія", "Німеччина", "Україна"]}
{"title": "Python Developer (Django)", "company": "IT Svit", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "Git", "MongoDB", "DevOps", "Kafka", "SQL", "Elasticsearch", "Python", "API", "jQuery", "Django", "AI", "PostgreSQL", "React", "TensorFlow", "Docker", "Keycloak"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Orderry", "company_type": "Product", "salary": null, "technologies": ["Django", "aiohttp", "React", "RabbitMQ", "Go", "SQL", "Python", "Pytest", "Redux", "asyncio", "Redis", "AI", "Celery", "Docker", "Kafka", "Kubernetes", "Selenium", "PostgreSQL", "Webpack"], "location": ["Україна"]}
{"title": "Python Developer", "company": "IT Svit", "company_type": "Outsource", "salary": null, "technologies": ["Git", "MongoDB", "jQuery", "Elasticsearch", "Django", "React", "Go", "SQL", "Python", "Microservices", "TensorFlow", "DevOps", "ML", "API", "AI", "Docker", "Rest", "Kafka", "PostgreSQL"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "EVE.calls", "company_type": "Product", "salary": "$4000", "technologies": ["Grpc", "Unix", "Python", "Websockets", "TensorFlow"], "location": ["Україна"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Go", "ML", "HTML", "CSS", "SQL", "API", "Python", "Embers", "AI", "React", "PostgreSQL", "JavaScript", "RESTful"], "location": ["Польща"]}
{"title": "Lead Python Engineer  (challenging omnichannel payment processing solution for Europe and North America)", "company": "Godel Technologies", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Git", "DevOps", "Azure", "SQL", "CI/CD", "API", "Python", "AWS", "GCP", "PostgreSQL", "AI", "Docker", "FastAPI", "MySQL"], "location": ["Польща", "Литва", "Болгарія"]}
{"title": "Python developer", "company": "Uptarget", "company_type": "Product", "salary": "від $3000", "technologies": ["Go", "CI/CD", "Kafka", "Kubernetes", "Python", "AI", "Docker"], "location": ["Україна"]}
{"title": "Odoo Senior Developer", "company": "Mongrov", "company_type": "Product", "salary": "$3500-4500", "technologies": ["Go", "ML", "API", "AI", "Odoo"], "location": ["Колумбія", "Польща", "Україна"]}
{"title": "Full-Stack Python Developer (with Angular)", "company": "Virtuace", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Go", "Angular", "Git", "MongoDB", "ML", "Azure", "CI/CD", "Pandas", "Kubernetes", "API", "Python", "AI", "NumPy", "Docker", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer (experience in ML projects using Python)", "company": "ISRAEL IT", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Spark", "Git", "ML", "CI/CD", "API", "OOP", "Python", "English", "Kubernetes", "Embers", "AWS", "AI", "Docker"], "location": ["Україна"]}
{"title": "Intelligent Automation Full Stack  Developer - Open A.I. and No Code A.I. is a plus", "company": "Mentally", "company_type": "Product", "salary": "$2500-3700", "technologies": ["Go", "Git", "Saas", "DevOps", "Azure", "ML", "Python", "AWS", "AI", "Docker", "Automation"], "location": ["Італія"]}
{"title": "Senior Python/Django Engineer", "company": "at Apexive", "company_type": "Agency", "salary": "від $3000", "technologies": ["Go", "SQL", "Kubernetes", "Python", "Django", "AWS", "AI", "React", "Docker", "RESTful", "MySQL"], "location": ["Чехія", "Нідерланди", "Польща", "Україна"]}
{"title": "Python Developer", "company": "GEO Pay", "company_type": "Product", "salary": null, "technologies": ["Go", "SQL", "Azure", "Python", "API", "Redis", "Django", "AWS", "PostgreSQL", "AI", "Celery", "Foundation", "Drf"], "location": ["Україна"]}
{"title": "Strong Python Developer", "company": "NGM Agency", "company_type": "Product", "salary": null, "technologies": ["Go", "Puppet", "Linux", "Git", "ML", "CSS", "SQL", "HTML", "PHP", "API", "Python", "OOP", "Django", "AI", "PostgreSQL", "JavaScript", "Docker", "MySQL"], "location": ["Україна"]}
{"title": "Senior Python Developer (with ML/AI  background)", "company": "Cyberspectr Solution", "company_type": "Outstaff", "salary": null, "technologies": ["PyTorch", "Git", "Pandas", "CI/CD", "Scikit-learn", "Python", "AWS", "AI", "NumPy", "TensorFlow", "Docker"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "DTEK", "company_type": "Product", "salary": null, "technologies": ["Go", "Java", "Linux", "NoSQL", "MongoDB", "SQL", "API", "Python", "Redis", "Embers", "AI", "PostgreSQL", "JavaScript", "React", "MySQL"], "location": ["Україна"]}
{"title": "Python developer", "company": "NestLogic", "company_type": "Product", "salary": null, "technologies": ["Go", "Linux", "ML", "Jupyter Notebook", "Kubernetes", "Python", "AI", "Docker"], "location": ["Україна"]}
{"title": "Odoo/Python Developer", "company": "Sentrium", "company_type": "Product", "salary": null, "technologies": ["Go", "Flask", "Linux", "MongoDB", "Git", "SQL", "Python", "API", "Django", "AI", "PostgreSQL", "RESTful", "Odoo"], "location": ["Україна"]}
{"title": "Middle\\Senior Backend Engineer ( Python)", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["Go", "GraphQL", "Git", "Ansible", "Kafka", "Node.Js", "API", "Python", "asyncio", "Embers", "Django", "AWS", "JavaScript", "AI", "Celery", "Docker", "TypeScript", "RabbitMQ"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["Linux", "Git", "ML", "CSS", "SQL", "HTML", "API", "Python"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FoxmindEd", "company_type": "Product", "salary": "$2700-3500", "technologies": ["Go", "Flask", "Linux", "Git", "ML", "CSS", "SQL", "HTML", "Python", "OOP", "Django", "AWS", "SQLAlchemy", "PostgreSQL", "JavaScript", "Docker", "MySQL"], "location": ["Україна"]}
{"title": "Strong Middle / Senior Python Developer", "company": "TECHIIA Holding", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Scrum", "Go", "Angular", "DevOps", "SQL", "CI/CD", "Elasticsearch", "Python", "API", "Redis", "Django", "AI", "PostgreSQL", "Celery", "Black"], "location": ["Україна"]}
{"title": "Full-Stack Python Engineer", "company": "MEV", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["Go", "DevOps", "ML", "SQL", "CI/CD", "API", "Python", "Redis", "Django", "AWS", "Jenkins", "AI", "React", "Celery", "Docker"], "location": ["Україна"]}
{"title": "FullStack developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Angular", "MongoDB", "ML", "CSS", "SQL", "HTML", "jQuery", "Python", "Django", "AI", "PostgreSQL", "JavaScript", "React", "Apache"], "location": ["Україна"]}
{"title": "Python developer", "company": "SourceTER", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Azure", "API", "Python", "AWS", "GCP", "AI", "Airflow", "Apache"], "location": ["Вірменія", "Азербайджан", "Грузія", "Казахстан", "Україна"]}
{"title": "Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Go", "Flask", "Git", "Pandas", "SQL", "CSS", "Vue.Js", "API", "Python", "Embers", "AWS", "SQLAlchemy", "AI", "Pytest", "Docker", "MySQL"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Go", "Flask", "Angular", "CSS", "Python", "Django", "AI", "JavaScript", "React"], "location": ["Україна"]}
{"title": "Back-end developer (Python/Web scraping)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["Git", "ML", "BeautifulSoup", "SQL", "Scrapy", "API", "Python", "Selenium", "AWS", "AI", "Airflow"], "location": ["Сполучені Штати"]}
{"title": "Python developer (Web scraping expert)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": null, "technologies": ["Git", "ML", "BeautifulSoup", "SQL", "Scrapy", "API", "Python", "Selenium", "AWS", "AI", "Airflow"], "location": ["Сполучені Штати"]}
{"title": "Backend Python/Django Developer for a SaaS Product", "company": "Iteksas", "company_type": "Product", "salary": "$2700-3500", "technologies": ["Go", "NoSQL", "ML", "Saas", "CSS", "Product", "SQL", "HTML", "Python", "Django", "Celery"], "location": ["Литва", "Україна"]}
{"title": "Middle/Senior Python Developer (Django)", "company": "Flexyti", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "MongoDB", "SQL", "CI/CD", "Kubernetes", "Python", "Django", "AWS", "PostgreSQL", "AI", "Docker"], "location": ["Україна"]}
{"title": "Middle/Senior Python Software Developer (or switcher from another OOP language)", "company": "Jito.dev", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Go", "Linux", "Git", "DevOps", "SQL", "CI/CD", "Python", "OOP", "Kubernetes", "AWS", "PostgreSQL", "AI", "Gis"], "location": ["Україна"]}
{"title": "Software Python Developer", "company": "Capital Recruiters", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Flask", "SQL", "API", "Python", "Django", "React"], "location": ["Україна"]}
{"title": "Python developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Linux", "NoSQL", "ML", "HTML", "CSS", "SQL", "jQuery", "API", "Python", "OOP", "Redis", "Django", "PostgreSQL", "Docker"], "location": ["Україна"]}
{"title": "Python/Django Full Stack Developer", "company": "BikeBUBL", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Go", "Frontend", "SQL", "Vue.Js", "Python", "Django", "AI", "PostgreSQL", "Js", "Vue"], "location": ["Велика Британія", "Україна"]}
{"title": "DevOps Engineer (with Golang or Python)", "company": "Akvelon", "company_type": "Outsource", "salary": "до $5000", "technologies": ["Go", "Git", "ML", "CI/CD", "Kubernetes", "Python", "API", "AWS", "AI", "Docker", "Sdn"], "location": ["Азербайджан", "Молдова", "Польща", "Туреччина", "Україна"]}
{"title": "Senior Python Developer", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "NoSQL", "Git", "ML", "CSS", "SQL", "HTML", "Python", "API", "Django", "AWS", "Senior", "JavaScript", "RESTful", "MySQL"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Competera", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Go", "Spark", "SQL", "Kafka", "Python", "AI", "GCP", "Airflow", "Luigi", "Click", "Apache"], "location": ["Кіпр", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Angular", "Git", "DevOps", "Vue.Js", "API", "Python", "Django", "AI", "React", "Docker", "Pyramid"], "location": ["Польща"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Go", "Flask", "Angular", "CSS", "Python", "Django", "AI", "JavaScript", "React"], "location": ["Україна"]}
{"title": "Python Developer for Automotive Project", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Angular", "Git", "DevOps", "Ansible", "Vue.Js", "API", "Python", "Django", "AI", "React", "Docker", "Pyramid"], "location": ["Польща"]}
{"title": "Software and MLOps Engineer (Python)  (Warsaw)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2500-3700", "technologies": ["Go", "ML", "DevOps", "Node.Js", "Python", "OOP", "API", "AWS", "AI", "React", "TensorFlow", "Mlops"], "location": ["Польща"]}
{"title": "Solidity/Blockchain expert (Smart Contract)", "company": "WeSoftYou", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "OOP", "AI", "React", "Solidity"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "SoftVision", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Flask", "Spark", "Git", "SQL", "API", "Python", "Kubernetes", "Django", "AWS", "PostgreSQL", "AI", "Docker", "MySQL", "Apache"], "location": ["Україна"]}
{"title": "Python Developer/Data Engineer", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["PyTorch", "OpenCV", "ML", "Git", "Pandas", "Python", "AI", "AWS", "NumPy", "TensorFlow"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Unidatalab", "company_type": "Product", "salary": "від $3000", "technologies": ["Go", "NoSQL", "Git", "ChatGPT", "Azure", "SQL", "Kafka", "Python", "API", "Kubernetes", "Django", "AWS", "GCP", "AI", "Docker", "FastAPI"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer (Prom.ua)", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["Git", "MongoDB", "Elasticsearch", "React", "RabbitMQ", "Go", "SQL", "Python", "JavaScript", "CSS", "CI/CD", "API", "Redis", "Docker", "Kafka", "Kubernetes", "PostgreSQL", "Webpack", "Click"], "location": ["Україна"]}
{"title": "Senior Appian Developer", "company": "DICEUS", "company_type": "Outstaff", "salary": "до $5000", "technologies": ["Go", "Git", "SQL", "API", "Embers", "AI", "Sail", "Appian", "JavaScript"], "location": ["Йорданія", "Польща", "Україна"]}
{"title": "Python Engineer", "company": "APOSTERA UA HARMAN", "company_type": "Product", "salary": "до $2800", "technologies": ["Linux", "DevOps", "Git", "ML", "Python", "API", "Automotive", "Senior", "AI", "Docker", "Automation", "Middle"], "location": ["Угорщина", "Польща", "Україна"]}
{"title": "Python Developer", "company": "SKILLUP", "company_type": "Product", "salary": "до $2800", "technologies": ["Go", "ML", "HTML", "CSS", "SQL", "Python", "Django", "AI"], "location": ["Україна"]}
{"title": "Python Developer for EdTech company", "company": "Projector", "company_type": "Product", "salary": null, "technologies": ["AI", "Python"], "location": ["Україна"]}
{"title": "Middle/Senior BackEnd developer Python/Django", "company": "Meest China", "company_type": "Product", "salary": null, "technologies": ["Go", "Nginx", "Git", "SQL", "API", "Python", "JWT", "Redis", "Wagtail", "Django", "AWS", "Jenkins", "AI", "Celery", "RESTful", "MySQL"], "location": ["Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["AI", "Python", "DevOps"], "location": ["Україна"]}
{"title": "Senior Python  Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Git", "ML", "Python", "OOP", "AI"], "location": ["Португалія"]}
{"title": "Python/GoLang developer (Europe)", "company": "TEAM International", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "NoSQL", "SQL", "Kubernetes", "API", "Python", "Django", "AI", "GCP", "Foundation"], "location": ["Польща", "Португалія"]}
{"title": "Senior Algorithms Developer (Speech Recognition, Python)", "company": "SD Solutions", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["PyTorch", "Go", "ML", "API", "Python", "Embers", "AI", "TensorFlow"], "location": ["Кіпр", "Грузія", "Польща", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": "до $2800", "technologies": ["Go", "Pandas", "SQL", "Python", "Embers", "Matplotlib", "AI", "Plotly", "NumPy", "Dash"], "location": ["Польща"]}
{"title": "Middle Backend Developer", "company": "Partner-way", "company_type": "Product", "salary": "до $2800", "technologies": ["Go", "Requests", "API", "Python", "JavaScript", "TypeScript"], "location": ["Велика Британія", "Сполучені Штати", "Україна", "Німеччина", "Польща"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": null, "technologies": ["PyTorch", "ML", "DevOps", "API", "Python", "OOP"], "location": ["Україна"]}
{"title": "Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Pandas", "SQL", "Node.Js", "Python", "OOP", "Redis", "Embers", "Django", "AI", "PostgreSQL", "Airflow", "React", "Celery", "Docker", "RabbitMQ"], "location": ["Польща", "Україна"]}
{"title": "Middle+/Senior Python developer", "company": "TechbrainJobs", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Go", "Angular", "Git", "SQL", "Elasticsearch", "Python", "Redis", "Django", "AI", "aiohttp", "PostgreSQL", "Mongo", "Celery", "Nginx", "Drf"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": null, "technologies": ["PyTorch", "ML", "DevOps", "API", "Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "Flyaps", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Linux", "Git", "CSS", "CI/CD", "SQL", "Python", "Django", "AI", "JavaScript"], "location": ["Україна"]}
