{"title": "Fullstack Engineer", "company": "MWDN", "company_type": "Outstaff", "salary": null, "technologies": ["Node", "Embers", "Git", "Python", "Vue", "HTML", "AI", "ML", "PHP", "SQL", "Go", "NoSQL", "API", "CSS"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "Python", "AI", "SQL", "Django", "Go"], "location": ["Україна"]}
{"title": "Senior RPA Software Engineer (Location Poland)", "company": "Unicsoft", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Git", "Python", "HTML", "AI", "ML", "Foundation", "SQL", "Go", "Linux", "API", "JavaScript"], "location": ["Україна", "Кіпр"]}
{"title": "Senior Python (Data) Engineer", "company": "Nortal", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "Spark", "Databricks", "PySpark", "Python", "Git", "AI", "Azure", "SQL", "Go", "API"], "location": ["Україна"]}
{"title": "Fullstack Software Developer (Python+React)/ AI enthusiast", "company": "Forex Tester Software Inc", "company_type": "Product", "salary": "$700-1500", "technologies": ["Svelte", "Embers", "Git", "React", "Angular", "Python", "Vue", "AI", "ChatGPT", "Go", "API"], "location": ["Україна"]}
{"title": "Python Developer (AdTech location technology leader)", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Spark", "AWS", "Python", "Go", "AI", "SQL", "Hadoop", "OOP"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "AI", "Docker", "Linux", "API", "OOP"], "location": ["Україна"]}
{"title": "Middle Python Engineer", "company": "GoIT", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "AWS", "Git", "Python", "AI", "Azure", "Flask", "Kubernetes", "Django", "Go"], "location": ["Польща"]}
{"title": "Python developer", "company": "Lineup", "company_type": "Outsource", "salary": "до $2800", "technologies": ["AWS", "Python", "SQL", "MySQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "AWS", "Git", "Python", "MongoDB", "Azure", "AI", "Kubernetes", "GCP", "Docker", "Jenkins", "Go", "Linux"], "location": ["Україна"]}
{"title": "Senior Infrastructure Engineer", "company": "Demigos", "company_type": "Outstaff", "salary": "до $6000", "technologies": ["Grpc", "Python", "AI", "Microservices", "SQL", "Java", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Kozak Group", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "Python", "Es", "JavaScript", "AI", "SQL", "MySQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Middle/Senior Django engineer", "company": "Disoft", "company_type": "Product", "salary": null, "technologies": ["Python", "PostgreSQL", "SQL", "Django", "Node.Js", "Go", "API"], "location": ["Україна", "Хорватія", "Польща"]}
{"title": "Middle Python Developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Python", "AI", "Kubernetes", "Docker", "Go", "API"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Kozak Group", "company_type": "Outstaff", "salary": null, "technologies": ["JavaScript", "AI", "Python"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "FreySoft", "company_type": "Outsource", "salary": null, "technologies": ["Python", "Go", "RESTful", "MongoDB", "AI", "Flask", "OOP", "API"], "location": ["Україна", "Польща"]}
{"title": "Middle Python Software Engineer", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["Kubernetes", "TypeScript", "Go", "Git", "Redux", "Docker", "Python", "Webpack", "CSS", "Redis", "SQLAlchemy", "React", "PostgreSQL", "aiohttp", "MongoDB", "AI", "RabbitMQ", "SQL", "Kafka", "Elasticsearch", "Click", "JavaScript", "asyncio"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Telnet)", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "FXC Intelligence", "company_type": "Product", "salary": "$5000-7000", "technologies": ["Python", "AI", "SQL", "Docker", "API"], "location": ["Велика Британія"]}
{"title": "Python Developer", "company": "FreySoft", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["Python", "Go", "RESTful", "MongoDB", "AI", "Flask", "OOP", "API"], "location": ["Польща", "Україна"]}
{"title": "Python/Django Engineer", "company": "Intobi", "company_type": "Outsource", "salary": null, "technologies": ["Python", "AI", "Django", "Docker", "Go"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$4000-6500", "technologies": ["DevOps", "FastAPI", "Embers", "Python", "AI", "SQL", "Django", "Go", "NoSQL", "API"], "location": ["Україна", "Польща"]}
{"title": "Python Engineer", "company": "Jungle Consulting", "company_type": "Product", "salary": "до $2500", "technologies": ["AWS", "Git", "Python", "HTML", "Mentoring", "AI", "ML", "Docker", "Linux", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "AI", "Docker", "Linux", "API", "OOP"], "location": ["Україна"]}
{"title": "Senior Full-Stack Engineer Python/Data Engineer", "company": "Intellias", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["DevOps", "Spark", "SQLAlchemy", "PySpark", "Python", "Go", "React", "Embers", "AI", "Azure", "Flask", "SQL", "D3", "Docker", "Dask", "Celery", "Pandas"], "location": ["Україна"]}
{"title": "Principal/Associate Director Software Engineer", "company": "Skillreveal", "company_type": "Outsource", "salary": "до $5000", "technologies": ["Embers", "AWS", "SQLAlchemy", "Python", "React", "AI", "Flask", "Kubernetes", "SQL", "Java", "Agile", "Go", "API"], "location": ["Польща"]}
{"title": "Senior Python with Cloud Certificate", "company": "Skillreveal", "company_type": "Outstaff", "salary": "$2700-3500", "technologies": ["Spark", "AWS", "Python", "Go", "React", "AI", "Azure", "Kafka", "Terraform", "API", "Redis"], "location": ["Україна"]}
{"title": "Python (Backend) Developer", "company": "Shark Software Company", "company_type": "Outstaff", "salary": null, "technologies": ["Bootstrap", "HTML", "GCP", "Django", "Go", "OOP", "Git", "GraphQL", "Docker", "AWS", "jQuery", "Python", "CI/CD", "Flask", "Celery", "CSS", "Redis", "FastAPI", "React", "PostgreSQL", "aiohttp", "AI", "ML", "RabbitMQ", "SQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Full-Stack Developer/ AI Evangelist", "company": "Softengi", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["DevOps", "AWS", "Git", "React", "Angular", "Python", "CI/CD", "AI", "Azure", "ML", "ChatGPT", "Copilot", "JavaScript"], "location": ["Чехія", "Литва", "Латвія", "Польща", "Україна"]}
{"title": "Senior Python Backend Developer", "company": "Forte Group", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Git", "Python", "React", "GraphQL", "AI", "Elasticsearch", "PHP", "Node.Js", "OOP", "API", "Pandas", "JavaScript"], "location": ["Україна"]}
{"title": "Mid Python (Django) Developer", "company": "3asoft", "company_type": "Outstaff", "salary": null, "technologies": ["Git", "Python", "AI", "Django", "Go"], "location": ["Україна"]}
{"title": "Python Developers (Permanent/ requires relocation to Dubai, UAE)", "company": "Aspire Technology", "company_type": "Product", "salary": "$7000-10000", "technologies": ["Go", "AI", "API", "Python"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Senior Python Developer", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "PostgreSQL", "Go", "AI", "Flask", "SQL", "Django", "OOP", "MySQL", "Mvc"], "location": ["Україна"]}
{"title": "QA Automation Engineer", "company": "PandaFlow", "company_type": "Product", "salary": null, "technologies": ["JavaScript", "AI", "Selenium", "Python"], "location": ["Сполучені Штати"]}
{"title": "Senior Python Software Engineer", "company": "InoXoft", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Embers", "Git", "Celery", "Python", "Go", "AI", "Flask", "Terraform"], "location": ["Україна"]}
{"title": "Strong Middle/Senior Python Web Developer for an energy efficiency project", "company": "Latrock", "company_type": "Product", "salary": "$2700-3500", "technologies": ["Python", "HTML", "AI", "Flask", "ML", "SQL", "Django", "Go", "API", "CSS"], "location": ["Німеччина"]}
{"title": "Junior Python Developer (розробка ботів)", "company": "CallC247", "company_type": "Product", "salary": "$700-1200", "technologies": ["Bot", "Solidity", "Python", "AI", "Blockchain"], "location": ["Україна"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8000", "technologies": ["Python", "TensorFlow", "PyTorch", "Keras", "Go"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "AWS", "Git", "Python", "MongoDB", "Azure", "AI", "Kubernetes", "GCP", "Docker", "Jenkins", "Go", "Linux"], "location": ["Україна"]}
{"title": "Senior Backend Python Developer", "company": "Verbit", "company_type": "Product", "salary": null, "technologies": ["AWS", "Python", "AI", "SQL", "Go", "NoSQL", "Redis"], "location": ["Україна"]}
{"title": "Python Developer", "company": "ANDROMEDA Systems", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["DevOps", "Git", "AWS", "Python", "AI", "Django", "Go", "Pandas"], "location": ["Україна"]}
{"title": "Python Developer (Turkey)", "company": "OSF Digital", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["Git", "Python", "AI", "Agile", "Go", "API"], "location": ["Туреччина"]}
{"title": "Middle Fullstack developer with Python knowledge", "company": "Mornhouse", "company_type": "Product", "salary": "$1800-2400", "technologies": ["CSS", "Git", "jQuery", "React", "Python", "Go", "HTML", "Redux", "AI", "ML", "Django", "OOP", "Fullstack", "API", "Pandas"], "location": ["Україна"]}
{"title": "Software Engineer (Python) (G)", "company": "Freelance", "company_type": "Outsource", "salary": "$2500", "technologies": ["DevOps", "Apache", "Spark", "Git", "AWS", "Python", "PostgreSQL", "CI/CD", "MongoDB", "AI", "Moment", "Bigdata", "Airflow", "SQL", "Go", "MySQL", "Redis"], "location": ["Румунія"]}
{"title": "Python Developer", "company": "EvaCodes", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "AI", "Python"], "location": ["Україна"]}
{"title": "Python NLP Developer", "company": "Tangible AI", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Git", "Python", "Nlp", "CI/CD", "AI", "Django", "Go"], "location": ["Сполучені Штати"]}
{"title": "Python Engineer", "company": "Intobi", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Python"], "location": ["Україна"]}
{"title": "Python Back-end Developer (JobTestPrep)", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Apis", "AWS", "React", "Python", "Json", "RESTful", "Git", "CI/CD", "AI", "Angular", "Kubernetes", "SQL", "Docker", "Go", "NoSQL", "API"], "location": ["Україна", "Грузія", "Кіпр"]}
{"title": "Str.Middle/Senior Python Architect 2037/03", "company": "Argument", "company_type": "Outstaff", "salary": "до $5000", "technologies": ["Pyramid", "Python", "PostgreSQL", "AI", "SQL", "Go", "Postgres"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["FastAPI", "Git", "Dash", "Python", "AI", "Flask", "SQL", "OOP", "API"], "location": ["Україна"]}
{"title": "Шукаю Спеціаліста з програмування АІ", "company": "Codeware.Digital", "company_type": "Product", "salary": null, "technologies": ["AWS", "Git", "Python", "AI", "TensorFlow", "PyTorch", "Blockchain", "Keras"], "location": ["Україна"]}
{"title": "Odoo Developer", "company": "White Label", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "PostgreSQL", "HTML", "AI", "ML", "SQL", "Go", "Linux", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Python Developer", "company": "NONAME DIGITAL", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["DevOps", "Git", "Python", "Go", "AI", "Django", "Docker", "Linux", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Python Backend Engineer", "company": "Reef Technlogies", "company_type": "Product", "salary": "$7560-11760", "technologies": ["Embers", "Python", "AI", "Django", "Go"], "location": ["Польща"]}
{"title": "Middle Python Developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["Git", "Python", "HTML", "ML", "SQL", "Linux", "API", "CSS"], "location": ["Україна"]}
{"title": "Full Stack Engineer (Python/React)", "company": "Fluvius", "company_type": "Outstaff", "salary": "до $2800", "technologies": ["AWS", "React", "Python", "Requests", "AI", "TypeScript", "SQL", "Django", "Go", "MySQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Software Engineer", "company": "incoalliance", "company_type": "Outstaff", "salary": "до $5000", "technologies": ["Spark", "Git", "Python", "Go", "AI", "TensorFlow", "Microservices", "Kubernetes", "Airflow", "Elasticsearch", "Docker", "Jenkins", "OOP", "API", "Pandas", "Redis"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Vimmi Communications", "company_type": "Product", "salary": "$1500-2800", "technologies": ["FastAPI", "Vim", "Python", "Go", "aiohttp", "RESTful", "MongoDB", "AI", "Flask", "Kubernetes", "Linux", "SQL", "Django", "Tornado", "OOP", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Robotics Advanced Automation Engineer", "company": "SoftServe", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Ros", "AWS", "Python", "AI", "Codesys", "Go", "API"], "location": ["Україна"]}
{"title": "Data Engineer/Analyst", "company": "AdPartner", "company_type": "Product", "salary": "$3000-4000", "technologies": ["Embers", "Git", "Scikit-learn", "Python", "AI", "TensorFlow", "PyTorch", "ML", "NumPy", "Airflow", "Go", "Pandas"], "location": ["Німеччина", "Естонія", "Польща", "Португалія", "Україна"]}
{"title": "Middle/Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$1000-5000", "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Quantitative Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Git", "Python", "Go", "AI", "OOP", "Linux"], "location": ["Україна"]}
{"title": "SEnior Python WMS", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["Python", "Go", "AI", "Wms", "OOP", "Linux", "API"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Backend Engineer with AI Integration Experience", "company": "Visarsoft", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "Tdd", "Nlp", "Python", "React", "Angular", "AI", "Azure", "TensorFlow", "TypeScript", "Agile", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Full-Stack Engineer Python/React", "company": "Intellias", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["DevOps", "Spark", "SQLAlchemy", "PySpark", "React", "Python", "Go", "AI", "Azure", "Flask", "TypeScript", "SQL", "D3", "Docker", "Dask", "Celery", "Pandas"], "location": ["Україна"]}
{"title": "Data Scientist / Senior Python developer", "company": "Simplify", "company_type": "Outstaff", "salary": "$2000-5000", "technologies": ["Git", "Python", "Sota", "OpenCV", "AI", "PyTorch", "ML", "Go", "Tensorrt"], "location": ["Україна", "Німеччина", "Польща"]}
{"title": "Senior Data Engineer", "company": "Intetics", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["AWS", "Git", "Python", "AI", "ML", "Airflow", "GCP", "SQL", "Go", "API", "Etl"], "location": ["Україна"]}
{"title": "Data and Machine Learning Engineer (Python)", "company": "Softwarium", "company_type": "Outsource", "salary": null, "technologies": ["Scikit-learn", "Angular", "Dask", "Go", "OOP", "Git", "Azure", "NumPy", "Docker", "Embers", "AWS", "Python", "TensorFlow", "NoSQL", "Pandas", "Spark", "React", "AI", "PyTorch", "ML", "SQL", "API"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["GCP", "Django", "Go", "MySQL", "Git", "Bigdata", "Cassandra", "Apache", "AWS", "Python", "CI/CD", "Moment", "Airflow", "Redis", "Spark", "MongoDB", "AI", "RabbitMQ", "SQL", "Kafka", "Elasticsearch", "API"], "location": ["Румунія"]}
{"title": "Senior Python Developer", "company": "TechMagic", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "AWS", "Python", "PostgreSQL", "Go", "CI/CD", "React", "AI", "Angular", "SQL", "Django", "Node.Js", "OOP", "API", "Selenium", "JavaScript"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["FastAPI", "Git", "Dash", "Python", "AI", "Flask", "SQL", "OOP", "API"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": null, "technologies": ["Postman", "AWS", "Git", "Python", "CI/CD", "AI", "Go", "API"], "location": ["Україна"]}
{"title": "Senior Python Backend Developer", "company": "TechHunt", "company_type": "Product", "salary": "$3500-5000", "technologies": ["Python", "Go", "CI/CD", "RabbitMQ", "Django", "Elasticsearch"], "location": ["Німеччина", "Нідерланди", "Польща", "Україна", "Португалія"]}
{"title": "Tech Lead (Python/Django/JS)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["Go", "AI", "Embers", "Python"], "location": ["Україна"]}
{"title": "Junior software engineer (parsing/reverse)", "company": "Artellence", "company_type": "Product", "salary": "до $2500", "technologies": ["Requests", "Java", "Linux", "Go", "Docker", "BeautifulSoup", "Python", "Parsing", "NoSQL", "Redis", "Security", "aiohttp", "MongoDB", "AI", "SQL", "API", "Selenium", "JavaScript", "asyncio"], "location": ["Україна"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "React", "Python", "PostgreSQL", "RESTful", "HTML", "AI", "ML", "SQL", "Go", "API", "CSS", "JavaScript"], "location": ["Польща"]}
{"title": "Senior Backend Engineer", "company": "Launch Labs", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "AWS", "Python", "Go", "GraphQL", "React", "MongoDB", "AI", "Flask", "ML", "TypeScript", "Celery", "API"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Python", "AI", "Django", "Go", "JavaScript"], "location": ["Україна"]}
{"title": "Data Mining Engineer needed for data centric startup", "company": "Forecasa", "company_type": "Product", "salary": null, "technologies": ["Spark", "Git", "PySpark", "Python", "CI/CD", "AI", "Kubernetes", "Airflow", "Pandas", "Docker", "Selenium"], "location": ["Сполучені Штати"]}
{"title": "Senior Python + Scala Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Scala", "Embers", "Python", "PostgreSQL", "RESTful", "AI", "SQL", "Go", "API"], "location": ["Польща"]}
{"title": "Quantitative Analyst", "company": "Weem", "company_type": "Product", "salary": null, "technologies": ["Perl", "SQL", "Python", "Phyton"], "location": ["Канада"]}
{"title": "Junior Python Developer in Test (CSA)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Pytest", "Git", "AWS", "Python", "CI/CD", "AI", "ML", "SQL", "Docker", "Jenkins", "Linux", "NoSQL", "asyncio"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "SPS Commerce", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Embers", "AWS", "Python", "CI/CD", "AI", "Kubernetes", "Docker", "API"], "location": ["Україна"]}
{"title": "Django developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "Python", "Go", "AI", "Django", "Celery", "API"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "Chatmasters", "company_type": "Product", "salary": "$700-1500", "technologies": ["FastAPI", "Drf", "Python", "Go", "MongoDB", "AI", "Flask", "ML", "ChatGPT", "Postgressql", "Websockets", "RabbitMQ", "Restapi", "Docker", "Celery", "Linux", "API"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["FastAPI", "AWS", "Python", "PostgreSQL", "GraphQL", "CI/CD", "AI", "Flask", "ML", "GCP", "SQL", "Django", "Docker", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Senior Python Engineer (Application Platform Track)", "company": "PandaDoc", "company_type": "Product", "salary": null, "technologies": ["FastAPI", "AWS", "Git", "Rabbimq", "Python", "PostgreSQL", "AI", "Kubernetes", "RabbitMQ", "SQL", "Django", "Docker", "Kafka", "Go", "Pandas", "asyncio"], "location": ["Польща", "Португалія", "Україна"]}
{"title": "Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["Scraping", "Embers", "BeautifulSoup", "Python", "HTML", "AI", "Flask", "ML", "SQL", "Selenium", "NoSQL", "API", "Pandas"], "location": ["Польща", "Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Product", "salary": null, "technologies": ["FastAPI", "Git", "Dash", "Python", "AI", "Flask", "SQL", "OOP", "API"], "location": ["Україна"]}
{"title": "Application Engineer", "company": "UnameIT", "company_type": "Product", "salary": "до $2500", "technologies": ["Fabric", "AI", "Git", "Python"], "location": ["Україна"]}
{"title": "Senior Python developer (with DevOps experience)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "FastAPI", "Embers", "Python", "AI", "SQL", "Django", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Python Back-end Developer /Candidates from Ukraine     JobTestPrep", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["AWS", "Git", "Python", "PostgreSQL", "React", "CI/CD", "RESTful", "MongoDB", "AI", "Angular", "Kubernetes", "SQL", "Docker", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer-a на ізраїльський фінтех проєкт", "company": "Ciklum International", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Spark", "Git", "Python", "AI", "Kubernetes", "SQL", "Data"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Temy", "company_type": "Outsource", "salary": null, "technologies": ["Python", "PostgreSQL", "GraphQL", "React", "SQL", "Django", "Go", "API"], "location": ["Україна"]}
{"title": "Django Developer (Middle)", "company": "PLANEKS", "company_type": "Outsource", "salary": "від $3000", "technologies": ["FastAPI", "Python", "Go", "AI", "Django", "Celery", "API"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Blackthorn Vision", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Angular", "HTML", "TypeScript", "Django", "Go", "Linux", "Git", "Azure", "Scipy", "NumPy", "Node.Js", "AWS", "Github", "Python", "Flask", "Pandas", "CSS", "React", "AI", "ML", "SQL", "Black", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "FastAPI", "Embers", "Python", "AI", "SQL", "Restapi", "Django", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "DAAS Support ENG", "company": "Temerix", "company_type": "Product", "salary": "$700-800", "technologies": ["Python", "Requests", "HTML", "AI", "Moment", "ML", "SQL", "Go", "NoSQL", "CSS"], "location": ["Україна"]}
{"title": "Middle Backend engineer on the project", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["FastAPI", "Git", "Dash", "Python", "AI", "Flask", "SQL", "OOP", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "Embers", "Git", "Python", "React", "Angular", "RESTful", "AI", "GCP", "Go", "API", "asyncio"], "location": ["Польща", "Хорватія", "Словаччина"]}
{"title": "Senior Fullstack Engineer (python+react)", "company": "Svitla Systems", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Git", "React", "Python", "PostgreSQL", "RESTful", "HTML", "AI", "ML", "TypeScript", "SQL", "Django", "Go", "MySQL", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Back-end Developer (experience with GPT API)", "company": "TechHunt", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["Git", "Python", "AI", "Node.Js", "API"], "location": ["Україна"]}
{"title": "Senior Python", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Git", "Python", "PostgreSQL", "React", "AI", "Flask", "Kubernetes", "Airflow", "SQL", "Jenkins", "Go", "Apache", "JavaScript"], "location": ["Польща"]}
{"title": "Senior Python Developer/DevOps Engineer", "company": "Powercode", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Git", "Dash", "Python", "Go", "CI/CD", "AI", "Azure", "Kubernetes", "Kibana", "Elasticsearch"], "location": ["Німеччина", "Польща", "Україна"]}
{"title": "backend CRM розробник", "company": "Stablexsolution", "company_type": "Product", "salary": "$1500-3000", "technologies": ["Python", "React", "Scss", "SQL", "Django", "Go", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["Embers", "Celery", "Python", "PostgreSQL", "Go", "React", "AI", "RabbitMQ", "Airflow", "SQL", "Django", "Docker", "Node.Js", "OOP", "Pandas", "Redis"], "location": ["Україна", "Польща", "Вірменія"]}
{"title": "Strong Middle/Senior Python Engineer", "company": "PLANEKS", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["FastAPI", "Python", "Go", "AI", "Django", "Celery", "API"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Kubernetes", "Go", "Linux", "OOP", "MySQL", "Git", "Docker", "Tornado", "Falcon", "Pytest", "Embers", "Python", "Flask", "SQLAlchemy", "PostgreSQL", "aiohttp", "AI", "SQL", "API"], "location": ["Україна"]}
{"title": "Senior Full Stack Engineer with Python and Golang", "company": "TeamDev", "company_type": "Outstaff", "salary": null, "technologies": ["AWS", "Git", "Python", "PostgreSQL", "React", "CI/CD", "MongoDB", "Azure", "AI", "Kubernetes", "GCP", "SQL", "Docker", "Go", "JavaScript"], "location": ["Україна"]}
{"title": "Python developer (AIOHttp)", "company": "TheWhyKingz", "company_type": "Product", "salary": "$1800-2400", "technologies": ["Embers", "Python", "PostgreSQL", "aiohttp", "MongoDB", "AI", "Shiny", "SQL", "Go", "Linux", "Redis"], "location": ["Латвія"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Embers", "Git", "Python", "React", "GraphQL", "AI", "Kubernetes", "Docker", "Reactjs", "Go", "API", "Golang", "OOP"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Database Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "$600-3500", "technologies": ["CSS", "Celery", "Python", "PostgreSQL", "Go", "React", "Angular", "Webpack", "HTML", "ML", "RabbitMQ", "Pandas", "SQL", "Django", "Linux", "MySQL", "Etl", "Redis"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "Solid", "AI", "Multithreading", "Linux", "Databases", "OOP"], "location": ["Україна"]}
{"title": "Python (Django) Developer", "company": "IvorySoft", "company_type": "Outsource", "salary": null, "technologies": ["Go", "AI", "Python", "Django"], "location": ["Україна"]}
{"title": "Backend Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$3500-4500", "technologies": ["AWS", "Git", "Python", "RESTful", "HTML", "AI", "Kubernetes", "ML", "Foundation", "Docker", "Go", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Middle+ Python Developer", "company": "CodeIT", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Embers", "Git", "Python", "PostgreSQL", "CI/CD", "AI", "Ansible", "SQL", "Django", "Docker", "Go", "Linux", "API"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Git", "Python", "RESTful", "AI", "SQL", "Go", "NoSQL", "API"], "location": ["Польща"]}
{"title": "Senior/Lead Python Developer", "company": "CHI Software", "company_type": "Outsource", "salary": null, "technologies": ["GCP", "Django", "Go", "Linux", "DevOps", "Azure", "Docker", "AWS", "Python", "CI/CD", "Flask", "PHP", "NoSQL", "FastAPI", "aiohttp", "AI", "SQL", "Elasticsearch", "API", "JavaScript"], "location": ["Польща", "Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Kubernetes", "Go", "Linux", "OOP", "MySQL", "Git", "Docker", "Tornado", "Falcon", "Pytest", "Embers", "Python", "Flask", "SQLAlchemy", "PostgreSQL", "aiohttp", "AI", "SQL", "API"], "location": ["Україна"]}
{"title": "Python Developer (middle)", "company": "Fordewind", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["DevOps", "Git", "AWS", "Python", "Go", "HTML", "AI", "Flask", "ML", "Elasticsearch", "SQL", "Celery", "NoSQL", "Pandas", "JavaScript"], "location": ["Україна"]}
{"title": "Sr. Python Developer", "company": "TrustPoint", "company_type": "Product", "salary": "$2000-5000", "technologies": ["DevOps", "Git", "Python", "CI/CD", "RESTful", "AI", "ML", "Django", "Go", "API"], "location": ["Сполучені Штати"]}
{"title": "Python Engineer", "company": "CloudMade", "company_type": "Product", "salary": "$1500-3000", "technologies": ["FastAPI", "Spark", "AWS", "Git", "Python", "PostgreSQL", "Go", "Scikit-learn", "aiohttp", "AI", "Flask", "ML", "SQL", "Docker", "OOP", "Apache", "API", "Pandas"], "location": ["Польща"]}
{"title": "Middle Python+Node.JS Engineer", "company": "A-Team Global", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "Python", "HTML", "AI", "ML", "Node.Js", "Go", "CSS"], "location": ["Болгарія", "Німеччина", "Україна"]}
{"title": "Intelligent Automation Full Stack  Developer - Open A.I. and No Code A.I. is a plus", "company": "Mentally", "company_type": "Product", "salary": "$2500-3700", "technologies": ["DevOps", "AWS", "Git", "Python", "AI", "Azure", "Saas", "ML", "Docker", "Go", "Automation"], "location": ["Італія"]}
{"title": "Senior Python Developer", "company": "Numerical Technologies", "company_type": "Product", "salary": "$1000-5000", "technologies": ["FastAPI", "AWS", "Git", "Python", "RESTful", "MongoDB", "Azure", "AI", "Go", "API"], "location": ["Польща", "Португалія", "Сінгапур", "Україна"]}
{"title": "Senior Machine Learning Engineer  video", "company": "PAYRUN", "company_type": "Product", "salary": "$5000-10000", "technologies": ["Python"], "location": ["Україна"]}
{"title": "Python developer", "company": "Embedd", "company_type": "Product", "salary": null, "technologies": ["Git", "Python", "PostgreSQL", "AI", "ML", "SQL", "API"], "location": ["Німеччина", "Велика Британія", "Україна"]}
{"title": "Senior Python Developer", "company": "Radency", "company_type": "Outstaff", "salary": null, "technologies": ["GCP", "Git", "GraphQL", "Docker", "Apache", "Python", "Flask", "Airflow", "NoSQL", "Pandas", "Redis", "Spark", "Flux", "PostgreSQL", "AI", "RabbitMQ", "SQL", "Elasticsearch", "API", "Postgres"], "location": ["Україна"]}
{"title": "Python Team Lead", "company": "SoftConstruct", "company_type": "Product", "salary": null, "technologies": ["DevOps", "FastAPI", "Spark", "Python", "Go", "aiohttp", "RESTful", "AI", "Kubernetes", "Beam", "Airflow", "Ansible", "SQL", "Kafka", "OOP", "Apache", "API"], "location": ["Україна"]}
{"title": "Full-Stack Python Developer (with Angular)", "company": "Virtuace", "company_type": "Outsource", "salary": "$3000-4500", "technologies": ["FastAPI", "Git", "Python", "Angular", "CI/CD", "MongoDB", "Azure", "AI", "Kubernetes", "ML", "NumPy", "Docker", "Go", "API", "Pandas"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["Pyramid", "AWS", "Git", "Python", "Go", "Embers", "CI/CD", "HTML", "AI", "Flask", "Kubernetes", "ML", "Django", "Node.Js", "OOP", "API", "JavaScript"], "location": ["Польща"]}
{"title": "Strong Python Developer", "company": "NGM Agency", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Git", "Python", "PostgreSQL", "Go", "HTML", "AI", "ML", "Puppet", "Linux", "PHP", "SQL", "Django", "Docker", "OOP", "MySQL", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python/Django Engineer", "company": "at Apexive", "company_type": "Agency", "salary": "від $3000", "technologies": ["AWS", "Python", "React", "RESTful", "AI", "Kubernetes", "SQL", "Django", "Docker", "Go", "MySQL"], "location": ["Чехія", "Нідерланди", "Польща", "Україна"]}
{"title": "Python Developer - AI Automation Solutions (LLaMA, ChatGPT Agents, Auto-GPT, LangChain)", "company": "Aimech", "company_type": "Product", "salary": "$600-1200", "technologies": ["FastAPI", "Langchain", "Nlp", "Python", "Llm", "AI", "ML", "ChatGPT", "API"], "location": ["Велика Британія", "Україна"]}
{"title": "Python Developer", "company": "GEO Pay", "company_type": "Product", "salary": null, "technologies": ["AWS", "Drf", "Python", "PostgreSQL", "Go", "AI", "Azure", "Foundation", "SQL", "Django", "Celery", "API", "Redis"], "location": ["Україна"]}
{"title": "Python Developer (Django)", "company": "IT Svit", "company_type": "Outsource", "salary": "від $3000", "technologies": ["DevOps", "Git", "jQuery", "Python", "PostgreSQL", "React", "MongoDB", "AI", "TensorFlow", "Elasticsearch", "Keycloak", "SQL", "Django", "Docker", "Kafka", "Go", "API"], "location": ["Україна"]}
{"title": "Python Team Lead", "company": "Mrt", "company_type": "Product", "salary": "до $7500", "technologies": ["Python", "Go", "AI", "OOP", "Linux"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Senior FullStack (Python+React) Developer", "company": "DataArt", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "Python", "React", "PostgreSQL", "RESTful", "HTML", "AI", "ML", "SQL", "Go", "API", "CSS", "JavaScript"], "location": ["Польща"]}
{"title": "Python Developer", "company": "IT Svit", "company_type": "Outsource", "salary": null, "technologies": ["Rest", "Django", "Go", "DevOps", "Git", "Docker", "jQuery", "Python", "TensorFlow", "Microservices", "React", "PostgreSQL", "MongoDB", "AI", "ML", "SQL", "Kafka", "Elasticsearch", "API"], "location": ["Україна"]}
{"title": "Full Stack Developer", "company": "UKR.NET", "company_type": "Product", "salary": null, "technologies": ["TypeScript", "Go", "MySQL", "Python", "MobX", "NoSQL", "Redis", "React", "PostgreSQL", "aiohttp", "MongoDB", "AI", "Sqlite", "SQL", "Elasticsearch", "Redux", "API", "JavaScript", "asyncio"], "location": ["Україна"]}
{"title": "Strong Junior/Middle Python Developer", "company": "Vilmate", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "FastAPI", "AWS", "Git", "Python", "PostgreSQL", "Go", "MongoDB", "AI", "SQL", "Django", "Docker", "Celery", "NoSQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$5000", "technologies": ["DevOps", "AWS", "Python", "Go", "CI/CD", "MongoDB", "AI", "Flask", "Cognito", "Airflow", "OOP", "Apache", "API"], "location": ["Україна"]}
{"title": "Python developer", "company": "Olearis", "company_type": "Outsource", "salary": "$600-3500", "technologies": ["FastAPI", "SQLAlchemy", "AWS", "Python", "PostgreSQL", "Go", "Requests", "AI", "SQL", "OOP", "API"], "location": ["Україна"]}
{"title": "ML/Python Senior", "company": "Danavero", "company_type": "Outstaff", "salary": "$2000-5000", "technologies": ["Python", "CI/CD", "AI", "Azure", "ML", "SQL"], "location": ["Україна"]}
{"title": "Lead Python Engineer  (challenging omnichannel payment processing solution for Europe and North America)", "company": "Godel Technologies", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["DevOps", "FastAPI", "AWS", "Git", "Python", "PostgreSQL", "CI/CD", "AI", "Azure", "Flask", "GCP", "SQL", "Docker", "Go", "MySQL", "API"], "location": ["Польща", "Литва", "Болгарія"]}
{"title": "Python developer", "company": "Ciba Health", "company_type": "Product", "salary": "$2000-5000", "technologies": ["DevOps", "Pyramid", "AWS", "Git", "Python", "GraphQL", "RESTful", "HTML", "AI", "Flask", "Kubernetes", "ML", "SQL", "Django", "Go", "API", "CSS", "Redis"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Vidby", "company_type": "Product", "salary": "$1200-2500", "technologies": ["Python", "PostgreSQL", "Go", "AI", "RabbitMQ", "SQL", "Django", "Celery", "API", "Redis"], "location": ["Україна"]}
{"title": "Back End Engineer ( Python\\Java\\Go) with Data Engineering experience", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $7500", "technologies": ["Spark", "Flink", "CI/CD", "AI", "ML", "Kafka", "API"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer (experience in ML projects using Python)", "company": "ISRAEL IT", "company_type": "Outstaff", "salary": "$3000-4500", "technologies": ["Spark", "AWS", "Git", "Python", "Go", "Embers", "CI/CD", "AI", "Kubernetes", "ML", "Docker", "English", "API", "OOP"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data Skills (AdTech Location Technology Leader)", "company": "Sigma Software", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "AWS", "Python", "Go", "AI", "SQL", "Hadoop", "Emr", "OOP"], "location": ["Польща", "Україна"]}
{"title": "Technical Lead Python", "company": "Meest Group", "company_type": "Product", "salary": "$2000-5000", "technologies": ["AWS", "Git", "Python", "PostgreSQL", "React", "CI/CD", "SQL", "Django", "Docker", "Go"], "location": ["Україна"]}
{"title": "Software Engineering Team Lead", "company": "AllSTARSIT", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer (with DevOps)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "FastAPI", "Embers", "AWS", "Python", "CI/CD", "AI", "Azure", "ML", "Puppet", "Chef", "Ansible", "SQL", "Django", "Docker", "Go", "NoSQL", "API"], "location": ["Україна", "Польща", "Грузія"]}
{"title": "Infrastructure Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Python", "Go", "AI", "SQL", "Java", "OOP", "NoSQL", "API", "Golang"], "location": ["Україна"]}
{"title": "Strong Junior/Middle Data Scientist", "company": "AppReal", "company_type": "Outstaff", "salary": "$700-1200", "technologies": ["Spark", "PySpark", "Embers", "Python", "AI", "Go", "Linux"], "location": ["Україна"]}
{"title": "Python developer", "company": "Uptarget", "company_type": "Product", "salary": "$2500-3700", "technologies": ["Python", "CI/CD", "AI", "Kubernetes", "Docker", "Kafka", "Go"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": "$1200-2500", "technologies": ["SQLAlchemy", "AWS", "Python", "PostgreSQL", "BeautifulSoup", "HTML", "AI", "Flask", "ML", "SQL", "Celery", "Linux", "API", "Selenium"], "location": ["Польща", "Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Orderry", "company_type": "Product", "salary": null, "technologies": ["Kubernetes", "Django", "Go", "Docker", "Pytest", "Python", "Webpack", "Celery", "Redis", "React", "PostgreSQL", "aiohttp", "AI", "RabbitMQ", "SQL", "Kafka", "Redux", "Selenium", "asyncio"], "location": ["Україна"]}
{"title": "Python/Django REST API Backend Developer", "company": "Smart UI", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["Angular", "HTML", "Django", "Go", "MySQL", "Linux", "Backend", "DevOps", "Git", "Crypto", "Docker", "AWS", "jQuery", "Python", "PHP", "NoSQL", "CSS", "React", "PostgreSQL", "MongoDB", "AI", "ML", "SQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Engineer with JS/Typescript", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Spark", "SQLAlchemy", "PySpark", "Python", "Go", "React", "Embers", "AI", "Azure", "Flask", "TypeScript", "SQL", "D3", "Docker", "Dask", "Celery", "Pandas"], "location": ["Україна"]}
{"title": "Experienced Python Developer - lifetime opportunity", "company": "CleverCrew", "company_type": "Product", "salary": null, "technologies": ["Svelte", "FastAPI", "Git", "AI", "Django", "Jenkins", "Go", "API", "Postgres"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "EVE.calls", "company_type": "Product", "salary": "$4000", "technologies": ["Grpc", "Python", "TensorFlow", "Websockets", "Unix"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "FastAPI", "Embers", "Python", "AI", "SQL", "Django", "Go", "NoSQL", "API"], "location": ["Україна", "Грузія", "Польща"]}
{"title": "Odoo Senior Developer", "company": "Mongrov", "company_type": "Product", "salary": null, "technologies": ["Odoo", "AI", "ML", "Go", "API"], "location": ["Колумбія", "Польща", "Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Postman", "Git", "Python", "CI/CD", "RESTful", "AI", "Docker", "Kubernetes", "Swagger", "Jenkins", "API"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["CSS", "Pytest", "SQLAlchemy", "AWS", "Python", "Git", "Embers", "AI", "Flask", "SQL", "Docker", "Go", "MySQL", "API", "Pandas", "Vue.Js"], "location": ["Україна"]}
{"title": "Full-Stack Python Engineer", "company": "MEV", "company_type": "Outsource", "salary": "$3000-4200", "technologies": ["DevOps", "AWS", "Python", "Go", "React", "CI/CD", "AI", "ML", "SQL", "Django", "Docker", "Jenkins", "Celery", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Celery", "Python", "PostgreSQL", "Go", "AI", "Flask", "ML", "SQL", "Docker", "OOP", "JavaScript"], "location": ["Україна"]}
{"title": "FullStack developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "$2700-3500", "technologies": ["jQuery", "Python", "PostgreSQL", "React", "Angular", "HTML", "MongoDB", "AI", "ML", "SQL", "Django", "Go", "Apache", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Python developer", "company": "SourceTER", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["AWS", "Python", "AI", "Azure", "Airflow", "GCP", "Apache", "API"], "location": ["Вірменія", "Азербайджан", "Грузія", "Казахстан", "Україна"]}
{"title": "Team Lead / Senior Python Engineer (Indigo Ag)", "company": "Intelliarts", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "SQLAlchemy", "Git", "Python", "Go", "AI", "Pydantic", "SQL", "Celery", "API", "Redis"], "location": ["Україна"]}
{"title": "Middle/Senior Full-stack Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["AWS", "Git", "React", "CI/CD", "RESTful", "AI", "Azure", "Kubernetes", "GCP", "Django", "Docker", "Jenkins", "Go", "API"], "location": ["Велика Британія", "Польща", "Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Bcconsolidator", "company_type": "Product", "salary": "$5800-7000", "technologies": ["Embers", "AWS", "SQLAlchemy", "Python", "PostgreSQL", "GraphQL", "Angular", "Apollo", "AI", "ML", "SQL", "Go", "Selenium"], "location": ["Латвія", "Нідерланди", "Польща"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Python", "React", "Angular", "AI", "Flask", "Django", "Go", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Back-end developer (Python/Web scraping)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": "до $5000", "technologies": ["AWS", "Git", "Python", "BeautifulSoup", "AI", "ML", "Airflow", "SQL", "Scrapy", "API", "Selenium"], "location": ["Сполучені Штати"]}
{"title": "Senior Python Engineer", "company": "Star Global", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["FastAPI", "Embers", "SQLAlchemy", "Git", "Python", "PostgreSQL", "Go", "AI", "Microservices", "Flask", "ML", "GCP", "SQL", "Docker", "Celery", "MySQL", "API"], "location": ["Україна"]}
{"title": "Python developer (Web scraping expert)", "company": "Ivy Tech Holdings Ltd", "company_type": "Outstaff", "salary": "від $3000", "technologies": ["AWS", "Git", "Python", "BeautifulSoup", "AI", "ML", "Airflow", "SQL", "Scrapy", "API", "Selenium"], "location": ["Сполучені Штати"]}
{"title": "Middle Python Developer з досвідом AI/ML", "company": "GetCode", "company_type": "Outstaff", "salary": "від $2000", "technologies": ["Spark", "AWS", "Python", "AI", "ML"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Wild Wild Leads", "company_type": "Agency", "salary": "$700-800", "technologies": ["Pytest", "Git", "Bootstrap", "Python", "Go", "JavaScript", "HTML", "Flask", "ML", "RabbitMQ", "SQL", "Django", "Celery", "MySQL", "CSS", "Redis"], "location": ["Україна"]}
{"title": "Software Engineer (Python)", "company": "DTEK", "company_type": "Product", "salary": null, "technologies": ["Embers", "Python", "PostgreSQL", "React", "JavaScript", "MongoDB", "AI", "Linux", "MySQL", "SQL", "Java", "Go", "NoSQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Tech Lead Full-stack Engineer (JS/Python)", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["AWS", "Git", "Python", "MongoDB", "AI", "GCP", "SQL", "Django", "Go", "NoSQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Developer for Guardicore", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "AWS", "Git", "Python", "MongoDB", "Azure", "AI", "GCP", "Docker", "Jenkins", "Go", "Linux"], "location": ["Україна"]}
{"title": "Lead Python Developer", "company": "PYGIO", "company_type": "Product", "salary": "$5000-7000", "technologies": ["Python", "PostgreSQL", "AI", "Kubernetes", "SQL", "Django", "Docker", "Go"], "location": ["Україна", "Албанія", "Вірменія", "Польща", "Чехія"]}
{"title": "Python Developer", "company": "FoxmindEd", "company_type": "Product", "salary": null, "technologies": ["SQLAlchemy", "AWS", "Python", "Git", "PostgreSQL", "Go", "HTML", "Flask", "ML", "Linux", "SQL", "Django", "Docker", "OOP", "MySQL", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["Embers", "Git", "Python", "PostgreSQL", "React", "AI", "Flask", "Kubernetes", "Airflow", "SQL", "Jenkins", "Go", "Apache", "JavaScript"], "location": ["Україна"]}
{"title": "Lead Backend Engineer ‍", "company": "Madgicx 🇺🇦", "company_type": "Product", "salary": "$1000-5000", "technologies": ["AWS", "Git", "Python", "PostgreSQL", "Go", "CI/CD", "Flask", "Elasticsearch", "SQL", "Django", "Docker", "Jenkins", "Celery", "MySQL", "API", "Pandas", "Redis"], "location": ["Україна"]}
{"title": "Python Developer in Test (Apps)", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Pytest", "AWS", "Git", "Python", "AI", "ML", "Jenkins", "Linux", "Selenium"], "location": ["Україна"]}
{"title": "Junior/Midle Developer (Python, JavaScript)", "company": "Checkbox", "company_type": "Product", "salary": "$700-1500", "technologies": ["Svelte", "Python", "PostgreSQL", "React", "RESTful", "JavaScript", "MongoDB", "Angular", "Flask", "PHP", "SQL", "Django", "Kafka", "Go", "NoSQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum", "company": "Ciklum International", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["AWS", "Git", "Python", "PostgreSQL", "AI", "Kubernetes", "Airflow", "GCP", "SQL", "Jenkins", "Go", "Apache", "JavaScript"], "location": ["Україна"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8500", "technologies": ["Python", "TensorFlow", "PyTorch", "ML", "Go"], "location": ["Польща", "Україна"]}
{"title": "Odoo/Python Developer", "company": "Sentrium", "company_type": "Product", "salary": null, "technologies": ["Odoo", "Git", "Python", "PostgreSQL", "RESTful", "MongoDB", "AI", "Flask", "SQL", "Django", "Go", "Linux", "API"], "location": ["Україна"]}
{"title": "Python developer (IoT/hardware)", "company": "Canyon Development", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "Go", "Embedded", "Linux", "OOP"], "location": ["Україна"]}
{"title": "Middle Python developer", "company": "Mobius", "company_type": "Product", "salary": "$2500", "technologies": ["Git", "Python", "HTML", "ML", "SQL", "Linux", "API", "CSS"], "location": ["Україна"]}
{"title": "Strong Middle / Senior Python Developer", "company": "TECHIIA Holding", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Celery", "Python", "Scrum", "PostgreSQL", "CI/CD", "Go", "AI", "Angular", "SQL", "Django", "Black", "Elasticsearch", "API", "Redis"], "location": ["Україна"]}
{"title": "Junior Python Developer Portugal only", "company": "Adaptiq", "company_type": "Product", "salary": "до $2500", "technologies": ["Git", "AWS", "Python", "Dash", "AI", "GCP", "Go"], "location": ["Португалія"]}
{"title": "Python developer", "company": "NestLogic", "company_type": "Product", "salary": null, "technologies": ["Python", "AI", "Jupyter Notebook", "Kubernetes", "ML", "Docker", "Go", "Linux"], "location": ["Україна"]}
{"title": "Full Stack Developer (Python,React) Miami location", "company": "Global Teams", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "PostgreSQL", "React", "CI/CD", "RESTful", "MongoDB", "AI", "Flask", "Redux", "GCP", "SQL", "Django", "Jenkins", "Go", "MySQL", "API"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python)  (Warsaw)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": null, "technologies": ["DevOps", "AWS", "Mlops", "Python", "Go", "React", "AI", "TensorFlow", "ML", "Node.Js", "OOP", "API"], "location": ["Польща"]}
{"title": "Senior Python Developer", "company": "UKR.NET", "company_type": "Product", "salary": "$1000-5000", "technologies": ["Python", "PostgreSQL", "aiohttp", "MongoDB", "AI", "Elasctisearch", "Elasticsearch", "MySQL", "SQL", "Go", "NoSQL", "API", "Redis", "asyncio"], "location": ["Україна"]}
{"title": "DevOps Engineer (with Golang or Python)", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Git", "Sdn", "Python", "CI/CD", "AI", "Kubernetes", "ML", "Docker", "Go", "API"], "location": ["Азербайджан", "Молдова", "Польща", "Туреччина", "Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "AI", "Moment", "Go", "Click", "API"], "location": ["Україна"]}
{"title": "Junior/Middle Python developer in test", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Pytest", "AWS", "Git", "Python", "PySide", "PyQt", "ML", "Jenkins", "Linux", "API"], "location": ["Україна"]}
{"title": "Python/Django", "company": "Perlyna Devs", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Go", "AI", "Python", "Django"], "location": ["Україна"]}
{"title": "Back End Developer", "company": "Nashpush", "company_type": "Product", "salary": null, "technologies": ["AWS", "Python", "Go", "AI", "Flask", "Saas", "Kubernetes", "Django", "Docker", "OOP", "API"], "location": ["Кіпр", "Україна"]}
{"title": "Computer Vision Engineer", "company": "tangiblee", "company_type": "Product", "salary": "від $2000", "technologies": ["Python", "OpenCV", "AI", "TensorFlow", "PyTorch", "Scipy", "NumPy", "Go"], "location": ["Україна"]}
{"title": "Middle\\Senior Backend Engineer ( Python)", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5500", "technologies": ["Embers", "AWS", "Git", "Python", "Go", "GraphQL", "AI", "TypeScript", "RabbitMQ", "Ansible", "Django", "Docker", "Kafka", "Node.Js", "Celery", "API", "JavaScript", "asyncio"], "location": ["Україна"]}
{"title": "Sr Python Engineer", "company": "Zaly", "company_type": "Product", "salary": null, "technologies": ["Highload", "Python", "PostgreSQL", "Ansible", "SQL", "Docker"], "location": ["Україна", "Сполучені Штати"]}
{"title": "Python developer / strong junior", "company": "dZENcode", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["AWS", "Git", "Python", "AI", "TensorFlow", "SQL", "Django", "Go", "NoSQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Developer (with ML/AI  background)", "company": "Cyberspectr Solution", "company_type": "Outstaff", "salary": null, "technologies": ["Git", "AWS", "Python", "Scikit-learn", "CI/CD", "AI", "TensorFlow", "PyTorch", "NumPy", "Docker", "Pandas"], "location": ["Україна"]}
{"title": "Senior / Lead Technical Support Developer", "company": "ApomSolutions", "company_type": "Outstaff", "salary": "до $6000", "technologies": ["Spark", "AWS", "Python", "Java", "AI", "Azure", "Kubernetes", "GCP", "Docker", "Oracle", "OOP"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "P2H", "company_type": "Outstaff", "salary": null, "technologies": ["Bootstrap", "Angular", "HTML", "Kubernetes", "Go", "MySQL", "Git", "Node.Js", "Vue.Js", "Embers", "jQuery", "Python", "PHP", "CSS", "Redis", "React", "PostgreSQL", "AI", "ML", "RabbitMQ", "SQL", "Elasticsearch", "Redux", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Develux", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "AWS", "Python", "PostgreSQL", "GraphQL", "CI/CD", "AI", "Azure", "Flask", "SQL", "Django", "Docker", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Software Rocket", "company_type": "Outstaff", "salary": "$3000-5000", "technologies": ["Python", "React", "Angular", "AI", "Flask", "Django", "Go", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Full-stack (JS/Python) / Tech lead", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["AWS", "Git", "Python", "MongoDB", "AI", "GCP", "SQL", "Django", "Go", "NoSQL", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Python Developer  (DCOS)", "company": "OSF Digital", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["Git", "Python", "React", "RESTful", "AI", "SQL", "Agile", "Go", "API"], "location": ["Польща", "Румунія", "Туреччина", "Україна"]}
{"title": "Python Developer for Training Neural Networks", "company": "Digifico", "company_type": "Product", "salary": null, "technologies": ["Python", "TensorFlow", "PyTorch", "SQL", "Keras", "Go", "NoSQL"], "location": ["Україна"]}
{"title": "Python developer", "company": "Peppernode", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "AWS", "Git", "Python", "CI/CD", "Flask", "Kubernetes", "Microservices", "Django", "Docker", "Go", "API"], "location": ["Україна"]}
{"title": "Python Developer for Automotive Project", "company": "Luxoft", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["DevOps", "Pyramid", "Git", "Python", "React", "Angular", "AI", "Flask", "Ansible", "Django", "Docker", "Go", "API", "Vue.Js"], "location": ["Польща"]}
{"title": "Python/Django Developer", "company": "ECHOES", "company_type": "Product", "salary": "$800-2000", "technologies": ["AWS", "Celery", "Python", "PostgreSQL", "Go", "GraphQL", "AI", "Kubernetes", "RabbitMQ", "SQL", "Django", "Docker", "Nginx", "Elasticsearch", "Linux", "Redis"], "location": ["Грузія", "Україна"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Pyramid", "Git", "Python", "React", "Angular", "AI", "Flask", "Django", "Docker", "Go", "API", "Vue.Js"], "location": ["Польща"]}
{"title": "Middle Python Developer", "company": "Starnavi", "company_type": "Outstaff", "salary": null, "technologies": ["FastAPI", "Embers", "Python", "React", "Angular", "RESTful", "AI", "Flask", "Kubernetes", "Linux", "Foundation", "SQL", "Django", "Docker", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Python developer", "company": "Odore", "company_type": "Product", "salary": null, "technologies": ["Pytest", "Postman", "SQLAlchemy", "Python", "AWS", "Git", "PostgreSQL", "AI", "SQL", "Go", "API"], "location": ["Велика Британія"]}
{"title": "Python Tech Lead", "company": "Dataforest", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Embers", "AWS", "Python", "AI", "Flask", "Kubernetes", "Airflow", "Elasticsearch", "GCP", "SQL", "Django", "Docker", "Kafka", "Go", "NoSQL", "Pandas", "Redis"], "location": ["Німеччина", "Польща", "Словаччина", "Україна"]}
{"title": "Python Software Engineer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "Spark", "AWS", "Python", "Go", "AI", "Flask", "SQL", "Kafka", "OOP", "NoSQL", "API", "Postgres", "Redis"], "location": ["Польща", "Словаччина", "Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": null, "technologies": ["DevOps", "AWS", "Python", "Go", "CI/CD", "MongoDB", "AI", "Flask", "Airflow", "OOP", "Apache", "API"], "location": ["Україна"]}
{"title": "Backend Python/Django Developer for a SaaS Product", "company": "Iteksas", "company_type": "Product", "salary": "$2700-3500", "technologies": ["Python", "Go", "HTML", "Saas", "ML", "Product", "SQL", "Django", "Celery", "NoSQL", "CSS"], "location": ["Литва", "Україна"]}
{"title": "Backend Python Developer", "company": "DevIT Group", "company_type": "Outsource", "salary": "$900-1500", "technologies": ["FastAPI", "Langchain", "AWS", "Git", "Python", "AI", "Azure", "RabbitMQ", "SQL", "Django", "Docker", "Go", "Linux", "API", "Redis"], "location": ["Україна"]}
{"title": "LLM developer", "company": "SerenityGPT", "company_type": "Product", "salary": "$1800-2400", "technologies": ["Go", "AI", "Nlp", "ChatGPT"], "location": ["Велика Британія"]}
{"title": "Experienced Odoo Developer", "company": "hts-experts.com", "company_type": "Product", "salary": "$700-800", "technologies": ["Odoo", "Git", "Embers", "Python", "PostgreSQL", "Requests", "JavaScript", "AI", "HTML", "ML", "SQL", "Go", "Linux", "CSS", "Troubleshooting"], "location": ["Швейцарія"]}
{"title": "Python Developer", "company": "4K-Soft", "company_type": "Outsource", "salary": "$700-1500", "technologies": ["Git", "Python", "Go", "MongoDB", "AI", "SQL", "Docker", "OOP", "MySQL", "Mondodb"], "location": ["Україна"]}
{"title": "Parsing expert for a long term partnership", "company": "WebDev 247", "company_type": "Product", "salary": null, "technologies": ["Python", "HTML", "AI", "ML", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "strong Python over Django dev", "company": "Flexyti", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["AWS", "Python", "PostgreSQL", "Go", "CI/CD", "MongoDB", "AI", "Kubernetes", "SQL", "Django", "Docker", "OOP"], "location": ["Україна"]}
{"title": "Senior Python developer (AWS)", "company": "TemaBit Fozzy Group", "company_type": "Product", "salary": null, "technologies": ["AWS", "Git", "Python", "CI/CD", "AI", "SQL", "OOP", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Django)", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Python", "PostgreSQL", "CI/CD", "MongoDB", "AI", "Kubernetes", "SQL", "Django", "Docker", "Go"], "location": ["Україна"]}
{"title": "Middle Python Developer (Django Framework)", "company": "NeoFin", "company_type": "Product", "salary": "$2000", "technologies": ["OpenCV", "HTML", "Django", "Go", "MySQL", "Git", "RESTful", "Finance", "Node.Js", "Vue.Js", "Python", "Flask", "CSS", "Redis", "React", "PostgreSQL", "AI", "ML", "SQL", "Elasticsearch", "API", "JavaScript"], "location": ["Малайзія", "Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Flexyti", "company_type": "Outsource", "salary": "до $2800", "technologies": ["AWS", "Senior", "Python", "Git", "RESTful", "HTML", "Flask", "ML", "MySQL", "SQL", "Django", "Go", "NoSQL", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Data Engineer", "company": "Competera", "company_type": "Product", "salary": null, "technologies": ["Apache", "Spark", "Python", "Luigi", "AI", "Airflow", "GCP", "SQL", "Kafka", "Go", "Click"], "location": ["Кіпр", "Україна"]}
{"title": "Solidity/Blockchain expert (Smart Contract)", "company": "WeSoftYou", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "Solidity", "React", "AI", "OOP"], "location": ["Україна"]}
{"title": "Software and MLOps Engineer (Python) (Poland)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2000", "technologies": ["DevOps", "AWS", "Mlops", "Python", "React", "AI", "TensorFlow", "ML", "Node.Js", "OOP", "API"], "location": ["Ізраїль", "Польща"]}
{"title": "Senior Python Developer", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["AWS", "Python", "aiohttp", "CI/CD", "AI", "Kubernetes", "RabbitMQ", "Docker", "Tornado", "Go", "Redis"], "location": ["Словаччина", "Україна"]}
{"title": "Middle/Senior Python Software Developer (or switcher from another OOP language)", "company": "Jito.dev", "company_type": "Outsource", "salary": "$3000-5000", "technologies": ["DevOps", "AWS", "Git", "Python", "PostgreSQL", "Go", "CI/CD", "AI", "Gis", "Kubernetes", "SQL", "OOP", "Linux"], "location": ["Україна"]}
{"title": "Software Python Developer", "company": "Capital Recruiters", "company_type": "Product", "salary": "$3000-5000", "technologies": ["React", "Python", "Flask", "SQL", "Django", "API"], "location": ["Україна"]}
{"title": "Quality Assurance Architect (Networking)", "company": "PLVision", "company_type": "Outsource", "salary": null, "technologies": ["Pytest", "Embers", "Robot Framework", "Python", "Go", "CI/CD", "AI", "Kubernetes", "Unittest", "Ansible", "Networking", "Docker", "Linux", "API", "Automation", "Architect"], "location": ["Україна"]}
{"title": "Team Lead Python", "company": "Capital Recruiters", "company_type": "Product", "salary": null, "technologies": ["React", "Python", "Flask", "SQL", "Django", "API"], "location": ["Україна"]}
{"title": "Python/Django Full Stack Developer", "company": "BikeBUBL", "company_type": "Product", "salary": "$1500-2800", "technologies": ["Python", "Vue", "PostgreSQL", "AI", "Frontend", "SQL", "Js", "Django", "Go", "Vue.Js"], "location": ["Велика Британія", "Україна"]}
{"title": "QA Engineer (Performance testing)", "company": "SeekIT", "company_type": "Outsource", "salary": "від $2000", "technologies": ["Python", "CI/CD", "AI", "ML", "SQL", "Java", "Jenkins", "Elasticsearch", "API", "JavaScript"], "location": ["Латвія"]}
{"title": "Python Developer", "company": "Ava Technologies Inc.", "company_type": "Product", "salary": null, "technologies": ["Serverless", "Embers", "AWS", "Python", "MongoDB", "AI", "ChatGPT", "Go"], "location": ["Чехія", "Нідерланди"]}
{"title": "Middle Python Software Engineer", "company": "teeko.", "company_type": "Product", "salary": "до $2000", "technologies": ["FastAPI", "Python", "PostgreSQL", "GraphQL", "SQL", "Go", "API"], "location": ["Україна", "Ізраїль"]}
{"title": "Senior Python Engineer", "company": "KnubiSoft", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Embers", "AWS", "Python", "Go", "GraphQL", "AI", "Django", "OOP", "API", "CSS"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "AI", "Moment", "Go", "Click", "API"], "location": ["Україна"]}
{"title": "Python Developer", "company": "AUTODOC", "company_type": "Product", "salary": "$1500-3000", "technologies": ["DevOps", "Python", "AI", "ML", "Streamlit", "Go", "API"], "location": ["Молдова", "Польща", "Португалія", "Україна"]}
{"title": "Python developer", "company": "Software Development Hub", "company_type": "Outsource", "salary": "до $2800", "technologies": ["jQuery", "Python", "PostgreSQL", "Go", "HTML", "ML", "Linux", "SQL", "Django", "Docker", "OOP", "NoSQL", "API", "CSS", "Redis"], "location": ["Україна"]}
{"title": "AI Enthusiast / Machine Learning", "company": "King's Choice", "company_type": "Product", "salary": null, "technologies": ["AI", "Python", "ChatGPT"], "location": ["Україна"]}
{"title": "Middle Python+Java Developer IRC183577", "company": "GlobalLogic", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Git", "Python", "RESTful", "AI", "SQL", "Java", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Python Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$5000-7000", "technologies": ["AWS", "Git", "Python", "RESTful", "HTML", "AI", "Kubernetes", "ML", "Foundation", "Docker", "Go", "API", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": "$3000-4200", "technologies": ["DevOps", "AI", "Python"], "location": ["Україна"]}
{"title": "Python/GoLang developer (Europe)", "company": "TEAM International", "company_type": "Outstaff", "salary": null, "technologies": ["Python", "AI", "Kubernetes", "Foundation", "GCP", "SQL", "Django", "Go", "NoSQL", "API"], "location": ["Польща", "Португалія"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["AI", "DevOps", "Crossplatform", "Python"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $9000", "technologies": ["AWS", "Python", "CI/CD", "AI", "Azure", "Kubernetes", "GCP", "Ansible", "Docker", "Go", "API"], "location": ["Україна"]}
{"title": "Full Stack Engineer", "company": "Glorium Technologies", "company_type": "Outsource", "salary": null, "technologies": ["DevOps", "Embers", "Git", "Python", "Go", "GraphQL", "React", "AI", "Kubernetes", "Docker", "OOP", "API"], "location": ["Україна", "Польща", "Кіпр"]}
{"title": "Senior Python Developer", "company": "Bluefield Technologies", "company_type": "Product", "salary": "$5000-6000", "technologies": ["HTML", "TypeScript", "Go", "Linux", "Ccna", "Git", "RESTful", "Docker", "Python", "CSS", "Pandas", "React", "aiohttp", "AI", "ML", "SQL", "Networking", "API", "Backbone", "asyncio"], "location": ["Словаччина", "Україна"]}
{"title": "Python Engineer", "company": "APOSTERA UA HARMAN", "company_type": "Product", "salary": null, "technologies": ["DevOps", "Senior", "Git", "Python", "AI", "ML", "Docker", "API", "Linux", "Automotive", "Middle", "Automation"], "location": ["Угорщина", "Польща", "Україна"]}
{"title": "Middle/Senior BackEnd developer Python/Django", "company": "Meest China", "company_type": "Product", "salary": null, "technologies": ["AWS", "Git", "Python", "Go", "RESTful", "AI", "Wagtail", "SQL", "Django", "JWT", "Jenkins", "Nginx", "Celery", "MySQL", "API", "Redis"], "location": ["Україна"]}
{"title": "Senior Cloud Developer", "company": "Alcor", "company_type": "Product", "salary": "$2000-5000", "technologies": ["AWS", "Python", "JavaScript", "AI", "Cloud", "SQL", "NoSQL", "API", "Vue.Js"], "location": ["Чехія", "Польща", "Румунія", "Словаччина", "Україна"]}
{"title": "Senior Algorithms Developer (Speech Recognition, Python)", "company": "SD Solutions", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["Embers", "Python", "AI", "TensorFlow", "PyTorch", "ML", "Go", "API"], "location": ["Кіпр", "Грузія", "Польща", "Україна"]}
{"title": "Strong Junior / Middle Python Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "$1000-2500", "technologies": ["Angular", "HTML", "Django", "Go", "OOP", "MySQL", "Linux", "Git", "Docker", "Python", "Webpack", "Celery", "Pandas", "Redis", "CSS", "Orm", "React", "PostgreSQL", "AI", "ML", "RabbitMQ", "SQL", "API"], "location": ["Україна"]}
{"title": "Python Developer for EdTech company", "company": "Projector", "company_type": "Product", "salary": "до $2800", "technologies": ["AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python  Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "Go", "AI", "ML", "OOP"], "location": ["Португалія"]}
{"title": "Python Developer - work only from Poland", "company": "Luxoft", "company_type": "Outsource", "salary": "$2500-3700", "technologies": ["Embers", "Dash", "Python", "Matplotlib", "AI", "NumPy", "SQL", "Go", "Pandas", "Plotly"], "location": ["Польща"]}
{"title": "Senior Python/DevOps Developer", "company": "Chrysalis Gate", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["DevOps", "Spark", "AWS", "Git", "Python", "React", "AI", "Moment", "Kafka", "API", "Redis"], "location": ["Литва", "Україна", "Польща", "Словаччина", "Румунія"]}
{"title": "Python Developer/Data Engineer", "company": "Ajax Systems", "company_type": "Product", "salary": null, "technologies": ["Git", "AWS", "Python", "OpenCV", "AI", "TensorFlow", "PyTorch", "ML", "NumPy", "Pandas"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with ML experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Ocr", "Python", "Angular", "AI", "ML", "Node.Js", "Go"], "location": ["Естонія", "Польща", "Україна"]}
{"title": "Odoo Engineer", "company": "OpsWay", "company_type": "Outsource", "salary": null, "technologies": ["Odoo", "Python", "PostgreSQL", "Xml", "JavaScript", "Owl"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data skills", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Spark", "AWS", "Python", "Go", "AI", "SQL", "OOP"], "location": ["Україна"]}
{"title": "Middle Backend Developer", "company": "Partner-way", "company_type": "Product", "salary": null, "technologies": ["Requests", "Python", "TypeScript", "Go", "API", "JavaScript"], "location": ["Велика Британія", "Сполучені Штати", "Україна", "Німеччина", "Польща"]}
{"title": "Python Developer", "company": "SKILLUP", "company_type": "Product", "salary": "до $2800", "technologies": ["Python", "HTML", "AI", "ML", "SQL", "Django", "Go", "CSS"], "location": ["Україна"]}
{"title": "Програміст на Django 1.9.0", "company": "GlutenOff.ua", "company_type": "Product", "salary": null, "technologies": ["Python", "PostgreSQL", "HTML", "ML", "SQL", "Django", "Docker", "Nginx", "Gulp", "Go", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Data Scientist for the oil and gas data prediction solutions", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Scikit-learn", "Python", "AI", "TensorFlow", "Azure", "NumPy", "SQL", "Go", "Pandas"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "Mobilunity", "company_type": "Outsource", "salary": null, "technologies": ["Playready", "AWS", "Dash", "Python", "Requests", "AI", "Azure", "Go", "API", "Fairplay"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "InventorSoft", "company_type": "Outstaff", "salary": "$3000-4000", "technologies": ["DevOps", "FastAPI", "Python", "SQL", "MySQL", "API"], "location": ["Україна"]}
{"title": "Python developer (US IoT project)", "company": "Romen Personnel", "company_type": "Product", "salary": "$1000-2500", "technologies": ["AWS", "Python", "AI", "Iot", "PHP", "SQL", "OOP"], "location": ["Сполучені Штати"]}
{"title": "Corsound AI - Senior Algorithms Developer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$3000-4000", "technologies": ["Embers", "Python", "AI", "TensorFlow", "PyTorch", "Algorithms", "Go", "API"], "location": ["Україна", "Грузія"]}
{"title": "Senior Data Scientist for the oil and gas industry", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Scikit-learn", "Python", "TensorFlow", "Azure", "NumPy", "SQL", "Go", "Pandas"], "location": ["Україна"]}
{"title": "Algorithm Developer for Corsound AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$2000-5000", "technologies": ["Embers", "Python", "AI", "TensorFlow", "PyTorch", "Algorithms", "Go", "API"], "location": ["Грузія", "Польща", "Україна"]}
{"title": "Python Engineer", "company": "GlobalLogic", "company_type": "Outsource", "salary": "до $2000", "technologies": ["Apache", "Spark", "Git", "AWS", "Python", "PostgreSQL", "CI/CD", "MongoDB", "AI", "Moment", "Airflow", "SQL", "Go", "MySQL", "Redis"], "location": ["Румунія"]}
{"title": "Middle Python Developer", "company": "SoftVision", "company_type": "Outsource", "salary": null, "technologies": ["Apache", "Spark", "AWS", "Git", "Python", "PostgreSQL", "AI", "Flask", "Kubernetes", "SQL", "Django", "Docker", "Go", "MySQL", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Quickstaffing LLC", "company_type": "Outstaff", "salary": null, "technologies": ["Spark", "Python", "AI", "Jupyter Notebook", "SQL", "Go", "Pandas"], "location": ["Вірменія"]}
{"title": "Middle/Senior Python/Go Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["Git", "Python", "AI", "ML", "Go", "API", "JavaScript"], "location": ["Польща", "Сербія", "Португалія"]}
{"title": "Middle+/Senior Python developer", "company": "TechbrainJobs", "company_type": "Product", "salary": "$3000-5000", "technologies": ["Git", "Drf", "Python", "PostgreSQL", "aiohttp", "Mongo", "Go", "AI", "Angular", "Elasticsearch", "SQL", "Django", "Nginx", "Celery", "Redis"], "location": ["Україна"]}
{"title": "Mid-Senior Python developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "$30-35", "technologies": ["Go", "AI", "API", "Python"], "location": ["Польща"]}
{"title": "Python Developer", "company": "S-PRO", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "Celery", "Python", "PostgreSQL", "Go", "React", "AI", "RabbitMQ", "Airflow", "SQL", "Django", "Docker", "Node.Js", "OOP", "Pandas", "Redis"], "location": ["Польща", "Україна"]}
{"title": "Senior Software Engineer (DataDiscovery)", "company": "MEGOGO", "company_type": "Product", "salary": "$1000-5000", "technologies": ["Apache", "Spark", "AWS", "Python", "PostgreSQL", "Go", "MongoDB", "Kubernetes", "Click", "SQL", "Docker", "Kafka", "OOP", "MySQL", "API"], "location": ["Україна"]}
{"title": "Python/Golang Developer (Hospitality industry)", "company": "Coherent Solutions", "company_type": "Outsource", "salary": null, "technologies": ["Python", "AI", "Kubernetes", "Foundation", "SQL", "Django", "Go", "NoSQL", "API", "Golang"], "location": ["Польща", "Грузія", "Литва", "Болгарія", "Румунія"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "AWS", "Git", "Python", "MongoDB", "Azure", "AI", "GCP", "Docker", "Jenkins", "Go", "Linux"], "location": ["Україна"]}
{"title": "Python Back-End Engineer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["AWS", "Python", "CI/CD", "AI", "Azure", "Kubernetes", "ML", "GCP", "Redis"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "level99.vip", "company_type": "Product", "salary": null, "technologies": ["Postman", "Requests", "HTML", "Kubernetes", "Git", "GraphQL", "Docker", "Apache", "Python", "Nginx", "NoSQL", "SQLAlchemy", "AI", "ML", "RabbitMQ", "SQL", "Kafka", "API", "Selenium"], "location": ["Україна"]}
{"title": "Middle Python Software Engineer (Prom.ua)", "company": "EVO", "company_type": "Product", "salary": null, "technologies": ["Kubernetes", "Go", "Git", "Docker", "Python", "CI/CD", "Webpack", "CSS", "Redis", "React", "PostgreSQL", "MongoDB", "RabbitMQ", "SQL", "Kafka", "Elasticsearch", "Click", "API", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Unidatalab", "company_type": "Product", "salary": null, "technologies": ["FastAPI", "AWS", "Git", "Python", "AI", "Azure", "Kubernetes", "ChatGPT", "GCP", "SQL", "Django", "Docker", "Kafka", "Go", "NoSQL", "API"], "location": ["Україна"]}
{"title": "Senior Appian Developer", "company": "DICEUS", "company_type": "Outstaff", "salary": "$3000-6000", "technologies": ["Embers", "Sail", "Git", "AI", "Appian", "SQL", "Go", "API", "JavaScript"], "location": ["Йорданія", "Польща", "Україна"]}
{"title": "Python Full Stack Developer", "company": "Atto Trading", "company_type": "Product", "salary": "$2000-5000", "technologies": ["DevOps", "Git", "Python", "React", "Angular", "HTML", "AI", "ML", "TypeScript", "Linux", "Foundation", "PHP", "Click", "SQL", "Node.Js", "Go", "MySQL", "CSS"], "location": ["Україна"]}
{"title": "Senior Backend Engineer for Neolithics AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["AWS", "Python", "CI/CD", "AI", "Azure", "Kubernetes", "ML", "GCP", "Go", "Redis"], "location": ["Україна"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$4000-5500", "technologies": ["DevOps", "Python", "PyTorch", "ML", "OOP", "API"], "location": ["Україна"]}
{"title": "Tech/Team Lead (Python)", "company": "Indigo Tech recruitment", "company_type": "Product", "salary": "$3500-5000", "technologies": ["FastAPI", "AWS", "Python", "PostgreSQL", "AI", "PyTorch", "ML", "SQL", "Go", "API", "Pandas"], "location": ["Франція"]}
{"title": "Senior Backend Engineer (Python)", "company": "Super Dispatch", "company_type": "Product", "salary": "$5000-6500", "technologies": ["AWS", "Python", "CI/CD", "AI", "Kubernetes", "GCP", "Django", "Go", "API", "Ddd"], "location": ["Узбекистан"]}
{"title": "Python Engineer", "company": "Respeecher", "company_type": "Product", "salary": "$4000-5500", "technologies": ["DevOps", "Python", "PyTorch", "ML", "API"], "location": ["Україна"]}
{"title": "Python developer", "company": "Flyaps", "company_type": "Outsource", "salary": "до $2800", "technologies": ["Git", "Python", "CI/CD", "AI", "SQL", "Django", "Go", "Linux", "CSS", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with OCR experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "Ocr", "Python", "Angular", "AI", "ML", "Node.Js", "Go"], "location": ["Україна"]}
{"title": "Python Developer (Data-driven)", "company": "TechbrainJobs", "company_type": "Product", "salary": "$6000-8000", "technologies": ["AWS", "Git", "Python", "CI/CD", "AI", "SQL", "Docker", "Go", "Linux", "API"], "location": ["Ізраїль"]}
