{"title": "Developer for AI ChatGPT bot", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI"], "location": ["Україна", "Польща"]}
{"title": "Backend Developer for AutoGPT", "company": "44gifts corp", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Python", "Git"], "location": ["Україна", "Польща"]}
{"title": "Python developer", "company": "Olearis", "company_type": "Outsource", "salary": "$1000-2500", "technologies": ["AWS", "AI", "OOP", "PostgreSQL", "Requests", "Python", "SQLAlchemy", "FastAPI", "Go", "SQL", "API"], "location": ["Україна"]}
{"title": "Junior Python Developer Portugal only", "company": "Adaptiq", "company_type": "Product", "salary": "до $2500", "technologies": ["AWS", "AI", "Dash", "GCP", "Python", "Git", "Go"], "location": ["Португалія"]}
{"title": "Strong Junior/Middle Data Scientist", "company": "AppReal", "company_type": "Outstaff", "salary": "$600-3500", "technologies": ["Embers", "AI", "Linux", "Python", "PySpark", "Go", "Spark"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Wild Wild Leads", "company_type": "Agency", "salary": "$700-800", "technologies": ["MySQL", "Redis", "Pytest", "Python", "Git", "ML", "RabbitMQ", "Flask", "Celery", "Bootstrap", "HTML", "Go", "SQL", "JavaScript", "Django", "CSS"], "location": ["Україна"]}
{"title": "Python/Django REST API Backend Developer", "company": "Smart UI", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["MySQL", "DevOps", "NoSQL", "Backend", "AI", "PostgreSQL", "jQuery", "HTML", "SQL", "Crypto", "API", "Python", "Git", "Go", "JavaScript", "Django", "CSS", "AWS", "Linux", "PHP", "ML", "Angular", "Docker", "React", "MongoDB"], "location": ["Україна"]}
{"title": "Python Developer - AI Automation Solutions (LLaMA, ChatGPT Agents, Auto-GPT, LangChain)", "company": "Aimech", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Python", "ML", "Langchain", "Nlp", "FastAPI", "ChatGPT", "Llm", "API"], "location": ["Велика Британія", "Україна"]}
{"title": "Database Developer", "company": "DATAWIZ", "company_type": "Product", "salary": null, "technologies": ["MySQL", "PostgreSQL", "Linux", "Pandas", "Redis", "Python", "ML", "RabbitMQ", "Angular", "Celery", "Webpack", "HTML", "Go", "SQL", "React", "Etl", "Django", "CSS"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "AI", "BeautifulSoup", "Pandas", "Selenium", "NoSQL", "Python", "ML", "Flask", "HTML", "Scraping", "SQL", "API"], "location": ["Польща", "Україна"]}
{"title": "DAAS Support ENG", "company": "Temerix", "company_type": "Product", "salary": "$700-800", "technologies": ["AI", "Requests", "Moment", "NoSQL", "Python", "ML", "HTML", "Go", "SQL", "CSS"], "location": ["Україна"]}
{"title": "Application Engineer", "company": "UnameIT", "company_type": "Product", "salary": null, "technologies": ["AI", "Python", "Git", "Fabric"], "location": ["Україна"]}
{"title": "Junior Python Developer", "company": "AgileEngine", "company_type": "Outsource", "salary": null, "technologies": ["AWS", "AI", "Python", "Git", "Postman", "Go", "API", "CI/CD"], "location": ["Україна"]}
{"title": "Python NLP Developer", "company": "Tangible AI", "company_type": "Agency", "salary": null, "technologies": ["AI", "Python", "Git", "Nlp", "Go", "Django", "CI/CD"], "location": ["Сполучені Штати"]}
{"title": "Junior software engineer (parsing/reverse)", "company": "Artellence", "company_type": "Product", "salary": "до $2500", "technologies": ["NoSQL", "AI", "Requests", "Redis", "SQL", "API", "Selenium", "Python", "Java", "asyncio", "Parsing", "Go", "JavaScript", "BeautifulSoup", "Linux", "aiohttp", "Docker", "Security", "MongoDB"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "level99.vip", "company_type": "Product", "salary": null, "technologies": ["NoSQL", "Nginx", "AI", "Requests", "HTML", "SQL", "API", "Apache", "Selenium", "Python", "Git", "RabbitMQ", "GraphQL", "Kafka", "Kubernetes", "ML", "Docker", "Postman", "SQLAlchemy"], "location": ["Україна"]}
{"title": "Junior Python Developer (Scraping) for AI Software Product", "company": "Simporter", "company_type": "Product", "salary": "$600-3500", "technologies": ["RESTful", "AI", "Elasticsearch", "Scrapy", "NoSQL", "Python", "RabbitMQ", "Go", "SQL", "Airflow", "API"], "location": ["Україна"]}
{"title": "Strong Junior Backend Python Developer", "company": "DevIT Group", "company_type": "Outsource", "salary": "$900-1500", "technologies": ["AWS", "AI", "Linux", "Redis", "Python", "Azure", "Git", "RabbitMQ", "Langchain", "Docker", "FastAPI", "Go", "SQL", "Django", "API"], "location": ["Україна"]}
{"title": "Odoo Engineer", "company": "OpsWay", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["PostgreSQL", "Odoo", "Python", "Xml", "Owl", "JavaScript"], "location": ["Україна"]}
{"title": "Python developer / strong junior", "company": "dZENcode", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["AWS", "AI", "NoSQL", "Python", "Git", "TensorFlow", "Go", "SQL", "JavaScript", "Django", "API"], "location": ["Україна"]}
{"title": "Python developer (US IoT project)", "company": "Romen Personnel", "company_type": "Product", "salary": "$1000-2500", "technologies": ["AWS", "AI", "OOP", "Python", "PHP", "SQL", "Iot"], "location": ["Сполучені Штати"]}
{"title": "Strong Junior / Middle Python Developer", "company": "DATAWIZ", "company_type": "Product", "salary": "$1000-2500", "technologies": ["MySQL", "AI", "PostgreSQL", "Pandas", "Redis", "Webpack", "HTML", "SQL", "API", "OOP", "Python", "Git", "RabbitMQ", "Celery", "Go", "Django", "CSS", "Linux", "ML", "Angular", "Docker", "React", "Orm"], "location": ["Україна"]}
{"title": "Middle Python Developer (Django Framework)", "company": "NeoFin", "company_type": "Product", "salary": "$2000", "technologies": ["MySQL", "Finance", "RESTful", "AI", "PostgreSQL", "Redis", "HTML", "Node.Js", "SQL", "OpenCV", "Vue.Js", "API", "Python", "Git", "Go", "JavaScript", "Django", "CSS", "ML", "Flask", "Elasticsearch", "React"], "location": ["Малайзія", "Польща", "Україна"]}
{"title": "Software and MLOps Engineer (Python) (Poland)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2000", "technologies": ["AWS", "AI", "OOP", "DevOps", "Python", "TensorFlow", "ML", "Mlops", "Node.Js", "React", "API"], "location": ["Ізраїль", "Польща"]}
{"title": "Parsing expert for a long term partnership", "company": "WebDev 247", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Python", "ML", "HTML", "CSS", "JavaScript", "API"], "location": ["Україна"]}
{"title": "Python/Django Developer", "company": "ECHOES", "company_type": "Product", "salary": null, "technologies": ["AWS", "AI", "PostgreSQL", "Linux", "Kubernetes", "Redis", "Python", "RabbitMQ", "GraphQL", "Celery", "Go", "Docker", "Nginx", "Elasticsearch", "SQL", "Django"], "location": ["Грузія", "Україна"]}
{"title": "Experienced Odoo Developer", "company": "hts-experts.com", "company_type": "Product", "salary": null, "technologies": ["Embers", "AI", "PostgreSQL", "Requests", "Odoo", "Linux", "Python", "Git", "ML", "Troubleshooting", "HTML", "Go", "SQL", "JavaScript", "CSS"], "location": ["Швейцарія"]}
{"title": "Python/Django", "company": "Perlyna Devs", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Go", "AI", "Python", "Django"], "location": ["Україна"]}
