{"title": "Python Engineer", "company": "Jungle Consulting", "company_type": "Product", "salary": "до $2500", "technologies": ["API", "HTML", "JavaScript", "AI", "Git", "AWS", "Mentoring", "Linux", "Docker", "Python", "ML", "CSS"], "location": ["Україна"]}
{"title": "Python developer", "company": "Olearis", "company_type": "Outsource", "salary": null, "technologies": ["FastAPI", "API", "Requests", "SQL", "Go", "AI", "SQLAlchemy", "AWS", "OOP", "PostgreSQL", "Python"], "location": ["Україна"]}
{"title": "Junior Python Developer Portugal only", "company": "Adaptiq", "company_type": "Product", "salary": "до $2500", "technologies": ["GCP", "Go", "Git", "AI", "Dash", "AWS", "Python"], "location": ["Португалія"]}
{"title": "Python/Django REST API Backend Developer", "company": "Smart UI", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["React", "NoSQL", "Git", "Crypto", "Angular", "JavaScript", "Go", "MySQL", "Backend", "Docker", "API", "MongoDB", "ML", "PHP", "Django", "SQL", "AI", "jQuery", "PostgreSQL", "Python", "HTML", "DevOps", "AWS", "Linux", "CSS"], "location": ["Україна"]}
{"title": "Strong Junior/Middle Data Scientist", "company": "AppReal", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "AI", "Embers", "Linux", "PySpark", "Python", "Spark"], "location": ["Україна"]}
{"title": "Middle Python Developer", "company": "Wild Wild Leads", "company_type": "Agency", "salary": "$700-800", "technologies": ["Django", "Flask", "HTML", "Redis", "SQL", "JavaScript", "Go", "Git", "Bootstrap", "Celery", "Pytest", "RabbitMQ", "MySQL", "Python", "ML", "CSS"], "location": ["Україна"]}
{"title": "Python Developer - AI Automation Solutions (LLaMA, ChatGPT Agents, Auto-GPT, LangChain)", "company": "Aimech", "company_type": "Product", "salary": "$600-3500", "technologies": ["FastAPI", "Langchain", "API", "AI", "Nlp", "Python", "ML", "ChatGPT", "Llm"], "location": ["Велика Британія", "Україна"]}
{"title": "Database Developer", "company": "DATAWIZ", "company_type": "Product", "salary": null, "technologies": ["Django", "Webpack", "React", "HTML", "Redis", "SQL", "Go", "Pandas", "Celery", "RabbitMQ", "Etl", "MySQL", "PostgreSQL", "Linux", "Python", "ML", "Angular", "CSS"], "location": ["Україна"]}
{"title": "Python Developer", "company": "Dataforest", "company_type": "Outsource", "salary": "$700-800", "technologies": ["Flask", "API", "HTML", "SQL", "Scraping", "NoSQL", "AI", "Pandas", "Selenium", "BeautifulSoup", "Embers", "Python", "ML"], "location": ["Польща", "Україна"]}
{"title": "Python NLP Developer", "company": "Tangible AI", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Django", "Go", "Git", "AI", "CI/CD", "Nlp", "Python"], "location": ["Сполучені Штати"]}
{"title": "Application Engineer", "company": "UnameIT", "company_type": "Product", "salary": "до $2500", "technologies": ["AI", "Python", "Git", "Fabric"], "location": ["Україна"]}
{"title": "Шукаю Спеціаліста з програмування АІ", "company": "Codeware.Digital", "company_type": "Product", "salary": "$700-1200", "technologies": ["AI", "Git", "TensorFlow", "AWS", "Keras", "Blockchain", "Python", "PyTorch"], "location": ["Україна"]}
{"title": "Python/Django", "company": "Perlyna Devs", "company_type": "Agency", "salary": "$600-3500", "technologies": ["Django", "Python", "Go", "AI"], "location": ["Україна"]}
{"title": "Python developer / strong junior", "company": "dZENcode", "company_type": "Outsource", "salary": "$600-1200", "technologies": ["Django", "API", "SQL", "JavaScript", "NoSQL", "Git", "Go", "AI", "TensorFlow", "AWS", "Python"], "location": ["Україна"]}
{"title": "Strong Middle Python Developer", "company": "level99.vip", "company_type": "Product", "salary": null, "technologies": ["Kafka", "Kubernetes", "NoSQL", "Git", "SQLAlchemy", "GraphQL", "Requests", "Selenium", "Docker", "API", "ML", "SQL", "AI", "Apache", "Python", "HTML", "RabbitMQ", "Postman", "Nginx"], "location": ["Україна"]}
{"title": "Junior software engineer (parsing/reverse)", "company": "Artellence", "company_type": "Product", "salary": "до $2500", "technologies": ["NoSQL", "Parsing", "Redis", "JavaScript", "Requests", "Go", "Selenium", "Docker", "API", "MongoDB", "Java", "SQL", "asyncio", "AI", "BeautifulSoup", "Security", "Python", "Linux", "aiohttp"], "location": ["Україна"]}
{"title": "DAAS Support ENG", "company": "Temerix", "company_type": "Product", "salary": "$700-800", "technologies": ["HTML", "Requests", "SQL", "AI", "NoSQL", "Go", "Moment", "Python", "ML", "CSS"], "location": ["Україна"]}
{"title": "Junior Python Developer (розробка ботів)", "company": "CallC247", "company_type": "Product", "salary": "$700-1200", "technologies": ["Solidity", "AI", "Blockchain", "Python", "Bot"], "location": ["Україна"]}
{"title": "Python developer (US IoT project)", "company": "Romen Personnel", "company_type": "Product", "salary": "$1000-2500", "technologies": ["Iot", "SQL", "AI", "PHP", "OOP", "AWS", "Python"], "location": ["Сполучені Штати"]}
{"title": "Odoo Engineer", "company": "OpsWay", "company_type": "Outsource", "salary": "$800-2000", "technologies": ["JavaScript", "Odoo", "Xml", "Owl", "PostgreSQL", "Python"], "location": ["Україна"]}
{"title": "Experienced Odoo Developer", "company": "hts-experts.com", "company_type": "Product", "salary": "до $2500", "technologies": ["Linux", "HTML", "Requests", "SQL", "Odoo", "JavaScript", "Git", "Go", "AI", "Embers", "Python", "PostgreSQL", "Troubleshooting", "ML", "CSS"], "location": ["Швейцарія"]}
{"title": "Strong Junior / Middle Python Developer", "company": "DATAWIZ", "company_type": "Product", "salary": null, "technologies": ["React", "Git", "Angular", "Webpack", "Redis", "Go", "MySQL", "Docker", "API", "ML", "Django", "SQL", "AI", "PostgreSQL", "Python", "HTML", "Pandas", "Celery", "OOP", "RabbitMQ", "Orm", "Linux", "CSS"], "location": ["Україна"]}
{"title": "Middle Python Developer (Django Framework)", "company": "NeoFin", "company_type": "Product", "salary": "$2000", "technologies": ["RESTful", "React", "Git", "OpenCV", "Flask", "Elasticsearch", "Redis", "JavaScript", "Go", "MySQL", "API", "ML", "Django", "Finance", "SQL", "AI", "PostgreSQL", "Python", "Node.Js", "HTML", "Vue.Js", "CSS"], "location": ["Малайзія", "Польща", "Україна"]}
{"title": "Parsing expert for a long term partnership", "company": "WebDev 247", "company_type": "Product", "salary": "до $2500", "technologies": ["API", "HTML", "JavaScript", "AI", "Python", "ML", "CSS"], "location": ["Україна"]}
{"title": "Python/Django Developer", "company": "ECHOES", "company_type": "Product", "salary": "$600-3500", "technologies": ["Django", "Elasticsearch", "Linux", "Kubernetes", "SQL", "Redis", "Go", "AI", "Celery", "AWS", "Nginx", "RabbitMQ", "PostgreSQL", "Docker", "Python", "GraphQL"], "location": ["Грузія", "Україна"]}
{"title": "Software and MLOps Engineer (Python) (Poland)", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "$2000", "technologies": ["Mlops", "API", "React", "AI", "DevOps", "TensorFlow", "OOP", "AWS", "Python", "ML", "Node.Js"], "location": ["Ізраїль", "Польща"]}
{"title": "Backend Python Developer", "company": "DevIT Group", "company_type": "Outsource", "salary": "$900-1500", "technologies": ["FastAPI", "Django", "Langchain", "API", "Azure", "Redis", "SQL", "Go", "Git", "AI", "AWS", "RabbitMQ", "Linux", "Docker", "Python"], "location": ["Україна"]}
{"title": "Junior/Middle Python developer in test", "company": "Ajax Systems", "company_type": "Product", "salary": "до $2500", "technologies": ["API", "PySide", "PyQt", "Git", "AWS", "Pytest", "Jenkins", "Linux", "Python", "ML"], "location": ["Україна"]}
