{"title": "Senior Python Developer", "company": "Kozak Group", "company_type": "Outstaff", "salary": "$1000-5000", "technologies": ["AI", "Python", "JavaScript"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "FXC Intelligence", "company_type": "Product", "salary": "$5000-7000", "technologies": ["SQL", "Python", "AI", "API", "Docker"], "location": ["Велика Британія"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Linux", "OOP", "Python", "AI", "Git", "API", "Docker"], "location": ["Україна"]}
{"title": "QA Automation Engineer", "company": "PandaFlow", "company_type": "Product", "salary": null, "technologies": ["Selenium", "AI", "Python", "JavaScript"], "location": ["Сполучені Штати"]}
{"title": "Senior Full-Stack Developer/ AI Evangelist", "company": "Softengi", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["ChatGPT", "React", "JavaScript", "CI/CD", "Azure", "Python", "AWS", "AI", "DevOps", "Git", "ML", "Angular", "Copilot"], "location": ["Чехія", "Литва", "Латвія", "Польща", "Україна"]}
{"title": "Python Developers (Permanent/ requires relocation to Dubai, UAE)", "company": "Aspire Technology", "company_type": "Product", "salary": "$7000-10000", "technologies": ["AI", "API", "Python", "Go"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$4000-6500", "technologies": ["Embers", "Go", "SQL", "Python", "NoSQL", "DevOps", "AI", "API", "Django", "FastAPI"], "location": ["Україна", "Польща"]}
{"title": "Senior Full-Stack Engineer Python/Data Engineer", "company": "Intellias", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Dask", "Embers", "Flask", "Spark", "React", "Go", "Pandas", "SQL", "Azure", "Python", "D3", "DevOps", "AI", "Docker", "PySpark", "SQLAlchemy", "Celery"], "location": ["Україна"]}
{"title": "Middle/Senior Python Developer (Telnet)", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$30-35", "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Senior RPA Software Engineer (Location Poland)", "company": "Unicsoft", "company_type": "Outsource", "salary": null, "technologies": ["Linux", "JavaScript", "Go", "SQL", "Python", "AI", "ML", "DevOps", "Git", "API", "Foundation", "HTML"], "location": ["Україна", "Кіпр"]}
{"title": "Senior Python Developer", "company": "JOIDY", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "SQL", "Python", "AWS", "AI", "Django"], "location": ["Україна"]}
{"title": "Senior Infrastructure Engineer", "company": "Demigos", "company_type": "Outstaff", "salary": "до $6000", "technologies": ["Microservices", "Grpc", "Go", "SQL", "Java", "Python", "NoSQL", "AI", "API"], "location": ["Україна"]}
{"title": "Senior Python (Data) Engineer", "company": "Nortal", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Databricks", "SQL", "Azure", "Python", "AI", "DevOps", "Git", "API", "Spark", "PySpark"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Linux", "OOP", "Python", "AI", "Git", "API", "Docker"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "Linux", "Go", "GCP", "Azure", "Python", "AWS", "AI", "Git", "Kubernetes", "Jenkins", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Senior Python Backend Developer", "company": "TechHunt", "company_type": "Product", "salary": "$3500-5000", "technologies": ["Go", "RabbitMQ", "CI/CD", "Python", "Django", "Elasticsearch"], "location": ["Німеччина", "Нідерланди", "Польща", "Україна", "Португалія"]}
{"title": "Data Scientist / Senior Python developer", "company": "Simplify", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "PyTorch", "Tensorrt", "OpenCV", "Python", "Sota", "AI", "Git", "ML"], "location": ["Україна", "Німеччина", "Польща"]}
{"title": "Senior Data Engineer", "company": "Intetics", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Go", "GCP", "Airflow", "SQL", "Python", "Etl", "AWS", "AI", "ML", "Git", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Flask", "OOP", "Go", "SQL", "Python", "MySQL", "AI", "Mvc", "PostgreSQL", "Django"], "location": ["Україна"]}
{"title": "Backend Engineer with AI Integration Experience", "company": "Visarsoft", "company_type": "Outstaff", "salary": null, "technologies": ["TypeScript", "React", "JavaScript", "Nlp", "TensorFlow", "Agile", "Python", "AWS", "Azure", "AI", "Tdd", "Angular"], "location": ["Україна"]}
{"title": "Data and Machine Learning Engineer (Python)", "company": "Softwarium", "company_type": "Outsource", "salary": "$5000-6000", "technologies": ["React", "TensorFlow", "NoSQL", "Embers", "Azure", "AI", "API", "Spark", "Dask", "OOP", "Go", "Scikit-learn", "PyTorch", "SQL", "ML", "Git", "Docker", "Angular", "Pandas", "Python", "AWS", "NumPy"], "location": ["Польща", "Україна"]}
{"title": "Quantitative Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["Go", "OOP", "Python", "AI", "Git", "Linux"], "location": ["Україна"]}
{"title": "SEnior Python WMS", "company": "Mrt", "company_type": "Product", "salary": null, "technologies": ["Linux", "Go", "OOP", "Python", "Wms", "AI", "API"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Python Back-end Developer (JobTestPrep)", "company": "SD Solutions", "company_type": "Outstaff", "salary": "до $8000", "technologies": ["React", "Go", "Apis", "Json", "RESTful", "Kubernetes", "SQL", "Python", "AWS", "CI/CD", "NoSQL", "AI", "Git", "API", "Docker", "Angular"], "location": ["Україна", "Грузія", "Кіпр"]}
{"title": "Senior Python Software Engineer", "company": "InoXoft", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Embers", "Flask", "Terraform", "Go", "Python", "AI", "Git", "Celery"], "location": ["Україна"]}
{"title": "Senior Python Backend Engineer", "company": "Reef Technlogies", "company_type": "Product", "salary": "$7560-11760", "technologies": ["Embers", "Go", "Python", "AI", "Django"], "location": ["Польща"]}
{"title": "Data Engineer/Analyst", "company": "AdPartner", "company_type": "Product", "salary": "$3000-4000", "technologies": ["Embers", "Go", "Pandas", "Scikit-learn", "PyTorch", "TensorFlow", "Airflow", "Python", "AI", "Git", "ML", "NumPy"], "location": ["Німеччина", "Естонія", "Польща", "Португалія", "Україна"]}
{"title": "Senior Backend Python Developer", "company": "Verbit", "company_type": "Product", "salary": "до $8000", "technologies": ["Go", "SQL", "Python", "AWS", "NoSQL", "Redis", "AI"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum Client", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "Linux", "Go", "GCP", "Azure", "Python", "AWS", "AI", "Git", "Kubernetes", "Jenkins", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8000", "technologies": ["Go", "PyTorch", "TensorFlow", "Keras", "Python"], "location": ["Польща", "Україна"]}
{"title": "Senior Full-Stack Engineer Python/React", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["TypeScript", "Dask", "Flask", "React", "Spark", "Go", "Pandas", "SQL", "Azure", "Python", "D3", "DevOps", "AI", "Docker", "PySpark", "SQLAlchemy", "Celery"], "location": ["Україна"]}
{"title": "Senior Python Engineer (Application Platform Track)", "company": "PandaDoc", "company_type": "Product", "salary": null, "technologies": ["Kafka", "asyncio", "Go", "Pandas", "Django", "RabbitMQ", "Git", "SQL", "Python", "AWS", "AI", "PostgreSQL", "Kubernetes", "FastAPI", "Docker", "Rabbimq"], "location": ["Польща", "Португалія", "Україна"]}
{"title": "Middle/Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$2000-5000", "technologies": ["AI", "API", "Python"], "location": ["Україна"]}
{"title": "Senior Backend Engineer", "company": "Launch Labs", "company_type": "Outsource", "salary": null, "technologies": ["TypeScript", "Flask", "React", "Go", "GraphQL", "Python", "AWS", "MongoDB", "ML", "AI", "API", "FastAPI", "Celery"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flask", "Pytest", "Embers", "aiohttp", "Tornado", "PostgreSQL", "AI", "API", "SQLAlchemy", "OOP", "Go", "SQL", "MySQL", "Git", "Linux", "Docker", "Falcon", "Python", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior/Lead Python Developer", "company": "CHI Software", "company_type": "Outsource", "salary": "$3500-5000", "technologies": ["Flask", "JavaScript", "GCP", "CI/CD", "NoSQL", "DevOps", "Django", "aiohttp", "Azure", "PHP", "AI", "API", "Go", "SQL", "Linux", "Elasticsearch", "Docker", "Python", "AWS", "FastAPI"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Engineer", "company": "ELITEX", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Go", "JavaScript", "Python", "AI", "Django"], "location": ["Україна"]}
{"title": "Senior Full Stack Engineer with Python and Golang", "company": "TeamDev", "company_type": "Outstaff", "salary": null, "technologies": ["PostgreSQL", "React", "JavaScript", "GCP", "Go", "SQL", "CI/CD", "Azure", "Python", "AWS", "AI", "Git", "Kubernetes", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Python Back-end Developer /Candidates from Ukraine     JobTestPrep", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6000", "technologies": ["PostgreSQL", "React", "Go", "API", "SQL", "CI/CD", "Python", "AWS", "AI", "NoSQL", "RESTful", "Git", "Kubernetes", "Docker", "Angular", "MongoDB"], "location": ["Україна"]}
{"title": "Team Lead Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": "до $8000", "technologies": ["Flask", "Pytest", "Embers", "aiohttp", "Tornado", "PostgreSQL", "AI", "API", "SQLAlchemy", "OOP", "Go", "SQL", "MySQL", "Git", "Linux", "Docker", "Falcon", "Python", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior Python Developer-a на ізраїльський фінтех проєкт", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Data", "SQL", "Python", "AI", "Git", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Go", "SQL", "Python", "Restapi", "NoSQL", "DevOps", "AI", "API", "Django", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Flask", "PostgreSQL", "React", "JavaScript", "Go", "Apache", "Airflow", "SQL", "Python", "AI", "Git", "Kubernetes", "Jenkins"], "location": ["Польща"]}
{"title": "Senior Python developer (with DevOps experience)", "company": "YozmaTech", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Go", "SQL", "Python", "NoSQL", "DevOps", "AI", "API", "Django", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Fullstack Engineer (python+react)", "company": "Svitla Systems", "company_type": "Outstaff", "salary": null, "technologies": ["TypeScript", "PostgreSQL", "React", "JavaScript", "Go", "CSS", "SQL", "RESTful", "Python", "MySQL", "AI", "ML", "Git", "API", "Django", "HTML"], "location": ["Україна"]}
{"title": "Team Lead Python Developer for VastData", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Multithreading", "OOP", "Databases", "Python", "AI", "Git", "Linux", "Solid"], "location": ["Україна"]}
{"title": "Infrastructure Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Golang", "OOP", "Go", "SQL", "Java", "Python", "AWS", "NoSQL", "AI", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "A-LISTWARE", "company_type": "Outstaff", "salary": "$5000", "technologies": ["Flask", "OOP", "Go", "Apache", "Airflow", "CI/CD", "Python", "AWS", "AI", "DevOps", "Cognito", "API", "MongoDB"], "location": ["Україна"]}
{"title": "ML/Python Senior", "company": "Danavero", "company_type": "Outstaff", "salary": "$2000-5000", "technologies": ["SQL", "CI/CD", "Azure", "Python", "AI", "ML"], "location": ["Україна"]}
{"title": "Software Engineering Team Lead", "company": "AllSTARSIT", "company_type": "Outstaff", "salary": null, "technologies": ["AI", "Go"], "location": ["Україна"]}
{"title": "Python Team Lead", "company": "Mrt", "company_type": "Product", "salary": "до $7500", "technologies": ["Go", "OOP", "Python", "AI", "Linux"], "location": ["Обʼєднані Арабські Емірати"]}
{"title": "Full Stack Developer", "company": "UKR.NET", "company_type": "Product", "salary": null, "technologies": ["React", "JavaScript", "NoSQL", "Redis", "Sqlite", "Redux", "MongoDB", "aiohttp", "AI", "API", "PostgreSQL", "Go", "SQL", "MySQL", "Elasticsearch", "TypeScript", "asyncio", "Python", "MobX"], "location": ["Україна"]}
{"title": "Python developer", "company": "Ciba Health", "company_type": "Product", "salary": null, "technologies": ["Flask", "Go", "Pyramid", "GraphQL", "CSS", "API", "SQL", "RESTful", "Python", "AWS", "DevOps", "AI", "Redis", "ML", "Git", "Kubernetes", "Django", "HTML"], "location": ["Україна"]}
{"title": "Back End Engineer ( Python\\Java\\Go) with Data Engineering experience", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $7500", "technologies": ["Kafka", "CI/CD", "ML", "Flink", "AI", "API", "Spark"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Radency", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Flask", "GCP", "GraphQL", "Postgres", "NoSQL", "Redis", "Flux", "Airflow", "PostgreSQL", "AI", "API", "Spark", "Apache", "SQL", "Git", "Docker", "Elasticsearch", "Pandas", "RabbitMQ", "Python"], "location": ["Україна"]}
{"title": "Sr. Python Developer", "company": "TrustPoint", "company_type": "Product", "salary": null, "technologies": ["Go", "CI/CD", "RESTful", "Python", "AI", "ML", "DevOps", "Git", "API", "Django"], "location": ["Сполучені Штати"]}
{"title": "Python Team Lead", "company": "SoftConstruct", "company_type": "Product", "salary": null, "technologies": ["Kafka", "Ansible", "OOP", "Go", "aiohttp", "Apache", "Airflow", "SQL", "API", "RESTful", "Python", "DevOps", "AI", "Kubernetes", "FastAPI", "Spark", "Beam"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data Skills (AdTech Location Technology Leader)", "company": "Sigma Software", "company_type": "Outstaff", "salary": null, "technologies": ["Emr", "OOP", "Go", "SQL", "Python", "AWS", "AI", "Hadoop", "Spark"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Numerical Technologies", "company_type": "Product", "salary": "$1000-5000", "technologies": ["Go", "RESTful", "Azure", "Python", "AWS", "AI", "Git", "API", "FastAPI", "MongoDB"], "location": ["Польща", "Португалія", "Сінгапур", "Україна"]}
{"title": "Senior Python Developer", "company": "Danavero", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Flask", "JavaScript", "OOP", "Go", "Pyramid", "Node.Js", "API", "CI/CD", "Python", "AWS", "AI", "ML", "Git", "Kubernetes", "Django", "HTML"], "location": ["Польща"]}
{"title": "Team Lead / Senior Python Engineer (Indigo Ag)", "company": "Intelliarts", "company_type": "Outsource", "salary": "$4000-6500", "technologies": ["Go", "Pydantic", "SQL", "Python", "AI", "Redis", "Git", "API", "FastAPI", "SQLAlchemy", "Celery"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "SPD-Ukraine", "company_type": "Outsource", "salary": null, "technologies": ["Flask", "OOP", "JavaScript", "Go", "SQL", "Python", "AWS", "AI", "PostgreSQL", "ML", "Docker", "Celery"], "location": ["Україна"]}
{"title": "Senior/Lead Machine Learning Engineer 2080/06", "company": "Argument", "company_type": "Product", "salary": "до $8500", "technologies": ["Go", "PyTorch", "TensorFlow", "Python", "ML"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Flask", "PostgreSQL", "React", "JavaScript", "Go", "Apache", "Airflow", "SQL", "Python", "AI", "Git", "Kubernetes", "Jenkins"], "location": ["Україна"]}
{"title": "Tech Lead Full-stack Engineer (JS/Python)", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["JavaScript", "GCP", "Go", "SQL", "Python", "AWS", "AI", "NoSQL", "Git", "API", "Django", "MongoDB"], "location": ["Україна"]}
{"title": "Technical Lead Python", "company": "Meest Group", "company_type": "Product", "salary": "$2000-5000", "technologies": ["React", "Go", "Git", "SQL", "CI/CD", "Python", "AWS", "PostgreSQL", "Django", "Docker"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "Star Global", "company_type": "Outsource", "salary": "до $6000", "technologies": ["Embers", "Flask", "Microservices", "PostgreSQL", "Go", "GCP", "SQL", "Python", "MySQL", "AI", "ML", "Git", "API", "FastAPI", "Docker", "SQLAlchemy", "Celery"], "location": ["Україна"]}
{"title": "Senior Python Developer for Ciklum", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["PostgreSQL", "JavaScript", "GCP", "Go", "Apache", "Airflow", "SQL", "Python", "AWS", "AI", "Git", "Kubernetes", "Jenkins"], "location": ["Україна"]}
{"title": "Senior Backend Engineer (Python)", "company": "Bcconsolidator", "company_type": "Product", "salary": "$5800-7000", "technologies": ["Embers", "Go", "Selenium", "GraphQL", "SQL", "Python", "AWS", "AI", "PostgreSQL", "ML", "Apollo", "Angular", "SQLAlchemy"], "location": ["Латвія", "Нідерланди", "Польща"]}
{"title": "Senior Python Engineer with JS/Typescript", "company": "Intellias", "company_type": "Outsource", "salary": null, "technologies": ["TypeScript", "Dask", "Embers", "Flask", "Spark", "React", "Go", "Pandas", "SQL", "Azure", "Python", "D3", "DevOps", "AI", "Docker", "PySpark", "SQLAlchemy", "Celery"], "location": ["Україна"]}
{"title": "Experienced Python Developer - lifetime opportunity", "company": "CleverCrew", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Go", "Postgres", "Svelte", "Jenkins", "AI", "Git", "API", "Django", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Embers", "Go", "SQL", "Python", "NoSQL", "DevOps", "AI", "API", "Django", "FastAPI"], "location": ["Україна", "Грузія", "Польща"]}
{"title": "Senior Python Developer (with DevOps)", "company": "YozmaTech", "company_type": "Outstaff", "salary": "$4000-5500", "technologies": ["Embers", "Chef", "Puppet", "Ansible", "Go", "SQL", "CI/CD", "Azure", "Python", "AWS", "ML", "NoSQL", "DevOps", "AI", "API", "Django", "Docker", "FastAPI"], "location": ["Україна", "Польща", "Грузія"]}
{"title": "Middle/Senior Full-stack Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["React", "Go", "GCP", "CI/CD", "Kubernetes", "Azure", "Jenkins", "AWS", "AI", "RESTful", "Git", "API", "Django", "Docker"], "location": ["Велика Британія", "Польща", "Україна"]}
{"title": "Middle/Senior Python Developer", "company": "Honeycomb Software", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Swagger", "Postman", "CI/CD", "Kubernetes", "RESTful", "Python", "AI", "Git", "API", "Jenkins", "Docker"], "location": ["Польща", "Україна"]}
{"title": "Senior Python Developer for Guardicore", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "Go", "GCP", "Azure", "Python", "AWS", "AI", "Git", "Linux", "Jenkins", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Python Tech Lead", "company": "Dataforest", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Embers", "Flask", "Kafka", "Go", "GCP", "Pandas", "Elasticsearch", "Airflow", "SQL", "Python", "AWS", "NoSQL", "Redis", "AI", "Kubernetes", "Django", "Docker"], "location": ["Німеччина", "Польща", "Словаччина", "Україна"]}
{"title": "Senior Python Developer", "company": "Develux", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Flask", "Go", "GraphQL", "SQL", "CI/CD", "Azure", "Python", "AWS", "AI", "NoSQL", "PostgreSQL", "API", "Django", "Docker", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Python developer (AWS)", "company": "TemaBit Fozzy Group", "company_type": "Product", "salary": null, "technologies": ["OOP", "SQL", "CI/CD", "Python", "AWS", "AI", "NoSQL", "Git", "API"], "location": ["Україна"]}
{"title": "strong Python over Django dev", "company": "Flexyti", "company_type": "Outsource", "salary": null, "technologies": ["OOP", "Go", "SQL", "CI/CD", "Python", "AWS", "AI", "PostgreSQL", "Kubernetes", "Django", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Full-stack (JS/Python) / Tech lead", "company": "Softengi", "company_type": "Outsource", "salary": "$4000-5500", "technologies": ["JavaScript", "GCP", "Go", "SQL", "Python", "AWS", "AI", "NoSQL", "Git", "API", "Django", "MongoDB"], "location": ["Україна"]}
{"title": "Python developer", "company": "Odore", "company_type": "Product", "salary": "$1000-5000", "technologies": ["PostgreSQL", "Pytest", "Postman", "Go", "SQL", "Python", "AWS", "AI", "Git", "API", "SQLAlchemy"], "location": ["Велика Британія"]}
{"title": "Full Stack Developer (Python,React) Miami location", "company": "Global Teams", "company_type": "Outsource", "salary": "до $6000", "technologies": ["Flask", "PostgreSQL", "React", "Go", "GCP", "SQL", "CI/CD", "RESTful", "Python", "Jenkins", "MySQL", "AI", "Git", "API", "Django", "Redux", "MongoDB"], "location": ["Україна"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Go", "Click", "AI", "API", "Moment"], "location": ["Україна"]}
{"title": "Back End Developer", "company": "Nashpush", "company_type": "Product", "salary": "до $6000", "technologies": ["Flask", "OOP", "Go", "Kubernetes", "Saas", "Python", "AWS", "AI", "API", "Django", "Docker"], "location": ["Кіпр", "Україна"]}
{"title": "Senior / Lead Technical Support Developer", "company": "ApomSolutions", "company_type": "Outstaff", "salary": null, "technologies": ["OOP", "GCP", "Oracle", "Java", "Python", "Docker", "AWS", "Azure", "AI", "Kubernetes", "Spark"], "location": ["Україна"]}
{"title": "Lead Backend Engineer ‍", "company": "Madgicx 🇺🇦", "company_type": "Product", "salary": "$2000-5000", "technologies": ["Flask", "Go", "Pandas", "Elasticsearch", "Git", "SQL", "CI/CD", "Python", "AWS", "Jenkins", "MySQL", "Redis", "PostgreSQL", "API", "Django", "Docker", "Celery"], "location": ["Україна"]}
{"title": "Lead Python Developer", "company": "PYGIO", "company_type": "Product", "salary": "$4000-5500", "technologies": ["Go", "SQL", "Python", "AI", "PostgreSQL", "Kubernetes", "Django", "Docker"], "location": ["Україна", "Албанія", "Вірменія", "Польща", "Чехія"]}
{"title": "Senior Python Developer", "company": "UKR.NET", "company_type": "Product", "salary": "$2000-5000", "technologies": ["Elasctisearch", "aiohttp", "asyncio", "Go", "SQL", "Python", "MySQL", "AI", "NoSQL", "Redis", "PostgreSQL", "API", "Elasticsearch", "MongoDB"], "location": ["Україна"]}
{"title": "Sr Python Engineer", "company": "Zaly", "company_type": "Product", "salary": null, "technologies": ["Ansible", "Highload", "SQL", "Python", "PostgreSQL", "Docker"], "location": ["Україна", "Сполучені Штати"]}
{"title": "Senior Python Developer", "company": "Idenon", "company_type": "Product", "salary": null, "technologies": ["Go", "aiohttp", "RabbitMQ", "CI/CD", "Python", "AWS", "Tornado", "Redis", "AI", "Kubernetes", "Docker"], "location": ["Словаччина", "Україна"]}
{"title": "Python Developer", "company": "FrontRunnrs", "company_type": "Product", "salary": "$5000-7000", "technologies": ["JavaScript", "Go", "Foundation", "CSS", "API", "RESTful", "Python", "AWS", "AI", "ML", "Git", "Kubernetes", "Docker", "HTML"], "location": ["Україна"]}
{"title": "Senior Software Engineer", "company": "Mobilunity", "company_type": "Outsource", "salary": null, "technologies": ["Playready", "Dash", "Go", "Requests", "Fairplay", "Azure", "Python", "AWS", "AI", "API"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "InventorSoft", "company_type": "Outstaff", "salary": "$3500-5000", "technologies": ["SQL", "MySQL", "Python", "DevOps", "API", "FastAPI"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with ML experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Node.Js", "Python", "AWS", "AI", "ML", "Ocr", "Angular"], "location": ["Естонія", "Польща", "Україна"]}
{"title": "Python Developer", "company": "KindGeek", "company_type": "Product", "salary": null, "technologies": ["AI", "Python", "Crossplatform", "DevOps"], "location": ["Україна"]}
{"title": "Senior Cloud Developer", "company": "Alcor", "company_type": "Product", "salary": null, "technologies": ["Vue.Js", "JavaScript", "Cloud", "SQL", "Python", "AWS", "NoSQL", "AI", "API"], "location": ["Чехія", "Польща", "Румунія", "Словаччина", "Україна"]}
{"title": "Python Engineer", "company": "MoveUp Recruitment agency", "company_type": "Product", "salary": "до $9000", "technologies": ["Ansible", "Go", "GCP", "CI/CD", "Kubernetes", "Azure", "Python", "AWS", "AI", "API", "Docker"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Bluefield Technologies", "company_type": "Product", "salary": "$5000-6000", "technologies": ["React", "Backbone", "HTML", "aiohttp", "Ccna", "AI", "API", "Networking", "Go", "CSS", "SQL", "Git", "Linux", "Docker", "TypeScript", "asyncio", "Pandas", "RESTful", "Python", "ML"], "location": ["Словаччина", "Україна"]}
{"title": "Python Developer", "company": "Ava Technologies Inc.", "company_type": "Product", "salary": "$4000-5500", "technologies": ["ChatGPT", "Embers", "Go", "Serverless", "Python", "AWS", "AI", "MongoDB"], "location": ["Чехія", "Нідерланди"]}
{"title": "Senior Software Engineer (Backend), Voice Services", "company": "Data Science UA", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Go", "Click", "AI", "API", "Moment"], "location": ["Україна"]}
{"title": "Quality Assurance Architect (Networking)", "company": "PLVision", "company_type": "Outsource", "salary": null, "technologies": ["Embers", "Pytest", "Robot Framework", "Go", "Automation", "Ansible", "API", "Kubernetes", "CI/CD", "Python", "AI", "Unittest", "Architect", "Linux", "Docker", "Networking"], "location": ["Україна"]}
{"title": "Team Lead Python", "company": "Capital Recruiters", "company_type": "Product", "salary": "$2000-5000", "technologies": ["Flask", "React", "SQL", "Python", "API", "Django"], "location": ["Україна"]}
{"title": "AI Enthusiast / Machine Learning", "company": "King's Choice", "company_type": "Product", "salary": "$2000-5000", "technologies": ["ChatGPT", "AI", "Python"], "location": ["Україна"]}
{"title": "Senior Python Engineer", "company": "KnubiSoft", "company_type": "Outsource", "salary": "$2000-5000", "technologies": ["Embers", "OOP", "Go", "GraphQL", "CSS", "Python", "AWS", "AI", "API", "Django"], "location": ["Україна"]}
{"title": "Algorithm Developer for Corsound AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": null, "technologies": ["Embers", "Go", "PyTorch", "TensorFlow", "Algorithms", "Python", "AI", "API"], "location": ["Грузія", "Польща", "Україна"]}
{"title": "Senior Python/DevOps Developer", "company": "Chrysalis Gate", "company_type": "Outstaff", "salary": "$6000-8000", "technologies": ["React", "Kafka", "Moment", "Python", "AWS", "AI", "DevOps", "Redis", "Git", "API", "Spark"], "location": ["Литва", "Україна", "Польща", "Словаччина", "Румунія"]}
{"title": "Python Back-End Engineer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "до $8500", "technologies": ["GCP", "CI/CD", "Azure", "Python", "AWS", "ML", "Redis", "AI", "Kubernetes"], "location": ["Україна"]}
{"title": "Senior/Lead Python Engineer with Data skills", "company": "Sigma Software", "company_type": "Outsource", "salary": null, "technologies": ["Go", "OOP", "SQL", "Python", "AWS", "AI", "Spark"], "location": ["Україна"]}
{"title": "Senior Full-stack Developer with OCR experience", "company": "8allocate", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Node.Js", "Python", "AWS", "AI", "ML", "Ocr", "Angular"], "location": ["Україна"]}
{"title": "Senior Data Scientist for the oil and gas industry", "company": "SSA Group", "company_type": "Outsource", "salary": null, "technologies": ["Go", "Pandas", "Scikit-learn", "TensorFlow", "SQL", "Azure", "Python", "NumPy"], "location": ["Україна"]}
{"title": "Corsound AI - Senior Algorithms Developer", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$3000-4000", "technologies": ["Embers", "Go", "PyTorch", "TensorFlow", "Algorithms", "Python", "AI", "API"], "location": ["Україна", "Грузія"]}
{"title": "Senior Data Scientist for the oil and gas data prediction solutions", "company": "SSA Group", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["Go", "Pandas", "Scikit-learn", "TensorFlow", "SQL", "Azure", "Python", "AI", "NumPy"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Quickstaffing LLC", "company_type": "Outstaff", "salary": null, "technologies": ["Go", "Pandas", "SQL", "Python", "Jupyter Notebook", "AI", "Spark"], "location": ["Вірменія"]}
{"title": "Senior Backend Engineer for Neolithics AI", "company": "SD Solutions", "company_type": "Outstaff", "salary": "$5000-6500", "technologies": ["Go", "GCP", "CI/CD", "Azure", "Python", "AWS", "ML", "Redis", "AI", "Kubernetes"], "location": ["Україна"]}
{"title": "Mid-Senior Python developer", "company": "Akvelon Tech Ukraine", "company_type": "Outsource", "salary": "$1000-5000", "technologies": ["AI", "API", "Python", "Go"], "location": ["Польща"]}
{"title": "Python Developer (Data-driven)", "company": "TechbrainJobs", "company_type": "Product", "salary": "$6000-8000", "technologies": ["Linux", "Go", "SQL", "CI/CD", "Python", "AWS", "AI", "Git", "API", "Docker"], "location": ["Ізраїль"]}
{"title": "Middle/Senior Python/Go Engineer", "company": "Akvelon", "company_type": "Outsource", "salary": null, "technologies": ["JavaScript", "Go", "Python", "AI", "ML", "Git", "API"], "location": ["Польща", "Сербія", "Португалія"]}
{"title": "Senior Software Engineer (DataDiscovery)", "company": "MEGOGO", "company_type": "Product", "salary": "$1000-5000", "technologies": ["Kafka", "OOP", "Go", "Apache", "API", "SQL", "Click", "Python", "AWS", "MySQL", "PostgreSQL", "Kubernetes", "Docker", "Spark", "MongoDB"], "location": ["Україна"]}
{"title": "Senior Python Developer", "company": "Ciklum International", "company_type": "Outsource", "salary": null, "technologies": ["Flux", "Go", "GCP", "Azure", "Python", "AWS", "AI", "Git", "Linux", "Jenkins", "Docker", "MongoDB"], "location": ["Україна"]}
{"title": "Python Full Stack Developer", "company": "Atto Trading", "company_type": "Product", "salary": null, "technologies": ["TypeScript", "React", "Linux", "Go", "Node.Js", "CSS", "SQL", "Click", "MySQL", "Python", "AI", "PHP", "DevOps", "Git", "ML", "Foundation", "Angular", "HTML"], "location": ["Україна"]}
{"title": "Tech/Team Lead (Python)", "company": "Indigo Tech recruitment", "company_type": "Product", "salary": null, "technologies": ["Go", "Pandas", "PyTorch", "SQL", "Python", "AWS", "AI", "ML", "PostgreSQL", "API", "FastAPI"], "location": ["Франція"]}
{"title": "Senior Backend Engineer (Python)", "company": "Super Dispatch", "company_type": "Product", "salary": "$5000-6500", "technologies": ["Go", "GCP", "Ddd", "CI/CD", "Kubernetes", "Python", "AWS", "AI", "API", "Django"], "location": ["Узбекистан"]}
